### ISSUE TITLE
Failing github actions

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#107]
There seem to be logging errors that make github actions fail currently. This is a bug we need to fix. 

https://github.com/welfare-state-analytics/riksdagen-corpus/pull/105#issuecomment-1002482202

**Comment by ninpnin** [comment]
Under issue #101 , I was talking about doing the testing against the original OCR'd XML documents. This testing paradigm would replace whatever the logging is trying to accomplish now. I think we can remove the action that yields these problems, and implement the new test suite later. What do you think @MansMeg ?

**Comment by MansMeg** [comment]
That works fine with me. Although I guess we want to add additional test suites, not just the OCR tests? Like checking the files follows the schema and in the long run that changes doesn't overwrite previous manually annotated parts.

**Comment by MansMeg** [comment]
The most important is just that we dont get a failed tests error message when creating a PR.

**Comment by ninpnin** [comment]
I guess there is a bit of confusion. At the moment, we have

1. A test suite that works fine
2. Logging of changed files that does not work

I would remove part 2, and implement tests that provide an equivalent level of security later.

**Comment by MansMeg** [comment]
Ah. Ok. Yes, that sounds good!

**Comment by ninpnin** [comment]
Done.
