### ISSUE TITLE
Reference your material from Wikidata 

### ISSUE THREAD

**Issue by salgo60** [welfare-state-analytics/riksdagen-corpus#108]
Eg. Wikidata [Q96781246](https://www.wikidata.org/wiki/Q96781246) "Anders Andersson i Skäringby" is mentioned that he was part of 1809 1810 in document "[Personregister till rikets ständers protokoll för tiden från och med år 1809 till och med år 1866](https://weburn.kb.se/riks/metadata/08/21798908.html)"--> I would like to use this document as the Source **but also point more exact were in the document this person is mentioned**

**Question**: Do you support the possibility to directly point to a location in the document or is this available some where else... 

Small test WIkidata [Q96781246#P39](https://www.wikidata.org/wiki/Q96781246#P39)
![image](https://user-images.githubusercontent.com/14206509/147758724-83fa74e0-4a5d-431a-800e-2492b610608b.png)

![image](https://user-images.githubusercontent.com/14206509/147758235-1a2b7c1b-8d85-469a-9b99-ae53ecc718ad.png)

that is XML [Personregister till rikets ständers protokoll för tiden från och med år 1809 till och med år 1866.](https://weburn.kb.se/riks/metadata/08/21798908.html)  --> file del [1 text i XML-format](https://weburn.kb.se/riks/st%C3%A5ndsriksdagen/xml/persreg_1809-1866__/persreg_1809-1866___01.xml) 

```xml
<block blockType="Text" pageElemId="{0383A77B-204C-4C38-AB07-70C7F7981014}" l="4635" t="1784" r="5444" b="2191"><region><rect l="4635" t="1784" r="5444" b="2191"/></region>
<text id="{0383A77B-204C-4C38-AB07-70C7F7981014}">
<par align="Justified" leftIndent="1100" rightIndent="100" startIndent="-1100" lineSpacing="1080">
<line baseline="1823" l="4641" t="1790" r="5438" b="1833"><formatting lang="Swedish">Andersson, Anders, Skäringby, för</formatting></line>
<line baseline="1868" l="4685" t="1838" r="5436" b="1878"><formatting lang="Swedish">Närdinghundra härad av Stockholms län</formatting></line>
<line baseline="1914" l="4688" t="1882" r="4843" b="1925"><formatting lang="Swedish">1809/10.</formatting></line></par>
<par align="Justified" startIndent="1100" lineSpacing="1032">
<line baseline="2004" l="4688" t="1973" r="4874" b="2005"><formatting lang="Swedish">1809—10.</formatting></line></par>
<par align="Justified" rightIndent="100" startIndent="1100" lineSpacing="1032">
<line baseline="2045" l="4686" t="2013" r="5433" b="2054"><formatting lang="Swedish">Memorial och yttranden I: 572—578,</formatting></line>
<line baseline="2089" l="4642" t="2057" r="5435" b="2098"><formatting lang="Swedish">581-583, 586—587. II: 26-27, 280—</formatting></line>
<line baseline="2133" l="4641" t="2103" r="5434" b="2136"><formatting lang="Swedish">282. lil: 346—350. IV: 197—199. V:</formatting></line>
<line baseline="2179" l="4641" t="2148" r="5121" b="2186"><formatting lang="Swedish">527. X: 161, 660—661.</formatting></line></par>
</text>
</block>
```

**Comment by ninpnin** [comment]
The **personregister** files are not part of the official corpus, though we are familiar with them and have worked on them for this exact purpose https://github.com/welfare-state-analytics/riksdagen-ocr . In the corpus, we will eventually have unique IDs for each paragraph/segment.

**Comment by salgo60** [comment]
@ninpnin thanks please keep me updated if you get unique ids and how we should link a "Riksdagens document"

* I just found an error in Wikipedia/WIkidata see [discussion](https://sv.wikipedia.org/wiki/Diskussion:Lista_%C3%B6ver_ledam%C3%B6ter_av_Sveriges_riksdags_andra_kammare_1941%E2%80%931944 ) about the [Wikipedia listpage](https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_ledam%C3%B6ter_av_Sveriges_riksdags_andra_kammare_1941%E2%80%931944) 
   * The following two persons was linked to the same physical person
       * Stockholms stad Ebon Andersson, fil. lic., bibliotekarie, h
       * Fyrstadskretsen Ebon Andersson, bibliotekarie, s

In the Riksdagen document [E29O1](https://www.riksdagen.se/sv/dokument-lagar/dokument/protokoll/1941----andra-kammaren----nr-i_E29O1/html) they are listed as 
* 11  Bibliotekarien, fil. lic. Ebon Maria Isabella Andersson.
* 104  Fru Ebon Olivia Bernhardina Andersson i Malmö.

In this example we have identification in an unique document with an unique number [E29O1](https://www.riksdagen.se/sv/dokument-lagar/dokument/protokoll/1941----andra-kammaren----nr-i_E29O1/html) --> we can have that information in Wikidata and create sorted lists --> we rather easy can see if we miss someone...

WIth the number of people and documents I feel we need to think twice so we easy can find errors like this...
* in WIkidata we have the Qnumber
* and I guess you will also have an unique number for a Swedish PM (that I guess we also should have in WIkidata as a property)
