### ISSUE TITLE
Ambiguous parties in the metadata

### ISSUE THREAD

**Issue by ninpnin** [welfare-state-analytics/riksdagen-corpus#109]
Some of the MPs in mop.csv have ambiguous party names, e.g.

Carl Hederstierna,**Unknown n**,Mandatperiod: 1922–1929,Första kammaren,1921,1927,,man,carl_hederstierna_063a74,,,,,

These should be replaced with unambiguous party names.

**Comment by salgo60** [comment]
I think you need linked data for all the parties people are part of... 

A good source is the book  Tvåkammar-riksdagen 1867-1970  e.g.

![image](https://user-images.githubusercontent.com/14206509/149622289-703e0b05-4b91-42a0-831b-f209cfe42440.png)

![image](https://user-images.githubusercontent.com/14206509/149622212-b5fc6ea5-b1ef-48b0-b241-8ba079f35d6d.png)

* jfg 1920-21 - Jordbrukarnas fria grupp ([Q10540831](https://www.wikidata.org/wiki/Q10540831))
* bf 1922-1943 - Bondeförbundet ([Q110472693](https://www.wikidata.org/wiki/Q110472693))

My understanding is that in the early 1900 people changed "parties" a lot see my samples of some people and parties see **[Användare:Salgo60/IriksdagenkalladPartier](https://sv.wikipedia.org/wiki/Anv%C3%A4ndare:Salgo60/IriksdagenkalladPartier)** and we dont have this information in Wikidata at all that will be the next project after "I Riksdagen kallad"

![image](https://user-images.githubusercontent.com/14206509/149622262-cd668c3a-1c3e-44ed-be28-cece382ad56c.png)

**Comment by rbbby** [comment]
Think this is solved now?

**Comment by MansMeg** [comment]
Great! Can you check Väinös example? then close this?

**Comment by ninpnin** [comment]
The file with the problem doesn't exist anymore.
