### ISSUE TITLE
Accented characters in regex patterns

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#111]
Noticed that we are listing accented characters manually in the regex patterns and only include åäöéÅÄÖÉ. We should probably switch to [À-ÿ] which I believe captures all potential characters used in names, etc.?

https://github.com/welfare-state-analytics/riksdagen-corpus/blob/dev/input/segmentation/patterns.json

**Comment by rbbby** [comment]
Replace regex patterns åäöé ÅÄÖÉ everywhere with:

- [ ] Capital letters: À-Þ
- [ ] Lowercase letters: ß-ÿ

Also check if this unicode list is comprehensive against all names in the metadata catalog.

**Comment by rbbby** [comment]
The characters ž, ć are currently not captured by the expanded regex. Look into including them in the regex.

**Comment by ninpnin** [comment]
@rbbby This test could be automated. Read in the patterns, and then match all names in names.csv (person-names.csv ?) against that.

**Comment by rbbby** [comment]
@ninpnin Would work but we could also just add "Latin Extended-A" unicode indices: 256-383 (r'[Ā-ſ]'). Number 329 is depreceated but probably does not matter. It however includes both small and capital letters (seems to switch every other character in the list) so depends on if we can include it in a nice way.
