### ISSUE TITLE
Megaissue for problems with Wikidata

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#112]
Incorrect wikidata will be listed here for fixing later on.

- [ ] start-end (1875-1975) https://www.wikidata.org/wiki/Q5555684

**Comment by rbbby** [comment]
People with more than one name in native language:
Q432059, Q6196285

**Comment by rbbby** [comment]
People who have missing party value for a given term, that also have party values filled for some other term which conflicts with an individual level party value:
Q18238811, Q3357513, Q4931171, Q4941925, Q4981479, Q53733, Q6178909, Q724410

**Comment by rbbby** [comment]
(vice) prime ministers currently lack connection to the government they are the head of

**Comment by rbbby** [comment]
Speaker list:
- third vice speaker (present in unichameral era)
- got both "första/andra kammarens vice talman" and "första/andra kammarens förste vice talman", I assume these are the same position?

**Comment by rbbby** [comment]
Ministers are missing at least for 1920, investigate further

**Comment by BobBorges** [comment]
Closing. Issues are repeated in other issues. MEGAissues are bad for MINIMAL PRs.

**Comment by MansMeg** [comment]
Yes. This is legacy. But do we have this in other issues?
