### ISSUE TITLE
hyphen error

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#120]
I just got this comment from David:

This is great, thanks for the heads up! Just from randomly clicking around, I noticed a word that looked like it was a line break, and it seems to have a soft-hyphen character (0xAD):

 reserva ­ tion

in https://github.com/welfare-state-analytics/riksdagen-corpus/tree/main/corpus/protocols/201617/prot-201617--89.xml

I don't know if these are common, but I wanted to let you know! I'm not sure if I've ever seen one before.

**Comment by ninpnin** [comment]
The link is broken.

**Comment by MansMeg** [comment]
Link is fixed. Old API.

**Comment by ninpnin** [comment]
Should we remove these? Can be done easily with regex.

**Comment by MansMeg** [comment]
I don't know. Or should we replace them with ordinary hyphens instead? Do we have any examples of these?

Or rather, what is the reason for these hyphens and how many are there?

**Comment by ninpnin** [comment]
If a "soft hyphen" is what I think it is, we can remove them without losing information. For instance

>reserva(-)tion

would be perfectly alright as

>reservation

in any context. It's just something we inherit from the HTML structure, where it might be beneficial to be able to split rows more flexibly.

**Comment by MansMeg** [comment]
Let's be very sure about this. I think the probability should be 0.95 that we have less than 1% of all soft hyphens that can be removed correctly.

```
> mean(rbeta(10000, 1, 300) < 0.01)
[1] 0.9504
```
This means that if only one hyphen cannot be removed out of 300 we can be sure to remove the rest. I think this can be a good quality check in general.

**Comment by ninpnin** [comment]
We seem to have 59379 lines with this character in the 2000s.

**Comment by ninpnin** [comment]
Done in https://github.com/welfare-state-analytics/riksdagen-corpus/commit/0c4b2a5089c869d05605d728a453c07aede90766 .
