### ISSUE TITLE
Minor fixes in 0.4 after I went through the API

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#121]
I have now gone through the corpus API as of now. I can see the following minor issues to be fixed together with the quality. I think anything takes a very long time we should discuss if we need it in 0.4 or if it can be pushed down the line. 

- [x] #127
- [x]  Is person.csv better than individual.csv? Yes
- [x] #130
- [x]  location.csv is not super-clear to me. Can we call it name_location_specifier.csv or similar instead.
- [x] party_mapping should be a CSV
- [x] combine prime_minister.csv and minister.csv?
- [x] #128
- [x] #129
- [x] remove accuracy_upper_bound.csv from root
- [x] add person_id column
- [x] add readmes everywhere
- [x] make file row and column order deterministic
- [x] match against minister file filtered in 2 different ways

**Comment by ninpnin** [comment]
- [x] The name _member.csv_ doesn't really communicate anything. Perhaps parliamentary-roles.csv / parliamentary-mandate-periods.csv / elected-officials.csv ?

- [x] location.csv -> name-in-parliament-specifiers.csv

- [x] The one json file should be converted to a csv.

- [x] I agree with Måns on the merging of prime ministers and ministers.

**Comment by MansMeg** [comment]
I agree on member. Its essentially a time period a person is elected to the parliament, not the person. Although, Im not sure which is best. Maybe @fredrik1984 or @Stubbendorff  might have an idea?

**Comment by fredrik1984** [comment]
I don't recall what the member.cvs file contains. Can paste the link to it here so I can take a look?

**Comment by MansMeg** [comment]
member contains the time periods a person is a member of the parliament. We are gearing toward calling it member-of-parliament.csv

**Comment by fredrik1984** [comment]
Ok. I guess the important thing is that we identify individual actors that we then can attach relevant roles/metadata to, such as time period in parliament. So the member.cvs should be used for that kind of metadata, I guess. But if you are looking for a name for that file, maybe mp_term-of-office.cvs would do? I don't know if this answers your question though : )
