### ISSUE TITLE
Handling party in the API

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#123]
At the moment we have 62% party values tied to time periods in the members of parliament file (which is how we want it).
We also have individual level party affiliations that can be used to impute time specific data by placing assumptions, for example if an individual only has been affiliated with a single party, or going further with parties that has had mandates in riksdagen, or even further by imputing if the party had mandates in riksdagen at a given time point, etc.

The question is how do we want to handle this? Some assumptions are made on the fly in the matching algorithm, but how should the data be stored for the end user?

**Comment by MansMeg** [comment]
I think we should not impute dates, but Im not sure? Can you be more explicit and maybe give an example?

**Comment by salgo60** [comment]
FYI: have started testing with dates for parties in Wikidata and follow the book "Tvåkammar-riksdagen 1867-1970" I guess we should also have partigroups... see Wikipedia article "[Moderaterna#Schematisk organisationshistorik för nuvarande Moderata samlingspartiet](https://sv.wikipedia.org/wiki/Moderaterna#Schematisk_organisationshistorik_för_nuvarande_Moderata_samlingspartiet)"

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/14206509/156921067-2c42f194-3e7a-4708-a141-646a69e9eb4e.png">

 
Example Anton Hahn WD [Q5782935](https://www.wikidata.org/wiki/Q5782935)
* Book ["Tvåkammar-riksdagen 1867-1970"](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfsNg)
<img width="629" alt="image" src="https://user-images.githubusercontent.com/14206509/156920802-f98d2c63-0ef3-498a-a2a0-586e8462ba42.png">
 
 * [WIkipedia](https://sv.wikipedia.org/wiki/Anton_Hahn) 
 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/14206509/156920790-48ae3e4e-b6eb-4e2e-99b9-255845ad6f67.png">

* Wikidata [Q5782935#P102](https://www.wikidata.org/wiki/Q5782935#P102)

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/14206509/156920983-79e8c236-ff09-4d3b-8dc9-66e1bfb4585f.png">
 
[ Timeline what WD has connected to the book Tvåkammar-riksdagen 1867-1970](https://js.histropedia.com/apps/query-timeline/index.html?q=SELECT%20distinct%20?person%20?personLabel%20(SAMPLE(?SPA)%20AS%20?SPA)%20%20(sample(?bild)%20AS%20?bild)%20%0A?birth%20?death%20?partyLabel%20WHERE%20%7B%0A%0A%20%20VALUES%20?member%20%7B%0A%20%20%20%20wd:Q33071890%20%0A%20%20%20%20wd:Q81531912%20%0A%20%20%20%20wd:Q82697153%20%0A%20%20%20%20wd:Q10655178%20%0A%20%20%7D%0A%20%20?person%20wdt:P39%20?member;%0A%20%20%20%20wdt:P1343%20?source.%0A%20%20?person%20p:P1343%20?pTva.%0A%20%20OPTIONAL%7B?person%20wdt:P102%20?party%7D%0A%20%20OPTIONAL%7B?person%20wdt:P569%20?birth%7D%0A%20%20OPTIONAL%7B?person%20wdt:P570%20?death%7D%0A%20%20?pTva%20ps:P1343%20wd:Q110346241.%0A%20%20?pTva%20prov:wasDerivedFrom%20%5B%20pr:P4819%20?SPAid%20%5D.%0A%0A%20%20OPTIONAL%20%7B?person%20wdt:P18%20?bild%7D.%0A%20%0A%20%20BIND(URI(CONCAT(%22https://portrattarkiv.se/details/%22,?SPAid))%20AS%20?SPA)%0A%0A%20%20SERVICE%20wikibase:label%20%7B%20bd:serviceParam%20wikibase:language%20%22sv,en%22.%20%7D%0A%7D%20GROUP%20BY%20%20?person%20?personLabel%20%20?death%20?birth%20?partyLabel%0Aorder%20by%20?partyLabel&md=true&g=article&l=SPA&t=personLabel&s=birth&e=death&i=bild&d=0&c=partyLabel&f=partyLabel&v=t)

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/14206509/159812852-3095a730-c122-469a-a22b-1abb08e85c6c.png">

* same but [link svWikipedia article](https://js.histropedia.com/apps/query-timeline/index.html?q=SELECT%20distinct%20?person%20?personLabel(sample(?bild)%20AS%20?bild)%20%0A?birth%20?death%20?partyLabel?wiki%20WHERE%20%7B%0A%0A%20%20VALUES%20?member%20%7B%0A%20%20%20%20wd:Q33071890%20%0A%20%20%20%20wd:Q81531912%20%0A%20%20%20%20wd:Q82697153%20%0A%20%20%20%20wd:Q10655178%20%0A%20%20%7D%0A%20%20?person%20wdt:P39%20?member;%0A%20%20%20%20wdt:P1343%20?source.%0A%20%20?person%20p:P1343%20?pTva.%0A%20%20OPTIONAL%7B?person%20wdt:P102%20?party%7D%0A%20%20OPTIONAL%7B?person%20wdt:P569%20?birth%7D%0A%20%20OPTIONAL%7B?person%20wdt:P570%20?death%7D%0A%0A%20%20OPTIONAL%20%7B?person%20wdt:P18%20?bild%7D.%0A%20%0AOPTIONAL%20%7B%0A%20%20%20%20%20%20?wiki%20schema:about%20?person%20.%0A%20%20%20%20%20%20?wiki%20schema:inLanguage%20%22sv%22%20.%0A%20%20%20%20%20%20?wiki%20schema:isPartOf%20%3Chttps://sv.wikipedia.org/%3E%20.%0A%20%20%20%20%7D%0A%20%20SERVICE%20wikibase:label%20%7B%20bd:serviceParam%20wikibase:language%20%22sv,en%22.%20%7D%0A%7D%20GROUP%20BY%20%20?person%20?personLabel%20%20?death%20?birth%20?partyLabel%20?wiki%0Aorder%20by%20?partyLabel&md=true&g=article&l=wiki&t=personLabel&s=birth&e=death&i=bild&d=0&c=partyLabel&f=partyLabel&v=t)

**Comment by ninpnin** [comment]
Continued in #201
