### ISSUE TITLE
Include data source

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#125]
Include data source in metadata files.

- [ ] Include data source ('wikidata'/'statskalender'/'personregister')

_Originally posted by @ninpnin in https://github.com/welfare-state-analytics/riksdagen-corpus/issues/99#issuecomment-1031231026_

**Comment by salgo60** [comment]
I did an overview what sources Wikidata has for Swedish PMs see https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/36#issuecomment-1045980893 [SPARQL](https://w.wiki/4tjy) and its very much a **Work in Progress**

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/14206509/155960030-f131a66e-08cc-420c-94ca-f8a647b7bf3e.png">

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/14206509/155960260-9d06029f-a2a3-4cfb-9b79-2d924d5d81b5.png">

**Comment by ninpnin** [comment]
Deprecated
