### ISSUE TITLE
Add our own id to all files and name it based on the CSV-file. So government file will have one column with government_id etc.

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#127]

**Comment by BobBorges** [comment]
> our own id

Is this still on the table?

![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/2ec0bec3-abb9-4a0d-b7b6-ce39ccfce2df)

Closing: reopen if necessary.

**Comment by MansMeg** [comment]
It looks good for now. We need to have our own persistent id (using uuid)s later on.
