### ISSUE TITLE
Handling wikidata queries date imputation

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#133]
When only a year is given for a date in wikidata the query will extend the date to YYYY-01-01. Does not matter for most intents and purposes and it is being handled for matching. But we should probably discuss if this is how we want to have it / what to do about it / make the format more explicit in the corpus.

**Comment by MansMeg** [comment]
I see two solutions:
1) Just have year (ie YYYY)
2) Use (YYYY-00-00)

the important part is that should fail for date parsers so the users will have solve it explicitly. Ie defensive data.

**Comment by salgo60** [comment]
In Wikidata you have date precision see [Help:Dates](https://www.wikidata.org/wiki/Help:Dates#Precision)

When creating the [vice speakers timeline](https://tinyurl.com/viceSpeakerSv) from Wikidata we have "bad" data with different precisions --> I also in the [SPARQL](https://query.wikidata.org/embed.html#SELECT%20%20%20%3Fspeaker%20%3Fitem%20%3FitemLabel%20%3FstartD%20%3FstartPrecision%20%3FendD%20%3FendPrecision%0A%3FfollowsLabel%20%3FfollowedbyLabel%20%0A%28GROUP_CONCAT%28DISTINCT%20%3FstatedinL%3B%20SEPARATOR%20%3D%20%22%2C%20%22%29%20AS%20%3Fstatedin%29%20%0A%28GROUP_CONCAT%28DISTINCT%20%3FnamniRiksdagen%3B%20SEPARATOR%20%3D%20%22%2C%20%22%29%20AS%20%3FRiksdagenkallad%29%20%3Fimg%20%3Farticle%0A%20%0AWHERE%20%7B%0A%20%20%20VALUES%20%3FlistT%20%20%7Bwd%3AQ110785766%20wd%3AQ110785785%20wd%3AQ110811796%20wd%3AQ110811796%20wd%3AQ110811805%20wd%3AQ110812751%20wd%3AQ110812759%20%7D%0A%20%20%20%3Fitem%20p%3AP39%20%20%3FpTalman.%0A%20%20%20%3FpTalman%20ps%3AP39%20%3FlistT.%20%0A%20%20%20OPTIONAL%20%7B%3Fitem%20wdt%3AP18%20%3Fimg%7D%0A%20%20%20OPTIONAL%20%7B%3FpTalman%20pqv%3AP580%20%3FstartNode.%0A%20%20%20%3FstartNode%20wikibase%3AtimeValue%20%3FstartD%20.%0A%20%20%20%3FstartNode%20wikibase%3AtimePrecision%20%3FstartPrecision%20%7D%0A%20%20%20OPTIONAL%20%7B%3FpTalman%20pqv%3AP582%20%3FendNode.%0A%20%20%20%3FendNode%20wikibase%3AtimeValue%20%3FendD%20.%0A%20%20%20%3FendNode%20wikibase%3AtimePrecision%20%3FendPrecision%20%7D%0A%20%20%20OPTIONAL%20%7B%3FpTalman%20pq%3AP1365%20%3Ffollows%7D%0A%20%20%20OPTIONAL%20%7B%3FpTalman%20pq%3AP1366%20%3Ffollowedby%7D%0A%20%20%20OPTIONAL%20%7B%3Fitem%20wdt%3AP2561%20%3FnamniRiksdagen%7D%0A%0A%20%20%20%20OPTIONAL%20%7B%3Fitem%20%20p%3AP39%20%20%5Bprov%3AwasDerivedFrom%20%5B%20pr%3AP248%20%3Fstatedin%20%5D%5D.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Fstatedin%20rdfs%3Alabel%20%3FstatedinL.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20FILTER%28%28LANG%28%3FstatedinL%29%29%20%3D%20%22en%22%29%0A%20%20%20%20%20%7D%20.%0A%20%20%20%20%3FlistT%20rdfs%3Alabel%20%3Fspeaker%20%20FILTER%28%28LANG%28%3Fspeaker%29%29%20%3D%20%22en%22%29%0A%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%3Farticle%20schema%3Aabout%20%3Fitem%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AinLanguage%20%22sv%22%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E%20.%0A%20%20%20%20%7D%20%20%0A%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Csv%22.%20%7D%0A%7D%20group%20by%20%20%3Fitem%20%3FitemLabel%20%3FstartD%20%3FstartPrecision%20%3FendD%20%3FendPrecision%20%3FfollowsLabel%20%3FfollowedbyLabel%20%3Fspeaker%20%3Fimg%20%3Farticle%0Aorder%20by%20%3Fspeaker) retrieved the precision 

<img width="691" alt="image" src="https://user-images.githubusercontent.com/14206509/154799202-398731ae-4c46-4f62-9de9-6ac017de5c89.png">

**OT**: Have you thought of setting up your own "Wikidata" the software is free and called [Wikibase](https://wikiba.se/) and soon its even easier when they [release a cloud version](https://addshore.com/2022/01/pre-launch-announcement-of-wikibase-cloud-wikidatacon/) 

One pattern I like is if we could do SPARQL federation i.e. send SPARQL queries between us... example [Riksarkivet TORA](https://riksarkivet.se/tora) has an endpoint [example query Tora --> Wikidata ](https://tora.entryscape.net/snorql/?query=PREFIX+wd%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0D%0APREFIX+wdt%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0D%0ASELECT+DISTINCT+%3Finstance+%3FTORA_label+%3FTORA_province_name+%3FwdLabel+%3FwdAdminLabel++%3FTORA_parishcode+%3FTORA_wd+%3FTORA_wd+%3FWD+%3FWDsame+%3Fitem+%3FWiki%0D%0AWHERE+%7B+%3Finstance+a+%3Chttps%3A%2F%2Fdata.riksarkivet.se%2Ftora%2Fschema%2FModernParish%3E.%0D%0A%3Finstance+skos%3AaltLabel+%3FTORA_label+.%0D%0AOPTIONAL+%7B%3Finstance+tora%3Aprovince_name+%3FTORA_province_name%7D%0D%0A%3Finstance+tora%3Aparishcode+%3FTORA_parishcode+.%0D%0A%3Finstance++rdfs%3AseeAlso+%3FTORA_wduri+.%0D%0ABIND+%28REPLACE%28str%28%3FTORA_wduri%29%2C%22https%3A%2F%2Fwww.wikidata.org%2Fwiki%2F%22%2C%22%22%29+AS+%3FTORA_wd%29.%0D%0ABIND+%28REPLACE%28str%28%3Fitem%29%2C%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%22%2C%22%22%29+AS+%3FWD%29.%0D%0A++BIND%28%0D%0A+++IF%28%3FWD+%3D+%3FTORA_wd%2C+%22Y%22%2C++%22N%22%29%0D%0A++++AS+%3FWDsame%29.%0D%0ASERVICE+%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E+%7B+%0D%0A++++%3Fitem+wdt%3AP31+wd%3AQ1523821%3B+wdt%3AP777+%3FTORA_parishcode+.+%0D%0A%09OPTIONAL+%7B%0D%0A%09%09%3Fitem+rdfs%3Alabel+%3FwdLabel.%0D%0A%09%09FILTER%28LANG%28%3FwdLabel%29+%3D+%22sv%22%29.%0D%0A%09%7D%0D%0A+++++++OPTIONAL+%7B+%0D%0A+++++++++++++++%3Fitem+wdt%3AP131+%3FWDAdmin.%0D%0A+++++++++++++++%3FWDAdmin+wdt%3AP31+wd%3AQ193556.%0D%0A%09%09%3FWDAdmin+rdfs%3Alabel+%3FwdAdminLabel.%0D%0A%09%09FILTER%28LANG%28%3FwdAdminLabel%29+%3D+%22sv%22%29.%0D%0A%09%7D%0D%0A%7D%0D%0AFILTER+%28%28+STRSTARTS%28str%28%3FTORA_wduri%29%2C+%22https%3A%2F%2Fwww.wikidata.org%2Fwiki%2F%22%29%29+%26%26+%3FWDsame+%3D+%22N%22+%29%0D%0A%7D+order+by++%3FTORA_label) - finding differences

**Comment by salgo60** [comment]
Another thing with dates is Calendar format. We have this problem with the data from Nobelprize.org that they mix [Gregorian dates with Julian Dates](https://en.wikipedia.org/wiki/Old_Style_and_New_Style_dates)... see [link](https://www.wikidata.org/wiki/User:Salgo60/ListeriaNobelData3)

**Comment by MansMeg** [comment]
Based on the date precision of wikipedia, I suggest we go with 2, since that is how it is solved in wikidata. Ie yyyy-00-00.

**Comment by MansMeg** [comment]
After our discoussion @rbbby , I think it is important for us to solve this issue better. Now we essentially add data that is not correct when we say that 1990 = 1990-01-01. Ill add this one ass a suggestion for 0.4.4.
