### ISSUE TITLE
Improving note/seg quality

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#140]
Currently, there seem to be some problems where note and segs are either incorrectly classified and where there are segmentation errors in the note/segs. It is also not fully clear what the definition is of note seg in the ParlaClarin format. To improve this quality we need to.

- [ ] Identify the definition of not seg (most likely this will be paragraphs). if a clear definition is missing in the parlaClarin schema, we should define it as a paragraph in a column of text (hence paragraphs split between column/pages will be two paragraphs).
- [ ] Train models to predict note/seg and maybe also identify segmentation errors (?).
- [ ] Map split segmentations between pages/columns for easy mapping between pages/columns

@ninpnin Do you think this is a good approach?

**Comment by ninpnin** [comment]
Duplicate of #189
