### ISSUE TITLE
Create a helper file to simplify manual quality control

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#141]
With the new meta-data-structure it has become more difficult for manual control of the quality. To solve this we should setup a function to generate a file that can be used for quality control (in the input directory). 

The helper file should contain name, chamber protocol, year, and party, sorted by year and lastname.

@Stubbendorff and @fredrik1984 Does this sound right to you?

**Comment by BobBorges** [comment]
closing as complete:
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/a92e585f-b6ee-4a49-a66a-0a0d74ed6065)

see also: `scripts/search-people.py`
