### ISSUE TITLE
Fix errors in 2006 and 2010

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#144]
We now have two dips in identifications of speakers in 2006 and 2010 compared to version 0.4.0. This is probably due to an error of dates according to @rbbby .

**Comment by MansMeg** [comment]
Did you solve it?

**Comment by rbbby** [comment]
Yes, 0.4.2 is almost finished.

**Comment by MansMeg** [comment]
Wow!

**Comment by MansMeg** [comment]
Can you produce the same quality plot you did before?

**Comment by rbbby** [comment]
Here it is!

![acc-diff-042](https://user-images.githubusercontent.com/78153594/159900933-2b348497-5c2b-4a94-999f-61eeae43bf97.png)

**Comment by MansMeg** [comment]
Nice!
