### ISSUE TITLE
Use digitized dictionary entries of all MP 1867–1993/4 for metadata database

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#147]
We got a digital copy of the biographical entries of all MPs between 1867–1993/94 (OCR searchable PDFs) from the Riksdag Library. These are the dictionaries Två kammarriksdagen 1867–1970 (Norberg et al. 1992 and Enkammarriksdagen 1971–1993/94 (Asker & Norberg 1996). These could be a complement to Statskalendern and Wikidata. The Zip-file can be found here:

https://drive.google.com/drive/folders/1Vk2q7s8Pi4DgZ1_B2xZB9mjF2SfFSOZs

**Comment by MansMeg** [comment]
This is a good idea!

**Comment by salgo60** [comment]
**Maybe we should coordinate** so we do this so we could help each other. I have connected > [1600](https://w.wiki/4uC8) WD persons with the book "Tvåkammar-riksdagen 1867-1970" 

* SPARQL [list](https://w.wiki/4$KU)
   * same but [link API and sv:Wikipedia](https://w.wiki/4$Md) 

as "Tvåkammar-riksdagen 1867-1970" has good information about parties I have also start added that in Wikidata and use "Tvåkammar-riksdagen 1867-1970"  as the source see [timeline/parties](http://minancestry.blogspot.com/2022/03/spa-tidslinje.html)

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/14206509/161156945-f666aecb-57e3-4892-910e-30d8a9ff5aa0.png">

My next step is that I have bought some of the books and will started to add page in book see example [Q5540748#P1343](https://www.wikidata.org/wiki/Q5540748#P1343) he is described in **book 1 page 47** and named **Aastrup i Stockholm**

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/14206509/161157107-2f0c5d1f-25fb-4418-9241-e2fe1c49a6f0.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/14206509/161157361-1f9c6ef6-f671-4690-87d9-dfb616f26a5a.png">

**Comment by fredrik1984** [comment]
Great, that was fast!

**Comment by fredrik1984** [comment]
...and a related question to @salgo60: how easy would you say it is to extract MP info from this source?

**Comment by salgo60** [comment]
@fredrik1984 depends what you want? dont hesitate to call me +46-735152802

I am doing it one by one manually (and add sources for all statements/pictures...) but I feel we could use tools like [Open Refine ](https://libjohn.github.io/openrefine/hands-on-web-scraping.html)

The 1600 I have connected --> you have the API and OCR:ed text and Tvåkammar-riksdagen 1867-1970 is well structured so I guess NER is not rocket science.... plus we have in Wikidata xxx potential Swedish PM:s that are not matched

**Example Aastrup in Stockholm that is connected**
* Wikipedia https://sv.wikipedia.org/wiki/Nils_Aastrup

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/14206509/161208941-7977faf0-6953-46b9-a5ab-27d35832a289.png">

* Wikidata https://www.wikidata.org/wiki/Q5540748

<img width="956" alt="image" src="https://user-images.githubusercontent.com/14206509/161209120-bcc0f6bc-cf3d-4164-8350-826678eae31f.png">

* SPA API -> https://portrattarkiv.se/endpoints/portraits.php?id=sj9PGLAlnmUAAAAAABfEmA

you have in **PortraitBioText** the OCRed text at SPA
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/14206509/161209410-ca30e39c-8202-4cff-999d-6a36d120bf47.png">

* [Notebook](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/Notebook/Sveriges%20Riksdag%20i%20SPA%20-%20Tv%C3%A5kammar-riksdagen%201867.ipynb) me extracting SPA 4353 entries from "Tvåkammar-riksdagen 1867" in SPA
   * [csv file created ](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/Notebook/OpenRefine_Tv%C3%A5kammar-riksdagen%201867-.csv)   

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/14206509/161209674-ea690e06-7a9c-4e81-a5c5-78991a580d0f.png">

<img width="691" alt="image" src="https://user-images.githubusercontent.com/14206509/161211345-0baee5d1-3536-45a5-8f2c-868db629230f.png">


**Issues I see**
* we need persistant identifiers for referencing people in the book.... [SPA](https://portrattarkiv.se/about) is "just 7000" people in a [Facebook group](https://www.facebook.com/groups/592177787549600)

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/14206509/161210166-5705b289-d59e-4299-8dc8-26de605d909e.png">

* SPA is a one man project and it was not created to be Swedish research data --> some pictures are grouped as "Tvåkammar-riksdagen 1867" is wrong classified --> **we need a lot of cleaning**

**"Formalize" your project [Välfärdsstaten analyserad](https://www.westac.se/en/) and Wikidata with some change management workflow?**
* right now I feel you use Wikidata Qnumbers but we have no "official" change management
  * Wikidata is very "loose" but we now have an tool for Mismatches with external sources see [Wikidata:Mismatch_Finder](https://www.wikidata.org/wiki/Wikidata:Mismatch_Finder) maybe that could be how we handle change management?
    * if you are interested I can maybe set up a meeting with the Wikidata [product manager Lydia Pintscher](https://www.linkedin.com/in/lydiapintscher/?originalSubdomain=de) she spoke last month about "[Best practices for reusing Wikidata’s data](https://www.youtube.com/watch?v=HqrEfvRo1iU&t=7s)"

<img width="845" alt="image" src="https://user-images.githubusercontent.com/14206509/161216016-f781d39a-a557-4e84-a9b5-132469fb7f1d.png">

<img width="849" alt="image" src="https://user-images.githubusercontent.com/14206509/161216145-78c6d436-9909-4b1c-b6c0-bfa29d0ba740.png">

<img width="834" alt="image" src="https://user-images.githubusercontent.com/14206509/161216249-66179032-630b-49f6-b5c8-522b6f990965.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/14206509/161216294-0ff7c2e8-5d9b-44be-a563-18a73fc7d40a.png">

<img width="836" alt="image" src="https://user-images.githubusercontent.com/14206509/161216340-6809dd21-f5e7-44d5-acf1-2917b0c57c62.png">

<img width="808" alt="image" src="https://user-images.githubusercontent.com/14206509/161216380-883fc8ad-faac-45f0-8a76-b8c1e49eecb1.png">

<img width="787" alt="image" src="https://user-images.githubusercontent.com/14206509/161216617-0725f9c8-8eb8-4c11-9d58-4048b41a3e59.png">
