### ISSUE TITLE
Persistent identifier for documents

### ISSUE THREAD

**Issue by salgo60** [welfare-state-analytics/riksdagen-corpus#148]
My wish is that we get a persistant identifier so **we can create a [WIkidata property](https://www.wikidata.org/wiki/Wikidata:List_of_properties)** for your project that we can use to reference your data
* documents
* a Swedish MP
* a party you have identified and related data
* maybe also a specific lexeme in a document
* section in your [parla-clarin](https://clarin-eric.github.io/parla-clarin/) formatted [corpus](https://github.com/welfare-state-analytics/riksdagen-corpus)
* ....

Example  how I today link a document at Riksdagen using Riksdagens id for a document with id [DT9C47](https://www.riksdagen.se/sv/dokument-lagar/dokument/protokoll/1932-forsta-kammaren-nr-47_DT9C47) as SPA has scanned the book Tvåkammar riksdagen and has one person per page we also have an identifier to a specific person in the book [sj9PGLAlnmUAAAAAABgcNA](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABgcNA) that we add to WIkidata

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/14206509/161245661-674e5fcf-0129-46ac-b115-39e996254aee.png">

I created today this article [Ivar Wittberg i Filipstad](https://sv.wikipedia.org/wiki/Ivar_Wittberg_i_Filipstad)
* WIkidata [Q111448420](https://www.wikidata.org/wiki/Q111448420?uselang=sv) as [graph](https://w.wiki/4$PS) see also [video how to navigate the graph](https://youtu.be/UGsCjBiQU8M)

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/14206509/161246631-35d17e85-17d5-4259-9882-d3bf1072375f.png">

* [sv:Wikipedia]((https://sv.wikipedia.org/wiki/Ivar_Wittberg_i_Filipstad))
  *  pages [linking this page](https://sv.wikipedia.org/wiki/Special:L%C3%A4nkar_hit/Ivar_Wittberg_i_Filipstad)
* template [Mall:Riksdagensdokument](https://sv.wikipedia.org/wiki/Mall:Riksdagensdokument) I created  in svWikipedia to link documents at Swedish Riksdagen - templates is used to support the [DRY pattern](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) dont repeat yourself

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/14206509/161246184-0c5e828d-96ba-4cd8-8117-7183290b3547.png">

Template used in the article
 >  {{Riksdagensdokument|
 > DT2O514
 > |titel=Motion 1932:514 Andra kammaren
 > |datum=lördagen den 7 maj 1948
 > |citat=Av [[Ivar_Wittberg_i_Filipstad|herr Wittberg]], i anledning av Kungl. Maj:ts proposition, nr 187, med förslag till ecklesiastik boställsordning m. m.}}

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/14206509/161247161-25268433-84b5-4237-98de-e2ef9af11bc9.png">

**Comment by rbbby** [comment]
We are planning to update some parts of the xml schema soon and one thing high up on the priority list is a persistent textblock identifier so references can be made to a specific part of the corpus.

**Comment by ninpnin** [comment]
@rbbby should we regenerate <u> element ID's to be UUID's as well? Or just go with the ones we have currently?

**Comment by MansMeg** [comment]
I think this is a good idea. Although release 0.4.3 first and do this in 0.4.4?

**Comment by ninpnin** [comment]
Continued in #208
