### ISSUE TITLE
Missing dates from party affiliation in wikidata leads to speeches with unknown party affiliation

### ISSUE THREAD

**Issue by TomasSkotare** [welfare-state-analytics/riksdagen-corpus#149]
Essentially, even if we know who was the speaker, the party affiliation is often unknown for (generally) earlier speakers, often 1920s-1930s.

This is largely due to them not having dates associated with the their party affiliation for a given time, and there are multiple options.

One example can be:
https://www.wikidata.org/wiki/Q4820820
with approx. 500 recorded speeches, all with party affiliation set to 'unknown'.

For reference, this plot shows protocols with the most unknown party affiliations from *known* speakers:
![image](https://user-images.githubusercontent.com/8590039/161516665-d16806de-b369-4b9f-9672-9d347a840e43.png)

**Comment by salgo60** [comment]
@TomasSkotare FYI in Wikidata I am updating the [party affiliation](https://www.wikidata.org/wiki/Q4820820?uselang=sv#P102) see https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/38 using the book "Tvåkammar-riksdagen 1867-1970" as a source --> [Q4820820](https://www.wikidata.org/wiki/Q4820820) = [the book vol 2 p 440](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABgcXg)

<img width="640" alt="image" src="https://user-images.githubusercontent.com/14206509/161532939-221e17c6-7c82-440a-9d41-69760418417c.png">


<img width="1037" alt="image" src="https://user-images.githubusercontent.com/14206509/161531660-c21b38f2-c9fb-4d02-8988-bba6ab8aed09.png">

The challenge is
* I am not skilled on Swedish historical parties
* the book "Tvåkammar-riksdagen 1867-1970" is excellent BUT vague --> for e.g. people associated with the communists like [Q4820820](https://www.wikidata.org/wiki/Q4820820) is not easy for me to "translate into Wikidata"

e.g. my "guess" below
1) **k 1922-1933** I am not sure I use [Kommunistiska partiets riksdagsgrupp](https://www.wikidata.org/wiki/Q111285801) / Q111285801 based on source Sveriges riksdag 1924 : porträttalbum - [August Konrad Ferdinand Spångberg (K)](http://runeberg.org/svriks24/0119.html)
2) **sp 1934-1937** [Socialistiska partiet](https://www.wikidata.org/wiki/Q2425638)
3)  **s 1938-1964** I assume [Socialdemokraterna](https://www.wikidata.org/wiki/Q105112) / Q105112

If we could get help with parties and maybe some good translation to Wikidata Q numbers and dates see [WD <-> party status right now](http://minancestry.blogspot.com/2022/03/spa-tidslinje.html)

**Dont hesistate to call me if this will help you +46-735152802**

**Comment by MansMeg** [comment]
I think this is the way to go here. Ie update the from and to dates for these parties. I think we should also setup these political parties and their abbreviations. @salgo60 is this something you have in wikidata right now? I think we have som similar mapping now in the corpus, but @rbbby know more about the details.

**Comment by salgo60** [comment]
No good quality in Wikidata right now on dates etc.. you have some data in the book "Tvåkammar-riksdagen 1867-1970" see page 12 book 1 and also some [Wiki articles ](https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_politiska_partier_i_Sverige#Tv%C3%A5kammarriksdagen_(1867%E2%80%931970))feels have good quality

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/14206509/161539798-fd8fe7af-d6b8-49ad-b7fa-b650e806f6ce.png">

I feel the model should be
* start [inception](https://www.wikidata.org/wiki/Property:P571) Property:P571
* end [dissolved, abolished or demolished date](https://www.wikidata.org/wiki/Property:P576) Property:P576
* [follows](https://www.wikidata.org/wiki/Property:P155) Property:P155
* [followed by](https://www.wikidata.org/wiki/Property:P156) Property:P156
* alias used in the book or in other sources...
   * the book has abbreviations that we should maybe translate to Wikidata Qnumbers... see bibl_uppslag_tvåkammar_1867-1970_Band_2__02.pdf page 427 

<img width="807" alt="image" src="https://user-images.githubusercontent.com/14206509/161542627-8d93dc8f-f0c6-4125-88d2-e759be1c2e6e.png">

<img width="389" alt="image" src="https://user-images.githubusercontent.com/14206509/161542977-c910e33d-ba98-4678-a56b-722048a11844.png">
<img width="361" alt="image" src="https://user-images.githubusercontent.com/14206509/161543176-ab913b75-ec6d-402a-831e-321ffad01531.png">
<img width="404" alt="image" src="https://user-images.githubusercontent.com/14206509/161543001-8994b350-bd33-4ba6-9cf4-42fad639c6c1.png">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/14206509/161543060-f3943531-f738-4a4b-920b-1d41515cf954.png">


**Wikidata example** Frihandelsvänliga centern [Q10499121](https://www.wikidata.org/wiki/Q10499121?uselang=sv) 
* this info is not checked with the book its from the [svwiki article](https://sv.wikipedia.org/wiki/Frihandelsv%C3%A4nliga_centern)

**Comment by MansMeg** [comment]
Hmm. Yes, we would need to formalize this somehow and also, ideally, connect their abbreviations to the parties as well to simplify your work. 

What of this do we have in wiki data as of now? Could we add these party-paths in a structured way in wikidata? We would need to store it in a normalized form in our meta-data. But I guess we all want to get this in structured form?

**Comment by salgo60** [comment]
> What of this do we have in wiki data as of now? 
I guess we can only trust what is sourced from the book "Tvåkammar-riksdagen 1867-1970"

I am right now doing [Wikidata_riksdagen-corpus/issues/38](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/38)
* [X] get the [bookregister txt file cleaned](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt) - 1 row per person = 3811 rows 
* [ ] start connect Wikidata objects to this list/the book
* [ ] add the book as a source with a ref to volume and page

The goal is to have one WD object and one svWikipedia article for every person. Status today is 
* [abt 3900 PMs in the register list of the book](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt) 
* Wikidata has 3347 [folk i första och andra kammaren](https://w.wiki/4$qi) 
*  [1700 riksdagsledamöter](https://w.wiki/4$kX) are connected to the book Tvåkammar-riksdagen 1867-1970 but needs cleaning and add a reference to volume and page in the book

as said a small mess with parties (riksdagsgrupper I guess) etc... needs some QA

**Comment by MansMeg** [comment]
Ok. But if I understand you correctly, the parties in the picture needs to be added as well as you suggest, right?

To us I think the date from and date to from individual mps would be important to add as well to solve this issue. Maybe just go through the mps where we have oroblems and fix them in wd?

**Comment by MansMeg** [comment]
I and @rbbby discussed this briefly. We think this needs to be done to solve your issue @TomasSkotare :
- [ ] Add start date and end date in our party affiliation csv-file
- [ ] Go through persons with multiple parties but without dates, and update them at wikidata 
- [ ] Update our party affiliations from wikidata

Then we should branch out the other issues that Magnus mentions as separate issues here, namely:
- [ ] Storing/adding the party structures to wikidata https://user-images.githubusercontent.com/14206509/161539798-fd8fe7af-d6b8-49ad-b7fa-b650e806f6ce.png + Add the party structure in our corpus as a csv-file
- [ ] Add MPs from the book (as Magnus is now doing)

**Comment by salgo60** [comment]
> To us I think the date from and date to from individual mps would be important to add as well to solve this issue. Maybe just go through the mps where we have oroblems and fix them in wd?

Sounds great the best if you have it also at your place.... as Wikidata is open we get changes that can be vandalization and/or changes done with good intentions but not the same intention other people has ;-)

[video](https://youtu.be/uegHrG-iU2o)
* browser plugin [Entity_Explosion](https://www.wikidata.org/wiki/Wikidata:Entity_Explosion) mentioned in the video --> you can jump between the bookpage in SPA, wikidata, other referencies....

OT if you walkthrough the book "Tvåkammar-riksdagen 1867-1970"... you also has mentioned the number of "motioner" they have written themself... that could be a good quality check that you have annotated those documents... I havnt added that information to Wikidata just updated the wiki articles with that text and some links to Riksdagens documents example 

* wikidata [Q5553680](https://www.wikidata.org/wiki/Q5553680?uselang=sv) 
* wiki article [Olof Anderson](https://sv.wikipedia.org/wiki/Olof_Anderson_i_Hasselbol)
* book [sj9PGLAlnmUAAAAAABgbrw](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABgbrw)

<img width="372" alt="image" src="https://user-images.githubusercontent.com/14206509/161897218-a6d2ea7c-845a-4fed-84d9-4dba63a394ac.png">

**Comment by MansMeg** [comment]
This is a list of the wikidata entries we need to fix regarding start and end date of their party affiliations. I add them here, so also @salgo60 can help (if he wants to):

- [x] Q4952016
- [x] Q5600489
- [x] Q4941925
- [x] Q4955783
- [x] Q5885103
- [x] Q4991027
- [x] Q6206776
- [x] Q6068516
- [x] Q5548875
- [x] Q4959099
- [x] Q5895466
- [ ] Q5913938
- [ ] Q937985
- [ ] Q6178909
- [ ] Q5556026
- [x] Q4931171
- [x] Q3369258
- [ ] Q1976379
- [ ] Q6220743
- [ ] Q3357513
- [ ] Q4953847
- [ ] Q5714600
- [ ] Q4981479
- [ ] Q6255280
- [ ] Q5717497
- [ ] Q5715406
- [ ] Q980319
- [ ] Q6236518
- [ ] Q6250434
- [ ] Q563289
- [ ] Q6045471
- [ ] Q5719585
- [ ] Q98281504
- [ ] Q1368035
- [ ] Q18238811

**Comment by MansMeg** [comment]
@salgo60 : I have now got a green light from the Riksdagen Library to release the book Tvåkammarriksdagen 1867-1970 as CC0. Do you need anything more from me?

**Comment by salgo60** [comment]
@MansMeg excellent then we will have pictures of all Swedish PMs in that book in Wikidata

we need a statement like a webpage that its CC-0 that we can reference..... 

best would be if Riksdagen Library could just have a page telling the book is CC-0 something like page [Riksdagens protokoll.Andra kammaren 1962, B01](https://weburn.kb.se/riks/metadata/33/19569833.html)

<img width="629" alt="image" src="https://user-images.githubusercontent.com/14206509/162085147-81a71616-a1a5-455a-8487-3e271042d9bd.png">

**Comment by salgo60** [comment]
@MansMeg  One vague thought also translate the sources in the book "Tvåkammar-riksdagen 1867-1970" to linked data and connect the source to the description in the book :


1) today in Wikidata we try to have [one object for every Swedish PM](https://w.wiki/52Tr)
2) Now with the book "Tvåkammar-riksdagen 1867-1970" getting more and more important maybe we should have an entry in Wikidata for the book and every article about the person in the book ( as SPA has [sj9PGLAlnmUAAAAAABfRZQ](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfRZQ) for the article "Andersson i Bringåsen" that _describes_ WD person [Q5554719](https://www.wikidata.org/wiki/Q5554719) )
3) having a wikidata item for a part of the book like [Andersson i Bringåsen](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfRZQ) --> we can also **add sources in a more structured way** e.g Andersson i Bringåsen has at the bottom mentioned: 

<img width="346" alt="image" src="https://user-images.githubusercontent.com/14206509/162137277-2d429717-49d7-4345-96ac-93b5a9c971d7.png">


3-1) Skrifter "Tankar om de föreslagna jernbanorna i Norrland" same as Wikidata [Q111516483](https://www.wikidata.org/wiki/Q111516483) someone has scanned it [link](http://www.busvebacken.se/J%C3%A4rnv%C3%A4gsBroschyr)
3-2) Litt: SP = Svenskt Porträtt galleri --> that is [scanned by Project Runeberg](http://runeberg.org/spg/) --> "[Hans Andersson. F. i Kyrkas" page 336](http://runeberg.org/spg/25-2/0336.html)

<img width="605" alt="image" src="https://user-images.githubusercontent.com/14206509/162138028-84228301-7524-4ee5-90cd-31f588c675bd.png">

<img width="715" alt="image" src="https://user-images.githubusercontent.com/14206509/162154024-237dcd7c-d8f6-4e29-8c0b-00d9a16133f4.png">

* graph[ todays WD object](https://w.wiki/52U9)
  * [video me navigate the graph](https://youtu.be/cb0RPb7qBm4)
![image](https://user-images.githubusercontent.com/14206509/162165450-d154d9d9-4c6f-4245-ae2d-e6e41d2ba9a1.png)


'''Nice to have'''
* [ ] as SPA has unique identifiers for every piece about a specific person in the book it would be nice that you in your  project creates persistent identifier for "book parts" in the book "Tvåkammar-riksdagen 1867-1970" . And as said earlier then we can to get approved a Wikidata property for your project (or better for the persistent place you will have when the project is over.... )

**Comment by MansMeg** [comment]
I now start to find incorrect parties in wikidata that would need to be fixed long term by adding the correct parties in the image above. Q5885103 was first a member of lmb that is translated as the moderate party, but this is not correct since the lmb split and some went to the "Högerpartiet" and some to what would be "Centern". 

I guess that a first step would be to add all the parties in the list above in wikidata. Could you do that @salgo60 ?

**Comment by MansMeg** [comment]
I actually think that soon we will be able to use the corpus to deduce this automatically for WD. Although we would need to find a way to do a lot of changes as a bulk then?

**Comment by salgo60** [comment]
@MansMeg bulk changes is no major problem 

We use [Quickstaments](https://www.wikidata.org/wiki/Help:QuickStatements) or [Open Refine](https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine) or API calls 

Yes there are a lot of parties that are not updated regarding to "Tvåkammar-riksdagen 1867-1970"

If you filter the timeline you [select parties like](http://minancestry.blogspot.com/2022/03/spa-tidslinje.html) "Moderaterna" you see a lot of errors

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/14206509/162285757-887f12e2-9174-43cf-b2a7-4cc179c319b4.png">

Example of error is [Q5983870](https://www.wikidata.org/wiki/Q5983870) Olof Melin  that I am fixing now see [history](https://www.wikidata.org/w/index.php?title=Q5983870&action=history)

<img width="671" alt="image" src="https://user-images.githubusercontent.com/14206509/162285360-8a21682d-c162-4b55-8bc4-2e56caab3b73.png">

Dont hesitate to call me 0735152802 we have one issue how to modell name changes e.g. Högerpartiet --> Moderaterna is that the same object or just a name change? I have started to add them as 2 objects as we get people obset in svWikipedia if they see the wrong name for a person ;-)

* Högerpartiet [Q111033682](https://www.wikidata.org/wiki/Q111033682?uselang=sv)
* Moderaterna [Q110843](https://www.wikidata.org/wiki/Q110843?uselang=sv)

For Swedish Church parishes we have implemented a maybe better solution see object Gävle parish [Q10512441](https://www.wikidata.org/wiki/Q10512441?uselang=sv#P2561)

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/14206509/162286715-1a020c0e-1334-4a8c-8e65-79f97f2c41b4.png">

**Comment by MansMeg** [comment]
I think we need to add those parties that exist here:
https://user-images.githubusercontent.com/14206509/161539798-fd8fe7af-d6b8-49ad-b7fa-b650e806f6ce.png

I think Högerpartiet and Moderaterna is simply the same party but with different names. Although "Lantmanna och borgarepartiet" split into Högerpartiet, Jordbrukarnas fria grupp and Bondeförbundet. So we need to keep that as a separate party since it split? Im not sure how to add this in the best way. Well. Now time to sleep.

**Comment by MansMeg** [comment]
Ah! yes. As you have done with olof Melin seems very reasonable! There he has been added to the many different parties.

**Comment by salgo60** [comment]
@MansMeg  The challenge with Wikidata is that we are [12000 people who should agree](https://stats.wikimedia.org/#/wikidata.org) and then some [1000 people on sv:WIkipedia](https://stats.wikimedia.org/#/sv.wikipedia.org) and maybe some 50 000 on WIkipedias [on > 200 different languages ](https://stats.wikimedia.org/#/all-projects) :smiley: 

My feeling is that one person has added Moderaterna for every rightwing party people....
* I guess that is **not good enough for you**
* That is not either my goal with Wikidata but does **everyone agree?**  

My feeling is that Wikidata 
* is excellent for gathering people like all Swedish PM:s
* when we have an excellent source like "Tvåkammar-riksdagen 1867-1970" then we can maybe agree about parties...
  * even better if we also have your data and can easy check our data with your data...  example how I check [Nobelprize winners](https://github.com/salgo60/open-data-examples/blob/master/Nobel%20API_2_1.ipynb)
* today I had a meeting with a new project [bildhistoria](https://blogg.bildhistoria.se/) and they would like to have events in a persons life same as Wikidata ... a little bit difficult and the future will tell if it works....

**Comment by MansMeg** [comment]
No, long-term it is not good enough for us. Although, right now it is not super-important.

It is hard for me to judge if everyone would agree, but formally it doesn't even there exist a "Högerpartiet" in the 1920ies. So the party back then was the "lantmanna and borgarepartiet". So I guess it is incorrect to label them as "Moderaterna" during the term in office, although some persons were probably then later members of Högerpartiet/moderaterna.

**Comment by salgo60** [comment]
Yes that is the logic but maybe the person doing this just positioned them to the right ;-) 

We have the same problem with "Liberalerna"

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/14206509/162324689-16943162-eb00-4c29-b7f2-e40df831e3d1.png">

Karl Magnus Lindh WD  [Q5956462](https://www.wikidata.org/wiki/Q5956462?uselang=sv#P102) is **lib s** in our bible
<img width="714" alt="image" src="https://user-images.githubusercontent.com/14206509/162324844-039e480a-0971-4ff1-9bde-ca41e81d87d4.png">

**Comment by MansMeg** [comment]
Yes indeed. As I said, I think at least our corpus will need to distinguish between these parties and we will base this on the Tvåkammarriksdagen book. But maybe wait with updating wikidata with this info en masse then? Or what do you think?

**Comment by salgo60** [comment]
My intention is to slowly updating the WD objects and use the Tvåkammarriksdagen book as the bible.... we have > 3000 Swedish PM people but miss pictures, source Tvåkammarriksdagen book....

**My todo list**
* updates [the WD objects](https://www.wikidata.org/wiki/Special:Contributions/Salgo60)
* add pictures of the Swedish PM people from SPA - [commons Special:ListFiles/Salgo60](https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/Salgo60&ilshowall=1)
* add links to "motioner" written using a Wiki template I have created [Mall Riksdagensdokument](https://sv.wikipedia.org/wiki/Kategori:Riksdagensdokument)
* updates the [svWiki articles like adding  Wikidata driven templates](https://sv.wikipedia.org/wiki/Special:Bidrag/Salgo60) (its a little bit controversial so some have "manual "templates)

**Comment by salgo60** [comment]
@MansMeg  **"Missing dates"** how will you translate when we lack dates for one party? 
* WD [Q6218962](https://www.wikidata.org/wiki/Q6218962?uselang=sv#P102)
* [SPA](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfsTQ)

<img width="744" alt="image" src="https://user-images.githubusercontent.com/14206509/162604454-ac2e67e6-f023-4be4-b331-3ab0eb80f1b6.png">

WD <-> Tvåkammarriksdagen
OT I have slowly started match WD and the [book see file](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/WD%20Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt) --> [salgo60/Wikidata_riksdagen-corpus/issues/38](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/38) 

* maybe you should start have the source connected to a fact if it is "**Wikidata quality**" or "**Tvåkammarriksdagen quality**"

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/14206509/162609635-ee9be9c4-f1d2-4bee-8171-058f386b5917.png">

**Comment by MansMeg** [comment]
I find this to be difficult. I would just add the dates we know. Later on I think we will be avle to deduce these dates from the protocols. We are also obly interested of the party affiliation while in the parliament.

Is there a rutine in wd how to handle say a person that first is mp for one party, then out of parliament and then enter for a new party? We dont know the exakt switch date there?

**Comment by MansMeg** [comment]
Also, for us it would be super helpful the more old mps that would be added since this will help us identify speakers in the protocols.

**Comment by salgo60** [comment]
> Also, for us it would be super helpful the more old mps that would be added since this will help us identify speakers in the protocols.

* [] I am walking through the list of all people in the book "Tvåkammar-riksdagen 1867-1970" [link](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/WD%20Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt) -->  we will have 3815 Swedish MPs in Wikidata from the book
  * also in the book it tells if a father was part of "ståndsriksdagen" that is also added...
  
  > Is there a routine in wd how to handle say a person that first is mp for one party, then out of parliament and then enter for a new party? We dont know the exakt switch date there?

* My understanding is that the book "Tvåkammar-riksdagen 1867-1970" when dates are used it is when the person was in the parlament
* one WD issue is if a person is not connected to a part like "Amineh Kakakabevh" wd [Q3675519](https://www.wikidata.org/wiki/Q3675519)
   * the old way in WD is set "no value"  this pattern is used in Sweden and in other countries
   
<img width="973" alt="image" src="https://user-images.githubusercontent.com/14206509/162639025-df07a853-ade1-426f-aa19-bc9a3807423d.png">

**Lesson learned**  working with the book  "Tvåkammar-riksdagen 1867-1970" is that there are different types of "vilde"

* [Q111478524](https://www.wikidata.org/wiki/Q111478524) "frisinad vilde" --> "Theodor Zetterstrand" [Q6252260#P102](https://www.wikidata.org/wiki/Q6252260#P102)
* [Q111108382](https://www.wikidata.org/wiki/Q111108382) "vänstervilde"
<img width="543" alt="image" src="https://user-images.githubusercontent.com/14206509/162639145-d91160f3-6eb9-4f66-8331-82d115910e49.png">

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/14206509/162639435-7b1d2d77-fae7-492c-b1c1-db1c66cb05b3.png">


* [Q111104528](https://www.wikidata.org/wiki/Q111104528) "högervilde" --> [what linkshere](https://www.wikidata.org/wiki/Special:WhatLinksHere/Q111104528)
<img width="504" alt="image" src="https://user-images.githubusercontent.com/14206509/162639348-4534cab8-8c57-4b68-b2de-3b480edf854b.png">

**Comment by fredrik1984** [comment]
Thanks for info @salgo60! I am currently writing the revised research infrastructure application to Riksbankens Jubileumsfond. Is it correct that there were 3815 ordinary MPs in the Bichamber Rikdag 1867–1970? And do you have the a similar figure for all MPs in the Unicameral Riksdag 1970– ? Would be good to add that information in the application!

**Comment by salgo60** [comment]
@fredrik1984
> for all MPs in the Unicameral Riksdag 1970– 

I guess you can ask Riksdagens API but its a moving target :rocket:

* [the list of in charge 349](https://github.com/salgo60/open-data-examples/blob/master/Riksdagens%20ledam%C3%B6ter%20status2.ipynb)
* the list what Riksdagen have [notebook](https://github.com/salgo60/open-data-examples/blob/master/Riksdagens%20ledam%C3%B6ter.ipynb) --> 2038
   * [json](http://data.riksdagen.se/personlista/?rdlstatus=samtliga&utformat=json&termlista=) (problem is that not everyone is a politician in this API its a small mess) 
* Wikidata people connected to [Q10655178](https://www.wikidata.org/wiki/Q10655178) "ledamot av Sveriges riksdag" SPARQL [count 2302,](https://w.wiki/53Hj) [list](https://w.wiki/53Hh)
  * project @Ainali twitter [@Jan_Ainali](https://twitter.com/Jan_Ainali) has been part of [Wikidata:WikiProject_every_politician/Sweden](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Sweden)

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/14206509/162696015-367aa6e6-ab24-42b2-a856-0d23bda6c939.png">

* OT a repository where a Wikidata user @tmtmtm is trying to get Wikidata updated [every-politician-scrapers](https://github.com/every-politician-scrapers) / [sweden](https://github.com/every-politician-scrapers/sweden-riksdag-api-current) / [change history](https://github.com/every-politician-scrapers/sweden-riksdag-api-current/commits/main)

Also [asks Jan ](https://twitter.com/salgo60/status/1513430323358535689?s=20&t=2NHCno5Puydl8M9WYMXXfQ)
<img width="723" alt="image" src="https://user-images.githubusercontent.com/14206509/162693928-7e27331e-6fb7-465a-bcfb-5eec2f26baa7.png">

**Comment by salgo60** [comment]
@fredrik1984 tips är att fundera över [Wikibase](https://wikiba.se/) som kommer i en cloud version [Wikibase.cloud](https://www.wikibase.cloud/)

Dennis Priskorn @dpriskorn en kille som bor i Sundsvall jobbar med Internetarchive och Wikibase om jag fattar rätt så läser dom Wikidata change strömmen ([APIRecent_changes_stream](https://www.mediawiki.org/wiki/API:Recent_changes_stream)) för att hitta saker.... och sedan har dom satt upp en egen wikibase ex. repository [internetarchive/wcdimportbot](https://github.com/internetarchive/wcdimportbot)

The prototype wikibase installation https://wikipediacitations.wiki.opencura.com

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/14206509/162703349-95dfa157-e483-4de3-b2b1-d833e9deb1a1.png">

Feels like an approach also for research data

**Comment by MansMeg** [comment]
> My understanding is that the book "Tvåkammar-riksdagen 1867-1970" when dates are used it is when the person was in the parlament

Thats sounds like good principle for us to use as well, in the long run since that is what we actually know from the protocols. 

> one WD issue is if a person is not connected to a part like "Amineh Kakakabevh" wd [Q3675519](https://www.wikidata.org/wiki/Q3675519)
> the old way in WD is set "no value" this pattern is used in Sweden and in other countries

I think WD should at least add one "party" that is "independent" connected to the wiki page:
https://sv.wikipedia.org/wiki/Partil%C3%B6s

Yes. That is something we need to handle. This also connects to the previous discussion in that historically we have had different types of independents ("vildar") in the parliament. I'll connect @Stubbendorff and @fredrik1984  to this discussion. @Stubbendorff and @fredrik1984  what do you think would be the best solution to this problem? Add different types of independents historically? Or just call them all independents? I think the most correct would be to call them all independent.

Although, members of the government (ministers) without political party should have another party since they are consider "opolitiska". What do you all think?

**Comment by fredrik1984** [comment]
Regarding "vildar", maybe a start would be to annotate them all as independent (or something adequate to "vilde"). Later on, it would make sense to also tag what kind of vilde they were, that is what historical name was used. But I guess there would still be a connection to which different party identities an MP had, right?

**Comment by dpriskorn** [comment]
> @fredrik1984 tips är att fundera över [Wikibase](https://wikiba.se/) som kommer i en cloud version [Wikibase.cloud](https://www.wikibase.cloud/)
> 
> Dennis Priskorn @dpriskorn en kille som bor i Sundsvall jobbar med Internetarchive och Wikibase om jag fattar rätt så läser dom Wikidata change strömmen ([APIRecent_changes_stream](https://www.mediawiki.org/wiki/API:Recent_changes_stream)) för att hitta saker.... och sedan har dom satt upp en egen wikibase ex. repository [internetarchive/wcdimportbot](https://github.com/internetarchive/wcdimportbot)

I dagsläget kör IA en Wikibase på Wbstack som sen kommer migreras till Wikibase.cloud när den tjänsten har lanserats. 

https://wikicitations.wiki.opencura.com/wiki/Main_Page är den Wikibase vi jobbar mot just nu. Där syns egenskaperna modelleringen och ett par testobjekt som tex https://wikicitations.wiki.opencura.com/wiki/Item:Q93

**Comment by salgo60** [comment]
**How it will look in WIkipedia Wikidata** and hopefully we get a WD property for your data too in the future

*[ svWikipedia a reference ](https://sv.wikipedia.org/wiki/Carl_Axel_Trolle_(1810%E2%80%931879))to the scanned article of the book in SPA and a volume page ref and the name used in the index -  **vol. 3, s. 283, omnämnd som: Trolle i Klågerup, Carl A**

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/14206509/162711274-4d2074d3-e979-4ccb-9b24-42eaa825cf7e.png">


* Wikidata e.g. [Q6215599](https://www.wikidata.org/wiki/Q6215599?uselang=sv#P569)

<img width="981" alt="image" src="https://user-images.githubusercontent.com/14206509/162710218-ac451859-3dc6-4549-8ad6-eeaddfba4599.png">

same [english](https://www.wikidata.org/wiki/Q6215599?uselang=en#P569)

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/14206509/162710455-9608efdb-f05f-457a-9884-bc0a20806729.png">

* [list of register "Tvåkammar-riksdagen 1867-1970" ](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/WD%20Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt)connected to Wikidata **[work in progress](https://github.com/salgo60/Wikidata_riksdagen-corpus/commits/main/data/WD%20Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt)**

<img width="602" alt="image" src="https://user-images.githubusercontent.com/14206509/162710668-a61a5344-4f21-45f5-8e26-5b968f2765fe.png">

**Comment by fredrik1984** [comment]
> 

Thank you for the info @salgo60!

**Comment by salgo60** [comment]
OT @fredrik1984 @MansMeg  @rbbby @dpriskorn 

Wiki Workshop 2022 April 25, 2022. **target group researchers** maybe something for you looks some ML related thing...

* [accepted papers](https://wikiworkshop.org/2022/#papers)
* [registration](https://t.co/LUuxoox0aA)

**Comment by fredrik1984** [comment]
Thank you for the info! Unfortunately, I might have difficulties to attend that day.

Fredrik Norén
PhD, Senior research assistant
Humlab
Umeå University
SE-901 87 Umeå, Sweden
+46 (0)73 995 10 15

umu.se/personal/fredrik-noren<http://umu.se/personal/fredrik-noren>
westac.se/en<http://westac.se/en>
inidun.github.io<http://inidun.github.io>
modernatider1936.se/en<http://modernatider1936.se/en>

[cid:B2E5D2EF-2346-49EB-B8BE-F2B23E18D6EF]

By sending an email to Umeå University, the University will need to process your personal data. For more information, please read: https://www.umu.se/en/about-the-website/legal-information/processing-of-personal-data

11 apr. 2022 kl. 20:22 skrev Magnus Sälgö ***@***.******@***.***>>:



OT @fredrik1984<https://github.com/fredrik1984> @MansMeg<https://github.com/MansMeg> @rbbby<https://github.com/rbbby> @dpriskorn<https://github.com/dpriskorn>

Wiki Workshop 2022 April 25, 2022. target group researchers maybe something for you looks some ML related thing...

  *   accepted papers<https://wikiworkshop.org/2022/#papers>
  *   registration<https://t.co/LUuxoox0aA>

**Comment by salgo60** [comment]
> > @fredrik1984 tips är att fundera över [Wikibase](https://wikiba.se/) som kommer i en cloud version [Wikibase.cloud](https://www.wikibase.cloud/)
> > Dennis Priskorn @dpriskorn en kille som bor i Sundsvall jobbar med Internetarchive och Wikibase om jag fattar rätt så läser dom Wikidata change strömmen ([APIRecent_changes_stream](https://www.mediawiki.org/wiki/API:Recent_changes_stream)) för att hitta saker.... och sedan har dom satt upp en egen wikibase ex. repository [internetarchive/wcdimportbot](https://github.com/internetarchive/wcdimportbot)
> 
> I dagsläget kör IA en Wikibase på Wbstack som sen kommer migreras till Wikibase.cloud när den tjänsten har lanserats.
> 
> https://wikicitations.wiki.opencura.com/wiki/Main_Page är den Wikibase vi jobbar mot just nu. Där syns egenskaperna modelleringen och ett par testobjekt som tex https://wikicitations.wiki.opencura.com/wiki/Item:Q93

Thanks @dpriskorn I feel this event driven approach reading the [event stream of Wikipedia](https://www.mediawiki.org/wiki/API:Recent_changes_stream) is what we need implemented in digital humaniora.... as a background with international money transactions I feel archives, museums, research plattforms feels more SILOS than trying to be part in a echosystem... this feels like one way forward

* [mediawiki Recent_changes_stream API](https://www.mediawiki.org/wiki/API:Recent_changes_stream) 
* [vision of a Wikibase echosystem ](https://www.youtube.com/watch?v=Y8iBElN6HTA) by Lydia --> we can also use SPARQL federation
  * interesting design approach with Wikidata/Wikibase listen [18 min](https://youtu.be/Y8iBElN6HTA?t=1100) that we **support conflicting data** and that is not just one thruth 
     * link [wd Q865](https://www.wikidata.org/wiki/Q865?uselang=sv) Taiwan she speaks about
  * also listen to the vision of the architect behind wikidata [Denny Vrandečić](https://scholia.toolforge.org/author/Q18618629) about his vision of sources [link](https://youtu.be/VdAc0JReVSw?t=2450)

<img width="658" alt="image" src="https://user-images.githubusercontent.com/14206509/162916682-1c925b88-cdd2-4b77-841a-426cfeb62273.png">

as said earlier that is what google has done for years see [tweet from 2018](https://twitter.com/salgo60/status/1039846313888833536)

<img width="638" alt="image" src="https://user-images.githubusercontent.com/14206509/162917415-ccbc4e2d-42bf-4dbe-91a1-293225f6e0d3.png">

**Comment by MansMeg** [comment]
Ok. Lets close this issue right now. For now it is sufficient to add the party dates in the party_affiliation csv file. Then @TomasSkotare can handle multiple parties.
