### ISSUE TITLE
Dead or unborn (<15) man talking

### ISSUE THREAD

**Issue by TomasSkotare** [welfare-state-analytics/riksdagen-corpus#158]
Person with ID Q5555684, Olof Andersson, 1839-03-08 -> 1912-12-29

General cause seems to be the same surname, e.g.:
          <note n="684f68b2" type="speaker">
            Herr ANDERSSON i Lycksele (s):
          </note>
          <u who="Q5555684" xml:id="i-ba712dfc66326d5e-19" n="71621342">
(From https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/corpus/protocols/197576/prot-197576--45.xml )

Protocols where the speaker is misattributed (as of 0.4.1):
['prot-1971--100', 'prot-1971--102', 'prot-1971--103',
       'prot-1971--114', 'prot-1971--128', 'prot-1971--56',
       'prot-1971--57', 'prot-1971--67', 'prot-1971--68', 'prot-1971--85',
       'prot-1972--117', 'prot-1972--123', 'prot-1972--126',
       'prot-1972--145', 'prot-1972--147', 'prot-1972--17',
       'prot-1972--33', 'prot-1972--41', 'prot-1972--52', 'prot-1972--56',
       'prot-1972--57', 'prot-1972--60', 'prot-1972--71', 'prot-1972--79',
       'prot-1972--83', 'prot-1973--141', 'prot-1973--37',
       'prot-1973--69', 'prot-1973--78', 'prot-1973--87', 'prot-1973--90',
       'prot-1973--91', 'prot-1974--122', 'prot-1974--126',
       'prot-1974--133', 'prot-1974--137', 'prot-1974--140',
       'prot-1974--145', 'prot-1974--16', 'prot-1974--27',
       'prot-1974--34', 'prot-1974--40', 'prot-1974--60', 'prot-1974--87',
       'prot-1974--88', 'prot-1974--89', 'prot-1975--36', 'prot-1975--37',
       'prot-1975--47', 'prot-1975--63', 'prot-1975--67', 'prot-1975--89',
       'prot-197576--16', 'prot-197576--29', 'prot-197576--31',
       'prot-197576--35', 'prot-197576--44', 'prot-197576--45',
       'prot-197576--46']

**Comment by MansMeg** [comment]
I think we should solve this by also adding a unit test for long-term quality control:
- [x] Add a unit test that an MP is not in a protocol after the date of death? Ideally we check that MPs are only in the protocols when they are actually a part of the parliament as a member fo parliament.
- [x] Fix those errors we find through the unit tests.

@ninpnin and @rbbby , any thoughts?

**Comment by rbbby** [comment]
Unit test has been added
