### ISSUE TITLE
How do I curate if a segment is not part of a speech?

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#16]
I would like to manually curate that this:

$u$seg
$u$seg[[1]]
[1] "\n              (Applåder)\n            "

attr(,"id")
[1] "i-3c7a53a61a573195-50"

is not part of a speech, but rather noise in the chamber?

Maybe add this as an example in the submit correction documentation?

**Comment by MansMeg** [comment]
We can use kinesic tag or note.

**Comment by ninpnin** [comment]
Resolved.
