### ISSUE TITLE
Create unit test for mappings

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#161]
@rbbby identified that we might have introduced a bug in the mapping algorithm. We should have a unit test that checks that the numbers of unknowns per protocols does not increase.

**Comment by MansMeg** [comment]
- None of the protocols should decrease by 50%
-  None of the protocols should have only unknowns
- None years should go down 5% or more

**Comment by rbbby** [comment]
Pushing this to 0.4.5 as rebuilding the wikidata api took a lot of debugging and this issue probably should be its own test (the other test related issues only required updating existing tests)

**Comment by BobBorges** [comment]
closed as moot after #319
