### ISSUE TITLE
Create structure for storing information on manually curated parts of the corpus

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#162]
Yesterday I had a discussion with a fiend of mine that is a developer at Ericson regarding how to store quality information (i.e. stuff that has been manually curated) in the corpus. He had one principle I think are reasonable.

> Avoid getting too much into the XML schema and store. 

Very few persons would want the exact quality level of different parts of the corpus (except us) and it would clog the data.

Hence, as we do with different tables for different metadata, he suggested that we would just store this information in a separate csv file. That would point into the minutes using textblock ids and also the actual text. This would most likely be easy to generate for all our annotated data and would be simple to check.

A simple example would be a csv, say called manually curated, with something like this:
`protocol_id,textsegment_id,git_hash,xml_type,value,quality_level,assessed_by
1982/83:212,j2d0j23dj023ed,speaker_id,Q182091,"manually_assessed","@MansMeg"
`

where:

protocol_id: protocol
textsegment_id: the textblock ids to point to
git_hash: the git has of the data that was assessed/curated
xml_type: what part of the xml has been manually assessed (e.g. the person id connection above). Could also be the "content" of the text block or more or less any any attribute.
value: the value that was manually assigned
quality_level: "manually_assessed"
assesed_by: who made the assessment (volontary)

Something like this would be a rough sketch.

**Comment by MansMeg** [comment]
We had a discussion during the sprint meeting and @ninpnin will take a first pass on this and come up with a suggestion on how to store this until the next curation meeting.

**Comment by ninpnin** [comment]
#178 I would go with JSON. It allows for some flexibility which comes in handy as different curations change different parts of the data.

**Comment by ninpnin** [comment]
Example file from the pull request:

```json
[
    {
        "protocol_id": "prot-1958-fk--22",
        "element_id": "sdhjds833ehj334",
        "quality_level": "manual",
        "tag": "note",
        "datetime": "2022-02-30",
        "text": "Herr Korhonen:",
        "git_hash": "ewkh3223jsdnd9djwenjew",
        "attributes": {
            "type": "speaker"
        },
        "assessed_by": "@MansMeg"
    },
    {
        "protocol_id": "prot-2022--103",
        "element_id": "nendsds8dssdyds",
        "quality_level": "manual",
        "tag": "seg",
        "datetime": "2022-02-30",
        "text": "Jasså.",
        "attributes": {
            "who": "Q182091"
        },
        "git_hash": "ejhjwds32832jhdsjhds",
        "assessed_by": "@ninpnin"
    }
]
```

**Comment by MansMeg** [comment]
The next step is to:
- [ ] 1) Write down principles for how to store curation as a "quality variable" in JSON. 
- [ ] 2) Test to implement recently annotated data using this format in the corpus

**Comment by MansMeg** [comment]
I guess this would need some work by both @ninpnin and @rbbby. What do you think? How do we fix this in the next two weeks?

**Comment by ninpnin** [comment]
I wrote a schema to check these against:

```python
import jsonschema

curation_schema = {
    "type": "object",
    "properties": {
        "protocol_id": {"type": "string"},
        "element_id": {"type": "string"},
        "quality_level": {"type": "string", "enum": ["automatic", "manual"]},
        "tag": {"type": "string", "enum": ["note", "seg", "pb"]},
        "year": {"type": "integer"},
        "month": {"type": "integer"},
        "day": {"type": "integer"},
        "text": {"type": "string"},
        "git_hash": {"type": "string"},
        "assessed_by": {"type": "string"},
    },
    "required": [ "protocol_id", "element_id", "text", "git_hash", "assessed_by"]
}

def validateJson(data):
    jsonschema.validate(instance=data, schema=curation_schema)
```

**Comment by MansMeg** [comment]
Alright! Can you do the two tasks above? Just write down the principles used and, with the help of @rbbby figure out how to store our data like this?

**Comment by ninpnin** [comment]
I can use some of the earlier annotation data that's available to me. @rbbby Do you know if we have the newer curation data somewhere so that it could be added?

**Comment by ninpnin** [comment]
I converted the newest annotations into this format and checked it against the new schema #192
