### ISSUE TITLE
Most common unknowns summary

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#163]
I have gone through the list of most common unknowns for version 0.4.2 and summarised the reasons for the persons not being matched in the corpus. Other than this we had bugs with names containing hyphens and ministers (these are now resolved). 

Missing during some time period:
- [x] man, nordstrandh: seems to be Q6016028 missing in the 60s
- [x] odell: seems to be mats Q571725 missing in wikidata as an mp around 90-94
- [ ] man, einar persson: Q6042789 seems to have been active up until 1967 (only til 1950 in wikidata)
- [ ] désirée pethrus engström: Q4972645 has missing position as mp around 2003-2006

Missing name "i riksdagen":
- [x] man, hagberg, luleå: likely Q442028
- [x] man, törnqvist, karlskrona: likely Q6218297
- [x] man, jansson, falun: likely Q5879850
- [x] man, larsson, luttra: likely Q5619070
- [x] man, svensson, grönvik: likely Q6198588
- [ ] man, hamrin, karlmar: likely Q5787427
- [x] man, Larsson, borrby: likely Q5937280
- [ ] man, Hamlin, jönköping: likely Q5787447

Name change:
- [ ] sofia jonsson: Q4960997 has changed name to Larsen, old name is not in wd
- [ ] rigmor ahlstedt: Q4980351 changed name to Stenmark, old name is not in wd
- [ ] margareta sandgren: Q4972552 changed name to Persson, old name is not in wd

OCR Errors:
- [x] margö ingvardsson: Q4955783, actual name is Margó, OCR error often results in Margö
- [x] man, hzeggblom: danish ä, "ae" --> ze
- [x] man, regneéll: An extra "E" is often added by OCR engine
- [x] man, höbinette: should be hübinette

Segmentation Errors:
- [ ] helena hillar rosen-qvist (newer protocols has problems with long intros getting split, this happens for long names)

**Comment by BobBorges** [comment]
> man, einar persson: Q6042789 seems to have been active up until 1967 (only til 1950 in wikidata)

still to 1950, but (band 5)
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/d10a6ef3-3292-4052-ad4f-12c241f60fa6)

**Comment by BobBorges** [comment]
> désirée pethrus engström: Q4972645 has missing position as mp around 2003-2006

still missing that term. not in bio books, but appears in protocols in that time range

**Comment by BobBorges** [comment]
>  man, hamrin, karlmar: likely Q5787427

is not in our metadata at all -- lacks role property on wikidata

**Comment by BobBorges** [comment]
names changed still missing from wikidata -- people not in bio books

**Comment by BobBorges** [comment]
OCR errors persist in protocols, but seem to be mitigated by fuzzy matching so I'm ticking the boxes.

**Comment by BobBorges** [comment]
> helena hillar rosen-qvist (newer protocols has problems with long intros getting split, this happens for long names)

still unmatched

**Comment by monirbounadi** [comment]
Re: "Name change:": I've fixed this. Have "Missing during some time period:" and "Segmentation Errors:" been fixed? If so, this issue can be closed.

**Comment by fredrik1984** [comment]
#323 #202 #346
