### ISSUE TITLE
Rebuild our Wikidata codebase

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#165]
Our infrastructure for pulling new data from Wikidata is a mess (difficult to work, build upon, and subject to breaking depending on certain updates in Wikidata). Fixing things like #133 has been done for a single file but we would like to do this for all of them and also to add functionality to update single individuals. I think we should put a day or two into rewriting this code.

**Comment by MansMeg** [comment]
Add this as functionality in the pyriksdagen library
Lets do a demo of the code base next meeting
