### ISSUE TITLE
Unit test to check that all paragraphs has ids

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#167]

**Comment by rbbby** [comment]
Pushing this to 0.4.5 as rebuilding the wikidata api took a lot of debugging and this issue probably should be its own test (the other test related issues only required updating existing tests).
Also this functionality already exist in the corpus, we just need to refactor it into a test.

**Comment by BobBorges** [comment]
Paragraphs here means note u and seg -- anything else?

**Comment by MansMeg** [comment]
Im not sure. All the text in the corpus needs to have an uuid so it can be referenced. Do you have the text in anything else than note and seg?

**Comment by BobBorges** [comment]
These seem to be the tags with text and IDs. There are also div and pb elements -- no text and currently have no IDs.

**Comment by MansMeg** [comment]
But those doesnt contain text that actually exist in the text, right? Its just metadata tags?

**Comment by ninpnin** [comment]
I think we should test that
- All elements in all ```<div>``` elements that contain text have an ID

Then, if we add new element types besides ```<u> <seg>``` and ```<note>```, we remember to add IDs for them as well.

Moreover, this could be integrated into the 'all IDs are unique' test.

**Comment by BobBorges** [comment]
will add this all, hopefully today

**Comment by MansMeg** [comment]
Great! Looking forward to a PR!

**Comment by BobBorges** [comment]
@ninpnin no u tags have text -- will check  the three canonical tags and any other tags that contain text.

**Comment by BobBorges** [comment]
Open PR #363
