### ISSUE TITLE
map back to source data / update source data --> corpus pipeline

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#179]
### Problem

I am trying to map the corpus back to the original alto files so we can make use of KB:s annotation tool, images and metadata not stored in the corpus for building classifiers. Doing so has proven to be difficult as the corpus contains both incorrect links to the API and (both reasonable and incorrect) text processing. I have not investigated the API linking problem too much but it is systematically wrong for almost all pages in the protocol I have checked, and I suspect the error to be inconsistent without a good solution.

### Example 1

Original data:
https://betalab.kb.se/prot-1972--146/prot_1972__146-122.xml
1. \<String ID="string_397" HPOS="825" VPOS="1297" WIDTH="85" HEIGHT="21" WC="0.92" CONTENT="närings-"/>\<SP WIDTH="21" VPOS="1297" HPOS="910"/>
2. \<String ID="string_398" HPOS="931" VPOS="1297" WIDTH="38" HEIGHT="17" WC="0.96" CONTENT="och"/>

Joining the whole textblock using minimal standard processing results in the string:

> Vi tror på att den fortsatta utvecklingen av den **närings- och\nregionalpolitik** som regeringen har föreslagit kommer att leda till positiva\ndrag i Västmanlands utveckling. Vidare är det nödvändigt att, allt i\nenlighet med propositionen, de decentraliserade statliga organen och\nlänsförvaltningen får ökade resurser för att man inom länets gränser skall\n

Corpus:
protocol: corpus/protocols/1972/prot-1972--146.xml
xml-id: i-U9YPo7ECEWjveKyjx6PBs

Link to image is incorrect, it links to the previous page 
https://betalab.kb.se/prot-1972--146/prot_1972__146-121.jp2/_view

> Vi tror på att den fortsatta utvecklingen av den **näringsoch regionalpolitik** som regeringen har föreslagit kommer att leda till positiva drag i Västmanlands utveckling. Vidare är det nödvändigt att, allt i enlighet med propositionen, de decentraliserade statliga organen och länsförvaltningen får ökade resurser för att man inom länets gränser skall

We have these kind of issues where _word1- word2_ --> word1word2 all over the place. I estimate it to happen in 6.8% of textblocks in the protocol investigated (some of these merges may be correct however). 

### Example 2

Original data
https://betalab.kb.se/prot-1972--146/prot_1972__146-120.jp2/_view
Herr BERGMAN (s) kort genmäle:\nFru talman! Jag hoppas att fru Jonäng kan ändra sig i sitt yrkande (...)
 
Corpus:
Link to image is incorrect, it links to the previous page 
https://betalab.kb.se/prot-1972--146/prot_1972__146-119.jp2/_view

Text has been split in the corpus. This may be how we want to do it but it makes mapping back very difficult and since we now have intro detection using BERT it begs the question if we want to keep these old intro splits. We should at least split intros at the same time (BERT + potential regex) and not in different stages of the pipeline.

1. Herr BERGMAN (s) kort genmäle:
2. Fru talman! Jag hoppas att fru Jonäng kan ändra sig i sitt yrkande (...)

### Solution

Mapping back to the source data is a total mess atm and even if fuzzy methods are applied, this would be very time consuming and not be perfect (probably not even good enough). I suggest we update the alto --> corpus pipeline to the mappings. Updating the pipeline is also useful for adding more data (if we extend the corpus further back in time) or if we re-ocr some time period. We should also look over what processing is done to the text and correct any bugs there.

**Comment by ninpnin** [comment]
>We have these kind of issues where word1- word2 --> word1word2 all over the place. I estimate it to happen in 6.8% of textblocks in the protocol investigated (some of these merges may be correct however).

I'd wager that the majority of these cases are completely fine, see eg. https://betalab.kb.se/prot-1968--fk--18/prot_1968__fk__18-030.jp2/_view:

>herr Kristiansson har utförligt **argumen-[\n]terat**

and many others even on that page. We've matched and joined "[a-z]-\n[a-z]" in general. That does break the mapping, though.

**Comment by rbbby** [comment]
> We've matched and joined "[a-z]-\n[a-z]" in general. That does break the mapping, though.

This makes sense and I think it is fine to break the mapping like this. My example however does not fall into this regex category.

> närings- och\nregionalpolitik --> näringsoch regionalpolitik

It is _närings- och_ that gets merged. The newline does not matter here so this seems to be some other pattern.

<img width="783" alt="Screenshot 2022-06-15 at 11 25 51" src="https://user-images.githubusercontent.com/78153594/173794028-7e0bf703-9899-4e39-9256-e45ac7df9c29.png">

**Comment by ninpnin** [comment]
Found the bug: https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/pyriksdagen/download.py#L139

EDIT: too bad KB's servers seem to be down and we can't try and fix it yet.

**Comment by ninpnin** [comment]
Done.
