### ISSUE TITLE
speaker identification errors

### ISSUE THREAD

**Issue by Stubbendorff** [welfare-state-analytics/riksdagen-corpus#18]
Speaker identification, in particular for the first decades, involving names like Olsson, Larsson, Persson et cetera: The identification is often wrong. Example from prot-1926--ak--16.xml:

```
<note type="speaker" xml:id="i-be425506a8fc0b3e-0">

Herr Olsson i Gävle:

</note>

<u who="valerius_olsson_7d8b88" next="cont" xml:id="i-19cc56c1348c4cb1-0">
```

Herr Olsson from Gävle might be adolv_olsson_063f0c or lars_olsson_656369 (both from Gävleborgs län with seats in the second chamber) – but not Valerius Olsson representing Högerpartiet and Kalmar län.

In the protocols, the many Olssons, Perssons and Anderssons are often – but not always – identified by adding the town, village or region they represent or come from – like “Olsson i Gävle”. A way to improve speaker identification would be to use the metadata on region or   ##town.

**Comment by MansMeg** [comment]
Here are the different tasks we need to fix:
- [ ] Add name in parliament to the MP file. Although MPs can have multiple names in parliament during different sessions and if they become part of the government. So Maybe add this as a separate file.
- [x] Extract those introductions that cannot be identified with a simple regexp from the name in the parliament. This list would probably need manual curation? I.e extract connections missing when using a more defensive programming style?
- [ ] Add missing MP persons and unknown (others) to the MP files (like Göran Person when he was not part of the government?

**Comment by ninpnin** [comment]
We got a 100% precision and an 88% recall on the sample. Ie no non-introductions were labeled as such, and 88% of the introductions were labeled correctly.

**Comment by ninpnin** [comment]
We are now over 90% accuracy.
