### ISSUE TITLE
Create a testset for segmentation annotation

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#188]
We want to have good quality in the segmentation classification. I.e. the "seg"/"note"/"introduction"/"marginal notes" etc

When we know the quality of the page meta data as is explored in #186, we can create a test set for the segment classification.

We then want to do:
- [x] Define the classes to use - use the minimal possible set (maybe note/seg/introductions). 
- [x] Take a random sample of 3 pages per decade and annotate these pages segment in the parlaclarin files. Add to the annotation schema the definitions. 
- [x] Add these annotations to the corpus in the structure on adding manual information, marked as a testset
- [x] Estimate the accuracy based on the test set

In general, I think all segment classification should be dummy variables, just as introductions. The reason is that that makes it easier for classification. note/seg is also a binary. I don't know if introductions is part of note or seg.

**Comment by fredrik1984** [comment]
also #189

**Comment by ninpnin** [comment]
Done

**Comment by MansMeg** [comment]
Sorry for repoening. But where is this testset now? Is it in the repo?

**Comment by ninpnin** [comment]
testset is the gold standard

**Comment by MansMeg** [comment]
So its this file?
https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/corpus/quality_assessment/segment_classification/prot-segment-classification.csv

**Comment by ninpnin** [comment]
Exactly

**Comment by MansMeg** [comment]
Ok then i close it again. :)
