### ISSUE TITLE
Most common introductions from unknown speakers

### ISSUE THREAD

**Issue by TomasSkotare** [welfare-state-analytics/riksdagen-corpus#202]
A new list of the most common introductions from the speakers still not identified. 

Some seem to be low-hanging fruit, and several are "Talmannen" and so on, which can possibly be identified if we were able to identify who it was for each protocol.

[most_common_unknown_introductions.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/9936858/most_common_unknown_introductions.csv)

**Comment by ninpnin** [comment]
A heuristic for _talman_ matching already exists, there's just so many of them that missing a few percent of them makes it in the top.

**Comment by MansMeg** [comment]
This is great!

**Comment by MansMeg** [comment]
I looked up the first person. It can be multiple persons depending on the mandate period. 
Herr Johansson i Trollhättan. He could be Q5885419 (if 1915–1919) or Q5886301 (if 1971-1982). Q5886301 did not have Johansson i Trollhättan i wikidata but I added it. So we have two (social democratic) Johansson i Trollhättan. Do we check which persons that are active during the period @ninpnin ?

**Comment by MansMeg** [comment]
@TomasSkotare Is it possible to add a column with the range of the years the unknown in the csv? See my comment above.

**Comment by TomasSkotare** [comment]
This is the updated list for v0.5.0. Some changes from last time, but not that many!

[0.5.0_most_common_unknown_introductions.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/10499420/0.5.0_most_common_unknown_introductions.csv)

**Comment by ninpnin** [comment]
I looked into  Hilding Johansson ([Q5886301](https://www.wikidata.org/wiki/Q5886301)), i.e. Johansson i Trollhättan, who was at the very top of the list.

He's missing the alias in our metadata database:

```csv
Q5886301,1961,1970,Älvsborgs läns valkrets,andrakammarledamot
Q5886301,1971-01-11,1974-01-10,Älvsborgs läns norra valkrets,ledamot
Q5886301,1974-01-10,1976-10-04,Älvsborgs läns norra valkrets,ledamot
Q5886301,1976-10-04,1979-10-01,Älvsborgs läns norra valkrets,ledamot
Q5886301,1979-10-01,1982-10-04,Älvsborgs läns norra valkrets,ledamot
Q5886301,Hilding Johansson,True
Q5886301,Karl Hilding Johansson,False
Q5886301,,Hilding Johansson
Q5886301,1971-01-11,1974-01-10,Socialdemokraterna,Q105112
Q5886301,1974-01-10,1976-10-04,Socialdemokraterna,Q105112
Q5886301,1976-10-04,1979-10-01,Socialdemokraterna,Q105112
Q5886301,1979-10-01,1982-10-04,Socialdemokraterna,Q105112
Q5886301,,,Socialdemokraterna,Q105112
Q5886301,1915-02-02,1994-07-15,man,nan
```

He does have the alias "Johansson i Trollhättan" on [Wikidata](https://www.wikidata.org/wiki/Q5886301), but that seems to be only tagged as an alias in _English_. I re-ran the wikidata downloading script and the alias is still missing.

**Comment by ninpnin** [comment]
The same thing seems to be the case for [Herr WIKLUND i Stockholm (fp)](https://www.wikidata.org/wiki/Q6241320) and [Herr SVENSSON i Malmö (vpk)](https://www.wikidata.org/wiki/Q6198714), and perhaps for a lot of these people.

**Comment by MansMeg** [comment]
Hi!

I added these people in wiki data. Hmmm. I probably did the mistake of adding it as an alias in English. My fault. it should only be a handful, since I tried this out.

**Comment by MansMeg** [comment]
Now I fixed it!

**Comment by TomasSkotare** [comment]
I added years to the list (still based on the 0.5.0 release; perhaps it should be run on the dev branch?).
[most_common_unknown_introductions.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/10554428/most_common_unknown_introductions.csv)

Additionally, I created the matching file with the files (protocols) involved, which could be referenced if needed:

[most_common_unknown_introductions_with_files.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/10554495/most_common_unknown_introductions_with_files.csv)

**Comment by TomasSkotare** [comment]
Here is the version (without files) for 0.5.1:
[most_common_unknown_introductions_v0.5.1.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/10685642/most_common_unknown_introductions_v0.5.1.csv)

I can add with files if requested.

**Comment by ninpnin** [comment]
Once the extension up until 1867 is done, we want to regenerate this file for the new protocols.

**Comment by fredrik1984** [comment]
#323 and #346
