### ISSUE TITLE
Current most common identified speakers who has no party affiliation

### ISSUE THREAD

**Issue by TomasSkotare** [welfare-state-analytics/riksdagen-corpus#203]
This is a list of people who are known (identified) but do not have a party affiliation scraped (in [party affiliation](https://raw.githubusercontent.com/welfare-state-analytics/riksdagen-corpus/main/corpus/metadata/party_affiliation.csv)).

One of these has a party affiliation set in [member_of_parliament](https://raw.githubusercontent.com/welfare-state-analytics/riksdagen-corpus/main/corpus/metadata/member_of_parliament.csv) - [Q5912635](https://www.wikidata.org/wiki/Q5912635)

There are probably more sources for estimating party affiliation but it's not always crystal clear where to begin. I believe that the overall affiliation should always be available in the party_affiliation csv, with further details in the others.

CSV File of most common known persons without specified affiliation:
[known_person_but_unknown_party.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/9937205/known_person_but_unknown_party.csv)

**Comment by ninpnin** [comment]
I checked some of the people with most speeches. Interestingly, some of those have a party on Wikidata, while some do not. Maybe we should rescrape the data?

**Comment by ninpnin** [comment]
Either way, I think we should move the all party affiliations to the party affiliation file. Having some in the party affiliation file and some in the member of parliament one is confusing, even if it corresponds to two different data sources.

**Comment by MansMeg** [comment]
I fully agree. We should let the data be the API and make it as intuitive as possible.

**Comment by TomasSkotare** [comment]
This is an updated version for 0.6.0 (after the merge with member of parliament).

This is, as far as I can tell simply a lack of information in the metadata, which impacts 4067 speeches currently.

[known_person_but_unknown_party.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/10882309/known_person_but_unknown_party.csv)

**Comment by fredrik1984** [comment]
Ok, so not suuper many known MPs with unknown party affiliation. I guess this should be fairly easy to do manually.

**Comment by fredrik1984** [comment]
This will be solved with #349 and the work that Lotta, Mattias and I are doing by going through the bio books looking for specific dates and parties for MPs.

**Comment by BobBorges** [comment]
closing as duplicate of #349
