### ISSUE TITLE
Add riksdagen-öppna-data id to MPs and speeches

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#204]
In riksdagens öppna data there exists an ID of both the individual speeches and the individual members of parliament.

We should add this ID as metadata to the corpus. Both concerning the MPs and the speeches (anföranden). This will help further simplify quality improvements.

**Comment by Lauler** [comment]
It should be possible to do this, though it might require a bit of work. Riksdagen publishes transcripts already segmented on the speech level here: https://data.riksdagen.se/data/anforanden/ . 

Downloading the json-files, there exists a field under "dokumentstatus" -> "dokbilaga" -> "bilaga" -> "fil_url" that links to the source files you appear to be using when parsing protocols. This at least lets you identify the correct protocol file under [riksdagen-corpus/corpus/protocols](https://github.com/welfare-state-analytics/riksdagen-corpus/tree/main/corpus/protocols) that contains the individual speech. 

In riksdagen-corpus protocol files the speeches are numbered (`Anf. ##`). This number is the key to matching individual speeches from riksdagens ID-system with the riksdagen-corpus format. 

For example:

1. For example, [Per Bolund's (MP) speech](https://github.com/welfare-state-analytics/riksdagen-corpus/blob/dc6a45ba60352ce31b18e2fe8051f332106a1202/corpus/protocols/202021/prot-202021--144.xml#L2327-L2442) in the interpellation debate "Sveriges ansvar för giftigt avfall i Chile" is numbered "Anf 26" in the [source document](https://data.riksdagen.se/fil/A96AAC5F-24F2-4677-A6C6-3AE22AC276E9#page=25) you've parsed.
2. The source document id (https://data.riksdagen.se/fil/A96AAC5F-24F2-4677-A6C6-3AE22AC276E9) can be used to join the individual speech from riksdagen's öppna data with the protocol file in riksdagen-corpus. In riksdagen's öppna data this source document is available under "dokumentstatus" -> "dokbilaga" -> "bilaga" -> "fil_url" if you download the json formatted files. 
3. In riksdagen's öppna data each debate has an ID (`dokid`). For Per Bolund's speech it's `H810772`. Each speech also has an `anforande_nummer`. Per Bolund's is `26`. 

So, necessary information:

**From riksdagen öppna data**  
* `fil_url`
* `anforande_nummer`

**From riksdagen-corpus**
* The url in `<pb facs>` field without the page indication. E.g. http://data.riksdagen.se/fil/A96AAC5F-24F2-4677-A6C6-3AE22AC276E9#page=1 (remove #page=1).  
* Parse the speech number (`Anf ##`) from every new speech \<note type="speaker"\> in a protocol xml file.

Using these, you could connect the two data sources.

**Comment by MansMeg** [comment]
Great with this info!
