### ISSUE TITLE
Fix segmentation in 1995

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#206]
There seem to be problems in how the data was segmented in 1995. We should check these protocols and potentially fix this.

**Comment by fredrik1984** [comment]
Lars Brink at the Riksdag Library might be is working on it and are suppose to connect these records to KBLab

**Comment by fredrik1984** [comment]
Main from Lars Brink 2023-03-24:

"Jag fick höra att det för protokollen  ~1995 skiljde sig åt mellan vad vi har på riksdagen och KB-labb har.
                                                                             
Vi har inte ändrat något hos oss sedan sent 2015 på webben. Så kanske KB-labb har materialet från det vi skannat senare som vi själva inte har hunnit publicera/ta hand om. Minns att jag överlämnade en disk till KB för överföring av data – det kanske var just från skanningen. Vi har skannat protokollen fram till 1867–1994/95.
 
Så just 1994/95 finns i två olika PDF-format. Dels skannat med OCR och dels skapat från Word utan OCR."

**Comment by fredrik1984** [comment]
At the morning meeting today I said that I could contact KBLab about this. But now I am thinking if it is not better if we fix it ourselves. What do you say @MansMeg and @ninpnin?

**Comment by MansMeg** [comment]
Im not sure we can. But I don't remember the details here.
