### ISSUE TITLE
List of most common speakers marked as "uncertain" affiliation, by decade

### ISSUE THREAD

**Issue by TomasSkotare** [welfare-state-analytics/riksdagen-corpus#209]
Party affiliation is "uncertain" if the speaker, at the date of speaking, is not within one the time range of ONE specified party affiliation.

This can happen if more than one party is assigned to that time (due to affiliation only being specified by year, for example), no party has start/end dates, and similar issues. 

It is possible to extract exactly why it was considered "uncertain" but this is not currently done.

NOTE:
One huge exception is that if a speaker only has a single party defined, that will always be assumed to be certain, even if the time is undefined. This exception was made to find anything, as the majority of speakers would otherwise be uncertain (they only have one party and with no set start/end date).

This is a plot showing which years have the most "uncertain" speakers:
![image](https://user-images.githubusercontent.com/8590039/202163921-fc3493fa-6353-48a3-87e4-565357c8dc66.png)

And here is a full list of the uncertain speakers, with number of speeches per decade listed. The list is roughly sorted by ascending decade of when the speeches were made.
[uncertain_per_decade.xlsx](https://github.com/welfare-state-analytics/riksdagen-corpus/files/10020978/uncertain_per_decade.xlsx)

**Comment by MansMeg** [comment]
Great with this information!

**Comment by MansMeg** [comment]
I think I found an explicit example of this:
Herr Nordstrandh (h) is set to unknown. But the MP exist as as member of the moderate party (h is högerpartiet): Q6016028 So this is an example of the same thing.

**Comment by TomasSkotare** [comment]
This is an update for how it looks since 0.5.0 (including 0.5.1) - I'm assuming metadata has changed, including start-stop dates of people, which causes the uncertain flag to be set.

![image](https://user-images.githubusercontent.com/8590039/219664551-454cda10-c74e-4f96-bcec-cc35eee88fb9.png)


Perhaps this is worth a look?
[uncertain_per_decade.xlsx](https://github.com/welfare-state-analytics/riksdagen-corpus/files/10767180/uncertain_per_decade.xlsx)

**Comment by ninpnin** [comment]
If you have the following rows

```csv
wiki_id,start,end,party
Q1234567,,,social democrat
Q1234567,1955,1969,social democrat
```

I think it should be up to the user to deduct that the person is a social democrat for the whole time period.

**Comment by TomasSkotare** [comment]
After accounting for cases where there is only one possible party regardless, the plot looks like this:

![image](https://user-images.githubusercontent.com/8590039/220143573-1a5bdd77-5df3-41fe-84fb-00265c805421.png)

While much improved, it still contains more errors than it used to. I assume (but haven't checked) that this is due to us having more available metadata. More choices lead to more uncertainty, even if it is likely more correct in this case.

**Comment by MansMeg** [comment]
Can you point out a specific error? Ie give an example?

**Comment by Stubbendorff** [comment]
the 1920s and 1930s have several MP:s changing parties due to the split of both the communists and the liberals. if there are no clear dates in wikidata, party belongings will be uncertain. this might explain part of it.

**Comment by TomasSkotare** [comment]
> Can you point out a specific error? Ie give an example?

I cannot say for certain if there is any error, just that we're not certain. There are many reasons for this, most commonly that the time span specified in wikidata doesn't match the speech.

The peaks in 1923 and 1934 are due to several speakers having the option of multiple different parties. Perhaps this can be handled by improved logic down the line, but at least it hasn't changed since the first version of this post.

**Comment by MansMeg** [comment]
Do you have any examples of these speakers in the period 1923-1934 with multiple different parties and their entries in the metadatabase?

**Comment by TomasSkotare** [comment]
For 1923:
Q55955      83
Q53642      53
Q1347810    48
Q6046940    35
Q6086670    33

For 1934:
Q53294      78
Q53650      67
Q5972050    62
Q5340170    57
Q5960142    53

(Number of speeches marked)

**Comment by MansMeg** [comment]
I looked up Q55955, and he only belonged to "Socialdemokratiska vänstergruppen" that year. So there is no uncertainty (if the wikidata and our metadata is synced). I think the error is on your end to solve, at least for that one.

**Comment by MansMeg** [comment]
But please list those with overlapping dates.

**Comment by TomasSkotare** [comment]
> I looked up Q55955, and he only belonged to "Socialdemokratiska vänstergruppen" that year. So there is no uncertainty (if the wikidata and our metadata is synced). I think the error is on your end to solve, at least for that one.

You are correct, in a way; the issue here is that the code considers "1923" as "1923-01-01" , so we get this issue where it's not clear if we mean all of 1923 or not.

While it will cause some errors, perhaps it's best to consider the end date "1923" to be the last day of the year instead?

**Comment by MansMeg** [comment]
Yes. I think that is probably obvious from the context. In the long run, we should probably fix this to simplify. But for now, I guess this falls on you.

Although, if you find MPs with overlapping dates, please file that as an issue.
