### ISSUE TITLE
Extend the corpus back to 1866 and the start of the two-chamber system

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#21]
- [x] 1910-1920
- [x] 1900-1910
- [x] 1890-1900
- [x] 1880-1890
- [x] 1867-1880

**Comment by ninpnin** [comment]
Ten yaers at a time

- [ ] 1910-1920
- [ ] 1900-1910
- [ ] 1890-1900
- [ ] 1880-1890
- [ ] 1867-1880

**Comment by fredrik1984** [comment]
Below are some notes from Lotta and Mattias at the Riksdag Library about layout changes during the bicameral period. This could be good to keep in mind when we start the quality control of the earlier decades.

Hej igen Fredrik,
Gjort nedslag i ett litet antal protokoll under tvåkammartiden, 1867, 1875, 1903, 1912, 1948, 1956, 1965
 
1867, FK, protokoll nr 507 första sidan, inleds med namn följt av kolon, sedan kommer anförandet.
Friherre Sprengtporten:
Kan även finnas med ort innan kolonet.
När vi sett statsråd som varit med framgår titeln före namnet.
 
 
Ett exempel gällande anförande av talmannen under 1867, FK, är protokoll nr 507 på sidan 394. Det visar på problematiken som kan dyka upp.
 
Sedan öfver!äggningen härefter förklarats slutad, yttrade Herr Grefven och Talmannen, att derunder hade yrkats, dels af Herr Beckman, att Kammaren för sin del måtte fatta ett så lydande beslut: »att Riksdagen, som erkänner behofvet af de presterliga befordringslagarnes revision, med afslag å det af Andra Kammaren fattade beslut, för sin del beslutar en underdånig framställning till Kongl. Maj:t, om beredande i grundlagsenlig ordning af en förändring i gällande lagar för presterlig befordran och prestval i den syftning, att tillfälle lemnas församlingarne i konsistoriela pastorat, att, före ansökningstidens utgång, få hos vederbörande domkapitel begära tvänne profpredikanter, hvilkas kompetens till den ifrågavarande sysslan domkapitlet i laga ordning eger pröfva och, derest denna godkännes och laga hinder i öfrigt icke möta, för dessa utfärda missiv till predikoprofs afläggande näst före de å förslaget uppförde»; och dels, att
 
Även sett varianter där det står ord mellan namnet och kolonet, t.ex. 1912, FK, protokoll nr 1, s.1
Herr Jonsson, Olof, framträdde till talmansbordet och yttrade:
 
1938, AK, protokoll nr 22.
Inga versaler i efternamnet, dock fetstil
Herr Jonsson i Eskilstuna:
 
1948, FK, protokoll nr 27, versaler i efternamnet och fetstil, men ingen partitillhörighet. Dock ett förnamn ibland (särskiljande?)
Herr KARLSSON, GUSTAF:
 
1956, FK, protokoll nr 22. Visar på antal ord mellan efternamnet och kolon. Med partitillhörighet.
Herr NORD (fp) kort genmäle: Herr talman!
 
Även protokoll från 1965, versaler t.ex.
Herr BENGTSON (ep):
 
Så:
Testen 1867, 1875, 1903, 1912, 1914, visar att namnen i de nedslag vi gjort verkar skrivas på samma sätt. Inga versaler eller fetstil. Utan med Herr + namn + ev ort. Kan finnas tillägg med titel framför Herr. Kolon efter namn, ort eller eventuella andra ord. Möjligen är namnen skrivna med lite mer utrymme mellan bokstäverna.
 
Test 1938 har fetstil i efternamn.
Test 1948 har versaler och fetstil i efternamn
Test 1956, 1964 har fått tillägg med partitillhörighet.
 
När det gäller din andra fråga är det lite problematiskt. Talmannen leder arbetet i kammaren. Ett anförande av talmannen övergår till att leda arbetet. Frågan är vad ni vill ha med från talmannen? Även det hen säger i kammaren i form av vad som händer och instruktioner för arbetet kan vara av intresse beroende på vad man som användare letar efter.

Vi får prata vidare om detta.
 
 
Vänlig hälsning
Lotta
