### ISSUE TITLE
Move pyriksdagennlibrary to separate repo

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#210]
There is a need to use and add variables that can easily be derived from the corpus. Examples are junior mps (first term mps), age at speach etc. 

We should create a python library with this type of unctionality as a separate repo. The functions there should have test suites for the functionality and be implemented so they are easy to reuse.

we need to decide on the API. I suggest we have a prefix ”var_” for derived variables. Eg var_junior_mp()

**Comment by ninpnin** [comment]
Duplicate of #88
