### ISSUE TITLE
Swedish Parliament person GUID

### ISSUE THREAD

**Issue by ninpnin** [welfare-state-analytics/riksdagen-corpus#213]
- [x] Remove from person.csv since there may be multiple of them per person. Add a separate later
- [ ] Create a new table for them in corpus/metadata

**Comment by salgo60** [comment]
FYI we have reported this duplication errror in sep 2022 to Riksdagen. I called them also and they said its wrong but still its there there and no reporting back....  

My understanding/guess is that they have added the metadata to one of the profiles --> I make that profile **[WD preferred](https://www.wikidata.org/wiki/Help:Ranking)**

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/14206509/210167208-b78b2e23-88de-4b47-9564-9c7aad548dea.png">


<img width="1069" alt="image" src="https://user-images.githubusercontent.com/14206509/210167295-6564dafb-438e-43de-b49b-bea815382fee.png">


* issue with 3 duplicates [#21](https://github.com/every-politician-scrapers/sweden-riksdag-api-current/issues/21)
   * The profiles we found
        *  [wd:Q63975366](http://www.wikidata.org/entity/Q63975366) Jessica Stegrud
        * [wd:Q4988619](http://www.wikidata.org/entity/Q4988619) Jytte Guteland
        * [wd:Q16160202](http://www.wikidata.org/entity/Q16160202)	Ilan De Basso

* my [Riksdagen Open Data backlog](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/50) 
   * [#88](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/88)
