### ISSUE TITLE
Extract all names from the protocols that now is unknown

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#216]
If we could get a list of the most common names that are unknown (Herr/Fru XX i YY) as a csv from the pariliament, we could just manually add those to wikidata. At least those with a frequency of occurrences larger than say 5.

I think these alias would be nice to have also for wikidata. Then we could do a pass to just update these names in our corpus.

**Comment by fredrik1984** [comment]
I think this is a good idea too. And we would at the same time improve our annotated speech corpus.

**Comment by MansMeg** [comment]
Exactly. That would probably increase the quality of the speaker mapping. Yesterday I saw an example of this.

**Comment by ninpnin** [comment]
Duplicate of #202 
<img width="460" alt="Screenshot 2023-01-17 at 15 15 04" src="https://user-images.githubusercontent.com/10169469/212921644-357354fe-8f3e-43b9-944a-34015d50da0d.png">
