### ISSUE TITLE
MP missing in wikipedia/wikidata

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#217]
We have found that Gunnar Olsson (s) i Edane is missing in wikidata and wikipedia. He was a member om enkammarriksdagen. Born 1920, see here: https://sv.wikipedia.org/wiki/Gunnar_Olsson

@salgo60 Could you add him to wikipedia/wikidata?

**Comment by salgo60** [comment]
@MansMeg han fanns i Wikidata [Q110994286](https://www.wikidata.org/wiki/Q110994286?uselang=sv) vill ni ha dom i Wikipedia också?
* dom som saknar [Wikipedia artikel men finns i Wikidata](https://js.histropedia.com/apps/query-timeline/index.html?q=SELECT%20distinct%20?person%20?personLabel(sample(?bild)%20AS%20?bild)%20%0A?birth%20?death%20?partyLabel?wiki%20WHERE%20%7B%0A%0A%20%20VALUES%20?member%20%7B%0A%20%20%20%20wd:Q33071890%20%0A%20%20%20%20wd:Q81531912%20%0A%20%20%20%20wd:Q82697153%20%0A%20%20%20%20wd:Q10655178%20%0A%20%20%7D%0A%20%20?person%20wdt:P39%20?member;%0A%20%20%20%20wdt:P1343%20?source.%0A%20%20?person%20p:P1343%20?pTva.%0A%20%20OPTIONAL%7B?person%20wdt:P102%20?party%7D%0A%20%20OPTIONAL%7B?person%20wdt:P569%20?birth%7D%0A%20%20OPTIONAL%7B?person%20wdt:P570%20?death%7D%0A%0A%20%20OPTIONAL%20%7B?person%20wdt:P18%20?bild%7D.%0A%20%0Aminus%20%7B%0A%20%20%20%20%20%20?wiki%20schema:about%20?person%20.%0A%20%20%20%20%20%20?wiki%20schema:inLanguage%20%22sv%22%20.%0A%20%20%20%20%20%20?wiki%20schema:isPartOf%20%3Chttps://sv.wikipedia.org/%3E%20.%0A%20%20%20%20%7D%0A%20%20SERVICE%20wikibase:label%20%7B%20bd:serviceParam%20wikibase:language%20%22sv,en%22.%20%7D%0A%7D%20GROUP%20BY%20%20?person%20?personLabel%20%20?death%20?birth%20?partyLabel%20?wiki%0Aorder%20by%20?partyLabel&md=true&g=article&l=person&t=personLabel&s=birth&e=death&i=bild&d=0&c=partyLabel&f=partyLabel&v=t) kommer bli fler...

ÖT: Tror ni kanske skulle ha en kontakt med Svenskt Porträtt arkiv dom gör om allt verkar det som dvs. dom scannade bilderna av boken Två-kammarriksdagen varje person kan i värsta fall flyttas kanske vore ide att tanka hem det.... jag har ingen kontakt med dom men finns en [Per Rohdin](https://blogg.bildhistoria.se/author/perrohdin/) som har tagit över skutan och skapar en ny version med kanske ny arkitektur hans GITHUB @perrohdin

**Comment by MansMeg** [comment]
Great! Then that is not the problem that I thought it was. Maybe we will see what happens when @TomasSkotare reruns the unknown speaker script.

**Comment by MansMeg** [comment]
Vi behöver dem bara i wikidata. Men hade svårt att läsa där.
