### ISSUE TITLE
Talman is unknown

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#218]
It seems like if the introduction says talman the person is commonly set to unknown. This is not super-important to fix now. But should be part of the backlog on stuff to fix long-term.

**Comment by fredrik1984** [comment]
On this Wikipedia page there is lists of all ordinary talmän, and all vice talmän (and vice vice talmän for the period 1971–) in Sweden since the Riksdag of Estate

https://sv.wikipedia.org/wiki/Sveriges_riksdags_talman

**Comment by ninpnin** [comment]
https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/corpus/metadata/speaker.csv This metadata seems comprehensive.

@MansMeg can you link to specific cases so we can investigate further?

**Comment by MansMeg** [comment]
I found it in @TomasSkotare s file in #202 . Roughly 4000 instances of Herr TALMANNEN is classified as unknown. So the question is how to handle this?

**Comment by fredrik1984** [comment]
Until we know if it is ordinary or vice speaker maybe we should annotate those as "Speaker of the house". Then we should get a better sense of how many "real" unknowns we have. Or maybe @ninpnin has a better idea?

**Comment by MansMeg** [comment]
Is this now done and should be closed? Or should we add the identified issues on segmentation quality and multiple persons in introductions?

**Comment by ninpnin** [comment]
This one is done. Let's make sure the adjacent issues are tracked.

**Comment by MansMeg** [comment]
Are they tracked?
