### ISSUE TITLE
Multiple birth-dates with different sources

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#222]
In the discussion on the 20th of January, we realized there could exist multiple dates for the same persons with different references in wikidata. The question is how we should handle this. We want a unit test to assert that persons.csv only has one person per line. 

@ninpnin wrote he solved this in 0.5.

Is this even still a problem?

**Comment by ninpnin** [comment]
This seems to not be an issue. I checked and there were no duplicates when it comes to birthdates.
