### ISSUE TITLE
Add the manually checked mappings by Emil

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#225]
Emil has manually checked the unknown speaker list. We need to add these manual edits to the data. 

Also these edits should be considered manually checked and should probably be stored as known mappings. These known mappings should be used to unit test the data so these introductions does not change with changes in wikidata.

Also, there are almost 4400 empty introductions mapped as ”unknown” in the csv. This should be checked at the same time.

**Comment by fredrik1984** [comment]
This issue relates to #323, right?

**Comment by MansMeg** [comment]
Yes. Its related.

**Comment by BobBorges** [comment]
Emil-file as unit test implemented in #278

"unknown" intros is a duplicate issue #323 

Closing.
