### ISSUE TITLE
Add mp data from the personregister

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#226]
In each digitized protocols (per year). There exist a personregister. The layout changed in the 1960ies but is in general consistant over time.

From these personregister we want to extract the following information and add that to the mp database:
- [x] Role in parliament (ersättare ordinarie and dates)
- [X] Election district: valkrets
- [ ] Committee positions (utskottsroller)
- [ ] Chair

**Comment by ninpnin** [comment]
I think election district is already covered pretty well.

**Comment by MansMeg** [comment]
When Emil is don with his lists we should checks which person is lacking this information and maybe add it manually to wikidata.

**Comment by MansMeg** [comment]
Now added as separate issues instead.
