### ISSUE TITLE
Rename protocols with Swedish characters

### ISSUE THREAD

**Issue by ninpnin** [welfare-state-analytics/riksdagen-corpus#229]
There are some protocols that have umlauts / Swedish characters in their filenames, eg.

>corpus/protocols/1969/prot-1969-höst-ak--43.xml

This already needs a special setting for git to work properly. Recently, zipping and unzipping turned this filename into 
>corpus/protocols/1969/prot-1969-h├╢st-ak--43.xml

Umlauts also break [XML inclusions](https://www.w3.org/TR/xinclude-11/) that we'll probably start using soon (#227). For these reasons, we should change these into

>corpus/protocols/1969/prot-1969-host-ak--43.xml

as it is not going to lead to conflicts anyway. The identifiers can be stored in the actual XML documents if we need them for something.

```XML
<!--- corpus/protocols/1969/prot-1969-host-ak--43.xml -->
<TEI xml:id="prot-1969-höst-ak--43">
<!--- rest of the document -->
```

**Comment by MansMeg** [comment]
I guess it is good then to also change the id to "host"?

**Comment by ninpnin** [comment]
I would keep the old id, so that it matches the betalab id.

**Comment by MansMeg** [comment]
Maybe instead have a separate betalab id. We should not use external id as our internal ids. That is kind of a bad habit. At least long term.

**Comment by fredrik1984** [comment]
@BobBorges – this relates to the discussion with Leif-Jöran and the "höst" riksdag protocols. Has this issue been solved?

**Comment by BobBorges** [comment]
let me double check

**Comment by BobBorges** [comment]
Solved. no funny characters in protocol paths/names:

`['-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'c', 'f', 'i', 'k', 'l', 'm', 'o', 'p', 'r', 's', 't', 'u', 'x']`
