### ISSUE TITLE
Create a baseline gold standard estimate of quality dimensions

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#232]
As a first step we want to create a baseline for quality estimation in the corpus. The target is to estimate the error along the different dimension of interest. Detailed information can be found here:
https://docs.google.com/document/d/1GauUJAx__rGkdMe5N54FxTT3jdcCvVnvHi_1-Q6AipA/edit?usp=sharing

We want to do the minimal annotation needed as described in the document in the following order of priority:
- [x] Segmentation classification
- [x] Speaker mapping
- [x] Segmentation error
- [x] OCR error

**Comment by fredrik1984** [comment]
@ninpnin @liamtabib the first three are done, right? Only OCR dimension left, which Liam will do?

**Comment by BobBorges** [comment]
We want to

- [ ] move `input/gold-standard/` stuff to `corpus/quality_assessment/`

Where are files related to segmentation error gold-standard? 

- [ ] move to `corpus/quality_assessment`
