### ISSUE TITLE
Quality assessment of the MP database

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#243]
Our MP database will be an important infrastructure in itself. Hence, the goal should be to have ALL MPs since 1867 in the database, with at least some rudimentary metadata. We need therefore to perform a manual quality assessment of the database and the MPs included (and not) in it.

Important MP metadata categories: name, party, gender, date of birth, i-ort, kammaruppdrag (ordinarie, ersättare, statsrådsersättare), valkrets, utskottsuppdrag/roller (committees, government, speaker of the house), uppropsnummer, chair, occupation. 

A first step could be to draw a sample of MPs from the biography series and see how many are missing from our database.

**Comment by ninpnin** [comment]
This would be very good.

>biography series

Is this easily available? I'd like to take a look and see how the sampling could be implemented.

**Comment by ninpnin** [comment]
Is this and #245 the same thing though?

**Comment by fredrik1984** [comment]
Yes, it is the same. I don't know if it is on GitHub, but I can send you it through sprend

**Comment by MansMeg** [comment]
I think we should do this by checking all wikidata ids that Emil and Magnus has checked and look in our database that they exist.

**Comment by salgo60** [comment]
@fredrik1984  Maybe related
* I started a discussion right now on Swedish Wikipedia  a discussion about if we can [document different sources quality/trust](https://sv.wikipedia.org/wiki/Wikipedia:Bybrunnen#Ess%C3%A4er_om_skillnaden_i_kultur/kvalitet_hos_olika_k%C3%A4llor)
  * a template I did 2028 about the my understanding of the [quality of Riksarkivt SBL](https://sv.wikipedia.org/wiki/Anv%C3%A4ndare:Salgo60/Source:SBL)
  * my question to Denny the designer of Wikidata and he thoughts of sources and trust [video](https://www.youtube.com/watch?v=VdAc0JReVSw&t=2450s)
  * my draft if we can add that to Wikidata [T222142](https://phabricator.wikimedia.org/T222142) "WikidataCon 2019: We need a better model communicating quality/relevance of sources in Wikidata / Provenance"
  
[<img width="1172" alt="image" src="https://user-images.githubusercontent.com/14206509/229743006-40541037-0d0e-4ae1-9950-8a68e3cca798.png">](https://sv.wikipedia.org/wiki/Anv%C3%A4ndare:Salgo60/Source:SBL)

**Comment by salgo60** [comment]
FYI @fredrik1984 One thing we dont have in Wikidata is school education

e.g. Folkräkningar (Sveriges befolkning) 1930 - [Folk_128505791](https://sok.riksarkivet.se/?postid=Folk_128505791) is about [Q16649279](https://www.wikidata.org/wiki/Q16649279) and he has _(folkskolans påbyggnader; lägre specialutbildning)_

I have seen that [SCB publish aggregated data about education for Swedish PM](https://www.scb.se/hitta-statistik/artiklar/2021/sveriges-politiker-hogre-utbildade-an-sina-valjare/) and I have asked for getting it per person with no success -  [created #102](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/102)

* SPARQL WD objects in the Swedish PM with source [Q50798414](https://www.wikidata.org/wiki/Q50798414)
  * https://w.wiki/6XuL -  2023 04 04 - 54 results
  
I will send a [question to Swedish Riksarkivet](https://github.com/Riksarkivet/dataplattform/issues/14) if they have an API and any plans on curating the eduction  data...

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/14206509/229773143-246cc9e3-280d-4fa2-b7e4-aa0c9b436de1.png">

### Occupations ###
In Wikidata its a small chaos but we try to have WD objects for occupations.... I did an overview some Swedish sources (Alvin, SKBL SBL...) usage of Occupation see [salgo60/HISCOKoder](https://github.com/salgo60/HISCOKoder) and tried started an [dialogue with no success](https://github.com/salgo60/HISCOKoder/issues/1) 2021

**Comment by fredrik1984** [comment]
Hm, I think school education is the Tvåkammar book, no? See this attached example
![Skärmavbild 2023-04-04 kl  14 09 34](https://user-images.githubusercontent.com/15212990/229787394-acd86738-a9b3-410a-8a7c-97a393bea83f.png)

**Comment by salgo60** [comment]
@fredrik1984 great and we sometimes add [Alma Mater P69](https://www.wikidata.org/wiki/Property:P69) in WD see [SPARQL Swedish PM](https://w.wiki/6XvQ) / [grouped = 209 different](https://w.wiki/6XvG) / [Map](https://query.wikidata.org/embed.html#%23title%3A%20Map%20P39%20for%20Swedish%20PMs%20in%20WD%0A%23defaultView%3AMap%0ASELECT%20distinct%20%3Fperson%20%3FpersonLabel%20%3Fedu%20%3FeduLabel%20%3Fcoord%20WHERE%20%7B%0A%20%20%20values%20%3Fsource%20%20%7Bwd%3AQ50798414%7D%0A%20%20%20values%20%3FposHeld%20%20%7B%20wd%3AQ33071890%20wd%3AQ81531912%20wd%3AQ82697153%20%0A%20%20%20%20wd%3AQ10655178%20%7D%0A%20%0A%20%20%3Fperson%20wdt%3AP39%20%3FposHeld.%0A%20%20%3Fperson%20wdt%3AP69%20%3Fedu.%0A%20%20%3Fedu%20wdt%3AP625%20%3Fcoord%0A%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22%20.%20%0A%20%20%7D%0A%7D%20order%20by%20%3FpersonLabel) _quality unknown_

[<img width="1175" alt="image" src="https://user-images.githubusercontent.com/14206509/229791798-ef8a7bf7-3a18-482f-abee-d108689d7664.png">](https://w.wiki/6XvG)

[<img width="1175" alt="image" src="https://user-images.githubusercontent.com/14206509/229792235-ab8a64b3-6534-464c-90bf-082480bcaace.png">](https://w.wiki/6XvJ)

### Uppsala Universitet I guess we should not just have schools also education/skills

I think WD has Alma Mater Uppsala Universitet but I guess it would be more interesting to understand the skill matrix of people in the Swedish parlament and what exams they have... my feeling one reason we [dont have better Riksdagens Öppna data](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/50) is the lack of IT skills in the Swedish PM and they cant understand why they need data as data and a [SPARQL endpoint #62](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/62) / [consequencies of not having 5 stardata #71](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/71) / dont see the [possibilities connecting EU <-> Kommuner #98](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/98)....

[<img width="1175" alt="image" src="https://user-images.githubusercontent.com/14206509/229896275-d39cbddc-6768-4108-86a6-1cf65071c5d1.png">](https://w.wiki/6XvJ)

### Riksarkivet Folkräkningar (Sveriges befolkning) 1930
The benefits with Riksarkivet is that they have it structured and maybe cleaner 🙏 and we maybe **get better trust when data same as Riksarkivet** 

**[Feedback Riksarkivet](https://github.com/Riksarkivet/dataplattform/issues/14#issuecomment-1496046133)**: its in the pipe but looks like they have nothing to show yet...

OT: I did a try with Bildhistoria to map all Swedish Schools but gave up see [#1](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/issues/1) ... see [comment Johannes Westberg](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/issues/1#issuecomment-1127392047) that its a rather tough challenge ;-)

**Comment by fredrik1984** [comment]
Ah, cool! It will be cool to get education etc in the Swerik corpus, although it is not the highest priority for now.

**Comment by salgo60** [comment]
I like the metaphor Google presented  at "Applied semantics: beyond the catalog" at [12.29 min](http://videolectures.net/iswc2017_taylor_applied_semantics/#) that Linked data means that we dont start from scratch all the time instead we use what we find and tries to add value... no one if we do this right needs to encode one more time that [Andersson/Olin studied at Harvard](https://w.wiki/6Xvj)... or who [studied in the States](https://w.wiki/6Xwf)


[<img width="1175" alt="image" src="https://user-images.githubusercontent.com/14206509/229798944-2e63824d-eb93-4a67-8248-fcb6647d6629.png">](https://w.wiki/6Xvj)

[<img width="1175" alt="image" src="https://user-images.githubusercontent.com/14206509/229898799-a3c72d1a-98fa-4443-b11d-d0de9ea7ad07.png">](https://w.wiki/6Xwf)
