### ISSUE TITLE
Missing Wiki_ID for members in parliament in 1925

### ISSUE THREAD

**Issue by lirrek** [welfare-state-analytics/riksdagen-corpus#244]
Hi everyone! I have found three MPs that do not have a wiki_id. They are the following (reference to the "Biografibanden" in the parentheses):

1. Ernst Göransson (spelled ”Göranson” in the roll call protocol), Alias: Göransson i Falla, Chamber: Andra kammaren (AK), Years active: 1925-1928, District: Jönköpings län. (Biografibanden, Band 2, p. 156). 
He appears in the first roll call protocol on the 28th of february 1925.

3. Otto Johansson, Alias: Johansson i Väby, Chamber: Andra kammaren, Years active: 1925-1932 (21-03-1932), District: Älvsborgs södra valkrets.  (Biografibanden, Band 4, p. 241) 
He appears in the first roll call protocol on the 28th of february 1925.

4. Herman Smedh,  Alias: Smedh i Bergarklås, Replaced Fredrik Aarnseth in AK when Fredrik died in 16th April 1925. Chamber: Andra kammaren & Första kammaren, Years active: 1925 (16-05-1925) – 1928 and FK in 1936. District: Kopparbergs län. (Biografibanden, Band 5, p. 92).
He makes his first appearance in the roll call protocol on the 16th of may 1925.

Hope this information is enough and useful. More information on the MPs can be found in the cited pages in the Biografibanden.

**Comment by MansMeg** [comment]
Hi!

I looked them up quickly.
1 and 3 seem to be missing also in Wikidata. @salgo60 could you confirm this? I.e. I guess we need to add them to wikidata?
2 has wiki id Q116687054, @ninpnin can you check why we don't have him in the data? It seems like a bug?

**Comment by salgo60** [comment]
Thanks WIP -  @MansMeg @lirrek 

* [x] Ernst Göransson [Q117011372](https://www.wikidata.org/wiki/Q117011372)
* [x] Otto Johansson [Q116687054](https://www.wikidata.org/wiki/Q116687054)
* [x] Herman Smedh [Q117018060](https://www.wikidata.org/wiki/Q117018060)

Let me know if we should share screens and I can show you how I work... I am available until friday and will be in the Italien alps next week not caring about Swedish PM people ;-)

* I think we will have some 100 missing persons in WIkidata...
*  there are "rather good" articles/lists i sv:Wikipedia but they are not just so complete as the registrer I use from the book Tvåkammar Riksdagen se link
      * one sad thin is that sv:WIkipedia dont generate the lists from Wikidata - my guess many people are nit used to databases
* examples of good lists 
     * [Lista över ledamöter av Sveriges riksdags andra kammare 1929–1932](https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_ledam%C3%B6ter_av_Sveriges_riksdags_andra_kammare_1929%E2%80%931932)
     * "valkrets" --> [Västra Götalands läns södra valkrets](https://sv.wikipedia.org/wiki/V%C3%A4stra_G%C3%B6talands_l%C3%A4ns_s%C3%B6dra_valkrets)
### WD missing PM

1. Ernst Göransson is SPA [sj9PGLAlnmUAAAAAABgbEw](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABgbEw)
   1. He was on an [ambiguation page](https://sv.wikipedia.org/wiki/Ernst_G%C3%B6ransson) see Google search in [video](https://www.youtube.com/watch?v=GOAEUV7JPdw)
   
   <img width="803" alt="image" src="https://user-images.githubusercontent.com/14206509/223590503-f2f4f63e-c1bd-4720-ab95-b25f554e6db0.png">  
       
   [<img width="1084" alt="image" src="https://user-images.githubusercontent.com/14206509/223590816-2ba30f58-59e6-4612-bfe7-1e0f5a741836.png">](https://sv.wikipedia.org/wiki/Special:L%C3%A4nkar_hit/Ernst_G%C3%B6ransson_(1887%E2%80%931959))
   
    1. [Links to the not created page](https://sv.wikipedia.org/wiki/Special:L%C3%A4nkar_hit/Ernst_G%C3%B6ransson_(1887%E2%80%931959))
    
  * [Lista över ledamöter av Sveriges riksdags andra kammare 1925–1928](https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_ledam%C3%B6ter_av_Sveriges_riksdags_andra_kammare_1925%E2%80%931928) ‎ 
  * [Jönköpings läns valkrets](https://sv.wikipedia.org/wiki/J%C3%B6nk%C3%B6pings_l%C3%A4ns_valkrets) ‎
  * [Ernst Göransson](https://sv.wikipedia.org/wiki/Ernst_G%C3%B6ransson) ‎ 

    3. I created him as WD [Q117011372](https://www.wikidata.org/wiki/Q117011372?uselang=sv) see also [pictures on commons](https://commons.wikimedia.org/wiki/Category:Ernst_G%C3%B6ransson_1887)
    [<img width="733" alt="image" src="https://user-images.githubusercontent.com/14206509/223634284-db85c9a0-958b-425d-b6b6-f7ebaf0fb3a8.png">](https://commons.wikimedia.org/wiki/Category:Ernst_G%C3%B6ransson_1887)    
    
4. **Done** Otto Johansson se [video](https://youtu.be/qRR-KO_XJWQ)
   1. **YES** was in WIkidata but **wrong linked in sv:Wikipedia on 2 pages** 
        1. [Västra Götalands läns södra valkrets](https://sv.wikipedia.org/w/index.php?title=V%C3%A4stra_G%C3%B6talands_l%C3%A4ns_s%C3%B6dra_valkrets&diff=52059429&oldid=51404007)
        2. [Lista över ledamöter av Sveriges riksdags andra kammare 1929–1932](https://sv.wikipedia.org/w/index.php?title=Lista_%C3%B6ver_ledam%C3%B6ter_av_Sveriges_riksdags_andra_kammare_1929%E2%80%931932&diff=prev&oldid=52059406)
        
6. **Done** Herman Smedh [video](https://youtu.be/rtYIRWyeqM4)
    1.  Wikidata [Q117018060](https://www.wikidata.org/wiki/Q117018060)
    2. Was mentioned in sv:Wikipedia 
        1. [Dalarnas_läns_valkrets](https://sv.wikipedia.org/wiki/Dalarnas_l%C3%A4ns_valkrets)    
        2. [Lista över ledamöter av Sveriges riksdags andra kammare 1925–1928](https://sv.wikipedia.org/wiki/Dalarnas_l%C3%A4ns_valkrets)

**Comment by MansMeg** [comment]
Thanks @salgo60 ! Do we know which people are missing or should we just add them as we find them?

Could you also add Herman Smedh? I have a vague memory that you said that you would be happy to add people that are missing and we find. Let me know if that is not correct.

**Comment by salgo60** [comment]
@MansMeg call me its easier 0735152802

* **My "thruth"** is in the register list of the book [Tvåkammar Riksdagen Q110346241](https://www.wikidata.org/wiki/Q110346241)  I created from the PDF see [WD Register över riksdagsmannabiografier band 1-5.txt](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/WD%20Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt)
  * I am slowly walking through the list and clean Wikidata, I add the Qnumber to that list when I have touched it
     * example [todays change](https://github.com/salgo60/Wikidata_riksdagen-corpus/commit/f6e10a897573e78f114c475b867c1a1b0020266e)
     
     [<img width="1034" alt="image" src="https://user-images.githubusercontent.com/14206509/223656770-fc683ab9-30cb-40ae-9fb3-22a559920d25.png">](https://github.com/salgo60/Wikidata_riksdagen-corpus/commit/f6e10a897573e78f114c475b867c1a1b0020266e)     
     
2. We also have all the list in sv.Wikipedia I have thought of checking them writing a program but I trust the book much more...
3. I guess we also can use what they have done in Riksarkivet SBL as they have classified a person as a Riksdagsman
4. When I touch a person I also add if it in [Tvåkammar Riksdagen Q110346241](https://www.wikidata.org/wiki/Q110346241) article says that a father was a Swedish PM in [Member of the Riksdag of the Estates Q](https://www.wikidata.org/wiki/Q82697153)....

**Comment by MansMeg** [comment]
Great! Then this should now be fixed. The second person was apparently incorrectly linked but has now been fixed.

@ninpnin Could you do a rerun toward wikidata and see that we now include these people?

**Comment by salgo60** [comment]
@MansMeg  cc: @miroli @Ainali @SchermanJ

* [X] how WD merge objects
* [X] how we describe conflicting opinions using the [EU RENDER projects](http://render-project.eu/tag/projects/index.html) ideas se example
* [X] How I modell "I Riksdagen kallad" -  we lack dates when it changed....
* [X] example how more parlaments in the world are updated by one user
* [ ] should Wikidata work with welfare-state-analytics then you need persistent identifiers to your data, see [FAIRDATA F1](https://www.go-fair.org/fair-principles/f1-meta-data-assigned-globally-unique-persistent-identifiers/)  and how project [Bionomia works with Wikidata](https://stanford.zoom.us/rec/play/zCW7Zel4sQVeSIgwYL1fAz2E9dytx0_VDdCdKHd2e-CpXQJvS37W-PtohlON9wYLJ3PV_CCH1PR2Kg_s._N9DzHE1blpFqQNL)/[slides](https://www.slideshare.net/DavidShorthouse/ld4-wikidata-affinity-group-shorthouse)

### How WD merge objects -  the last 365 days - 33 times

* [video](https://youtu.be/3hnOW-HN1wo) how to check the merge history for Theodor Berg [Q110548072](https://www.wikidata.org/w/index.php?title=Q110548072&action=history)

* [SPARQL](https://w.wiki/6RBN) merges done for objects connected to the book [Tvåkammar-riksdagen 1867–1970](https://www.wikidata.org/wiki/Q110346241) / [Q110346241](https://www.wikidata.org/wiki/Q110346241)

[<img width="1436" alt="image" src="https://user-images.githubusercontent.com/14206509/223703991-3fbccccc-975d-485f-8f9d-887da4895a87.png">](https://w.wiki/6RBN)

* [SPARQL query](https://w.wiki/6RBL)

[<img width="1436" alt="image" src="https://user-images.githubusercontent.com/14206509/223704169-c6c449ab-47d1-4713-933a-1fc8fdf4ca1c.png">](https://w.wiki/6RBL)


### how we describe conflicting opinions - based on the EU RENDER project
My guess excellent for the Academic world.... If you are [interested FactGrid runs Wikibase](https://database.factgrid.de/wiki/Main_Page) at the Gotha research center I know him [Olaf](https://twitter.com/OlafSimons) / [twitter](https://twitter.com/Factgrid)

* Example Taiwan [Q865](https://www.wikidata.org/wiki/Q865)

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/14206509/223698187-f3319d66-3a8a-4073-942d-74e9a3e1c505.png">

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/14206509/223698318-81ca2f36-6180-40fa-a2b9-d000a9fbe358.png">

### How I modell "I Riksdagen kallad"
In addition to alias I do the following --> we get a source and also can add a sequence -  **we lack a date when it changed**...
* example [Q115870509#P2561](https://www.wikidata.org/wiki/Q115870509#P2561)

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/14206509/223694725-404f801b-e2c9-4a22-814e-0be9ac890a48.png">

* [Q5891896](https://www.wikidata.org/wiki/Q5891896?languse=sv#P2561) = Jonsson i Hov senare Stockholm o åter Hov, Olof, 5:145

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/14206509/223699813-7a8dc8be-f4b0-4aa8-b74a-7a4b3dd55a39.png">

### GITHUB rep that updates PM data
* GITHUB [every-politician-scrapers](https://github.com/every-politician-scrapers) > 200 reps and feeding WD and a project [Wikidata:WikiProject_every_politician](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician)
  * [Sweden related change tracking](https://github.com/every-politician-scrapers/sweden-riksdag-api-current/commits/main)

**Comment by lirrek** [comment]
Hello again! 

I found one MP that has a wiki_id but is not in the "member_of_parliament.csv" data. 
Gustaf Johnsson, Q111804160, 
https://www.wikidata.org/wiki/Q111804160

You can also find him in the "Biografibanden", Band 2, p. 285

In the "name.csv", only his last name is prevalent. In the "alias.csv" both his alias and name are shown.

**Comment by MansMeg** [comment]
Great! Yes, I think this is another bug we probably should fix. My guess is that this person is lacking the role in wikidata. Hence he is included but we dont know about when he is an MP.

I set this up as a separate issue to fix:
#252

**Comment by salgo60** [comment]
**Updated** [Q111804160](https://www.wikidata.org/w/index.php?title=Q111804160&diff=1862957386&oldid=1857446789) with **position held** [P39](https://www.wikidata.org/wiki/Q111804160#P39)

cc: @MansMeg @lirrek

**Comment by MansMeg** [comment]
Great! This means that this will be fixed as soon as we do a new release with updates of wikidata. So I close this issue now.
