### ISSUE TITLE
Error in WD Register över riksdagsmannabiografier band 1-5.txt

### ISSUE THREAD

**Issue by salgo60** [welfare-state-analytics/riksdagen-corpus#255]
@MansMeg 
**Mistake in file [WD Register över riksdagsmannabiografier band 1-5.txt](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/WD%20Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt)** see [correction](https://github.com/salgo60/Wikidata_riksdagen-corpus/commit/25a42768e01a31b3ea0837dddcde9cab23c43331)

* correct
  * Wallmark i Smedsbyn, Nils, 5:444
  * Wallmark i Selånger, Nils Petter, 5:263
* was
  * Wallis i Smedsbyn, Nils, 5:444
  * Wallis i Selånger, Nils Petter, 5:263
  
  From the PDF:Index
  
<img width="765" alt="image" src="https://user-images.githubusercontent.com/14206509/226587657-7be4e5e5-fdfe-4b4c-9b15-f2e93b5472fb.png">

**Comment by MansMeg** [comment]
Great! I removed it now from the list of missing MPs in #249
