### ISSUE TITLE
MP with Wiki_ID, but who is not registered as a MP

### ISSUE THREAD

**Issue by lirrek** [welfare-state-analytics/riksdagen-corpus#256]
Hi! 

Sally Luterkort (Q107639258), is not registered as a MP on Wiki-id and therefore not in the Swerik-data. He was a first chamber MP for Västernorrland and Jämtlands län. 1925-1927. He can be found in “Biografibanden”, Band 5, p.240-241.

**Comment by MansMeg** [comment]
Great! Hopefully we will fix this in the general overhaul we are doing now. Ideally done in the next couple of weeks.

**Comment by salgo60** [comment]
Thanks @lirrek I touched [Q107639258](https://www.wikidata.org/w/index.php?title=Q107639258&action=history&offset=&limit=500) looks like [we miss a good source for birthdate](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABgfnQ)

* pictures [depicting Q107639258](https://view-it.toolforge.org/?q=Q107639258)
* Wiki display tools [Reasonator](https://reasonator.toolforge.org/?q=Q107639258&lang=sv) / [squid](https://sqid.toolforge.org/#/view?id=Q107639258&lang=sv)

[<img width="875" alt="image" src="https://user-images.githubusercontent.com/14206509/227139086-4636b1a6-47f0-4cab-b478-b4bafccdea69.png">](https://w.wiki/6UkZ)

* I [död- och begravningsboken Sundsvalls Gustav Adolfs kyrkoarkiv, Död- och begravningsböcker, SE/HLA/1010190/F/7 (1921-1927), bildid: 00205235_00181, sida 178](https://sok.riksarkivet.se/bildvisning/00205235_00181#?c=&m=&s=&cv=180&xywh=2940%2C3201%2C1143%2C834) it says "Maria Sjukhus" as death place feels vague to then state its deathplace Stockholm
   * OT [We have a rather confused discussion about a new WD property](https://www.wikidata.org/wiki/Wikidata:Property_proposal/place_of_resident_registration_at_death) i.e. to split physical deathplace with were the records are.... more on [sv:Wikipedia](https://sv.wikipedia.org/wiki/Wikipedia:Wikidatafr%C3%A5gor#%C3%85tskilja_d%C3%B6dshemort_och_d%C3%B6dsort?)
   
 OT looks the [police in Norway start look into Knowledge graphs](https://twitter.com/hustveit/status/1638530913595260930) my usecase is combine [DNA and Geneology and KG](https://twitter.com/salgo60/status/1638803483402059776?s=20)

**Comment by MansMeg** [comment]
Great. Then this will be fixed in the next release!
