### ISSUE TITLE
MP with Wiki ID but not in dataset

### ISSUE THREAD

**Issue by lirrek** [welfare-state-analytics/riksdagen-corpus#259]
Hi again! I found another MP with Wiki ID but not connected to the dataset the dataset.

Oskar Samuelson, First Chamber, 1930. Biografibanden Band 1 p.167

Here is the wikidata page: https://www.wikidata.org/wiki/Q117288109

**Comment by ninpnin** [comment]
I think he is in the 'dev' branch:

```
Q117288109,Stockholm
Q117288109,"Stockholm, Per Oskar Samuelson"
Q117288109,1930,1930,Stockholms läns valkrets,förstakammarledamot
Q117288109,Oskar Samuelson,True
Q117288109,Per Oskar Samuelson,False
Q117288109,Samuelson,False
Q117288109,1885-09-23,1947-01-07,man,nan
```

But probably not yet in the published version.

**Comment by MansMeg** [comment]
Great! He will be added in the next version (0.7.1) , see #258 . So hopefully this will be fixed in the next couple of days.

**Comment by MansMeg** [comment]
Done.
