### ISSUE TITLE
Train a domain adapted BERT/RoBERTa for the Swedish parliamentary corpus for curation purposes

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#266]
This include:
- [ ] Handle the vocabulary (remove words that does not exist) and add new common words to the vocab
- [ ] Pretrain it on data
- [ ] Compare the classification accuracy with other Swedish LLMs (GPT-4/ChapGPT)

**Comment by ninpnin** [comment]
Followed in its own repo

**Comment by MansMeg** [comment]
? Why close this?

**Comment by ninpnin** [comment]
@MansMeg we have a dedicated repo for this. The issue(s) can be and should be tracked there.

**Comment by ninpnin** [comment]
In fact, _nothing_ should be tracked here as this repo is about to be archived

**Comment by MansMeg** [comment]
Fair enough. We should though have an issue in the canban board on this.
