### ISSUE TITLE
Add ”Ej biograferade ersättare” to wikidata

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#268]
We should also check these people if they are added in wikidata.

**Comment by salgo60** [comment]
I extracted the page 551 file see [Register över ej biografierade ersättare band 1 02 s 551](https://raw.githubusercontent.com/salgo60/Wikidata_riksdagen-corpus/main/data/Register%20%C3%B6ver%20ej%20biografierade%20ers%C3%A4ttare%20band%201%2002%20s%20551.txt) looks its better to use the data from "inside the book" as then we get party, electoral district, occupation and birth year .... 

* tested a [Open refine reconciliation](https://openrefine.org/docs/manual/reconciling) with Wikidata just using the names-> [test1](https://gistpreview.github.io/?088084a9a334d2866af077223eac321f)

**Example**
<table>
  <tr>
   <th>Wikidata
    <th>Register page 551</th>
    <th colspan=6>Inside book</th>
  </tr>
    <th>
    <th><th>name</th>
    <th>electoral district </th>
    <th>party</th>
<th>born</th>
<th>occupation</th>
<th>substition</th>
<th>comment</th>
  </tr>
    <tr>
   <td><a href="https://www.wikidata.org/wiki/Q117378461">Q117378461</a><td>Ahlinder, Lars-Erik, 2:495 </td>
    <td>Ahlinder, Lars-Erik<td>Örebro läns valkrets<td>m<td>1926<td> ingenjör.<td>Ersättare 1984/85 (16.11-18.12.1984)</td><td>has signed <a href="https://www.riksdagen.se/sv/dokument-lagar/dokument/motion/forbattringar-inom-foraldraforsakringen_G802256">G802256</a> = WD <a href="https://www.wikidata.org/wiki/Q98008664">Q98008664</a> --> he is <a href="https://www.wikidata.org/wiki/Q117378461">Q117378461</a>
  </tr>
<tr>
   <td><a href="https://www.wikidata.org/wiki/Q5544145">Q5544145</a>   <td>Ahlquist, Bengt, 1:523 
   <td>Ahlquist, Bengt<td>Uppsala läns valkrets<td>fp<td>1943<td>informatör<td>Ersättare 1992/93 (8.3-12.4.1993) och 1993/94 {7.2-31.3.1994)
<tr>
  <td>
   <td>Allgulander, Swante, 2:498 
   <td>Allgulander, Swante<td>Västerbottens läns valkrets<td>m<td>1931<td>överläkare<td>Ersättare 1981/82 (12.2-14.3.1982) och 1985/86 (7.5-6.6.1986)
<tr><td><a href="https://www.wikidata.org/wiki/Q107419934">Q107419934</a><td>Andersson, Elisabeth, 2:495<td><td><td><td>1961<td>lågstadielärare.
<tr><td>saknas men finns på <a href="https://sv.wikipedia.org/wiki/Stockholms_kommuns_valkrets">wiki lista</a><td>Andersson, Ingela, 1:519<td>Andersson, Ingela<td><td>vpk<td>1957<td>
Ersättare 1983/84 (26.3-25.5.1984).
<tr><td><a href="https://www.wikidata.org/wiki/Q98415201">Q98415201</a><td>Andersson, Krister, 2:496
<td>Andersson, Krister <td><td>s<td>1959<td>ombudsman<td>Ersättare 1985/86 (8.5-6.6.1986) och 1987/88 (9.11-20.12.1987)
<tr><td><td>Andreasson, Åke, 2:494<td>Andreasson, Åke<td><td>c<td>1927<td>lantbrukare<td>
Ersättare 1980/81 (23.4-23.5.1981).
<tr><td><a href="https://www.wikidata.org/wiki/Q3540867">Q3540867</a><td>Arnholm, Maria, 1:521<td>Arnholm, Maria<td><td>fp<td>1958<td>politisk assistent<td>Ersättare 1987/88 (16.10-15.11.1987)

<tr><td><a href="https://www.wikidata.org/wiki/Q98556988">Q98556988</a><td>Axelsson, Josef, 2:494<td>Axelsson, Josef<td><td>m<td>1921<td>kontorist<td>Ersättare 1977/78 (17.4-3.6.1978) och 1978/79 (20.1-23.2.1979)
<tr><td><a href="https://www.wikidata.org/wiki/Q4937165">Q4937165</a><td>Backberger, Barbro, 1:519<td>Backberger, Barbro<td><td>vpk<td>1932<td>författare<td>Ersättare 1974 (23.3-22.4.1974) och 1976/77
(10.1-11.4.1977)
<tr><td><a href="https://www.wikidata.org/wiki/Q110056640">Q110056640</a><td>Bengtsson, Carl-Olof, 1:525<td>Bengtsson, Carl-Olof<td><td>s<td>1947<td>inspektör
<tr><td><td>Bengtsson, Eva, 2:493<td>Bengtsson, Eva<td><td>m p<td>1928<td>fru<td>Ersättare 1990/91 (15.5-14.6.1991)
<tr><td><td>Bengtsson, Torsten, 1:526<td>Bengtsson, Torsten<td><td>m<td>1929<td>lantmästare<td>
Ersättare 1975/76 (30.10-13.12.1975) och 1976/77 (4.10-10.11.1976).
<tr><td><a href="https://www.wikidata.org/wiki/Q104214628">Q104214628</a><td>Berglund, Märtha, 2:495<td>Berglund, Märtha<td><td>s<td>1943<td>postmästare<td>Ersättare 1990/91 (12.11-11.12.1990)
<tr><td><a href="https://www.wikidata.org/wiki/Q4938501">Q4938501</a><td>Berglund, Nilsson, Mona, 2:494 <td>Berglund Nilsson,Mona<td><td>s<td>1942<td>undersköter­ska<td>RL 1994/95-. Ersättare 1989/90 (16.10-23.11.1989)
<tr><td><a href="https://www.wikidata.org/wiki/Q98271301">Q98271301</a><td>Bernal, Loui, 1:524 
<tr><td><td>Björinge, Jan, 1:521
<tr><td><td>Blom, Erik, 1:527
<tr><td><a href="https://www.wikidata.org/wiki/Q98937885">Q98937885/a><td>Bodén, Lennart, 2:497 
<tr><td><a href="https://www.wikidata.org/wiki/Q117378928">Q117378928</a><td>Bolin, Ingrid, 2:496 
<tr><td><a href="https://www.wikidata.org/wiki/Q98271096">Q98271096</a><td>Bouvin, Ulla, 1:523 
<tr><td><a href="https://www.wikidata.org/wiki/Q117467164">Q117467164</a><td>Brandoné, Anna, 1:526 
<tr><td><td>Brorsson, Anita, 2:498 
<tr><td><td>Budd, Birgitta, 2:496 
<tr><td><td>Burman, Ingrid, 1:523
<tr><td><td>Carlsson, Sivert, 1:525
<tr><td><td>Carlsson, Ulla-Britt, 2:495
<tr><td><td>Cedell, Silwa, 1:526 
<tr><td><td>Corshammar-Bojerud, Anna, 1:526
<tr><td><td>Dahlstrand, Göran, 1:519 
<tr><td><td>Danielsson, Sigrid, 2:495 
<tr><td><td>Davidsson, Inga, 2:496 
<tr><td><td>Duvskog, Ethel, 1:526
<tr><td><td>Edin, Erik, 1:519
<tr><td><td>Edvardsson, Berit, 2:498 
<tr><td><td>Egervärn, Erik, 2:498 
<tr><td><td>Eliasson, Lennart, 2:496
<tr><td><td>Elm, Gunnar, 1:525
<tr><td><td>Eriksson, Billy, 1:519
<tr><td><td>Eriksson, Bror, 1:523
<tr><td><td>von Essen, Anne-Marie, 2:493
<tr><td><td>Fredriksson, Conny, 1:525 
<tr><td><td>Fritzson, Tore, 2:493 
<tr><td><td>Fägersten, Ingrid, 2:495
<tr><td><td>Garstedt, Inge, 1:526 
<tr><td><td>Genitz, Stig, 2:495 
<tr><td><td>Gillberg, My, 1:527 
<tr><td><td>Glansén, Barbro, 2:494 
<tr><td><td>Granath, Elisabeth, 2:495 
<tr><td><td>Gunnarsson, Alvar, 1:525
<tr><td><td>Gunnarsson, Britta, 1:521 
<tr><td><td>Gustavsson, Inger, 2:494 
<tr><td><td>Gylling, Kersti, 1:520
<tr><td><td>Hagberg, Michael, 1:524 
<tr><td><td>Hamilton, Carl-Hugo, 2:496 
<tr><td><td>Hansson, Birgit, 1:524 
<tr><td><td>Hartelius, Ingeborg, 1:526 
<tr><td><td>Hasselgren, Arne, 2:494 
<tr><td><td>Hedberg, Gertrud, 1:520 
<tr><td><td>Hedlund, Margareta, 2:498 
<tr><td><td>Heinemann, Kerstin, 2:496 
<tr><td><td>Hulth, Anna-Britta, 1:524 
<tr><td><td>Häggström, Nils, 2:498 
<tr><td><td>Häll, Christer, 1:524 
<tr><td><td>Harneman, Lars, 2:494 
<tr><td><td>Högström, Kenth, 2:497
<tr><td><td>Högström, Tomas, 2:496
<tr><td><td>Ihrfors, Carl-Johan, 1:520
<tr><td><td>Jarlbäck, Nina, 1:524 
<tr><td><td>Jensfelt, Cecilia, 1:520 
<tr><td><td>Johansson, John, 1:525 
<tr><td><td>Jonback, Margareta, 2:496 
<tr><td><td>Jonsson, Margit, 2:497
<tr><td><td>Karlén, Ingvar, 1:523 
<tr><td><td>Karlsson, Georg, 1:525 
<tr><td><td>Karlsson, Lars-Olof, 2:495
<tr><td><td>Karlsson, Ronny, 1:525
<tr><td><td>Klang, Bengt A, 2:495 
<tr><td><td>Krogvig, Bo, 2:497 
<tr><td><td>Kung, Andres, 1:526 
<tr><td><td>Källman, Birgitta, 1:525
<tr><td><td>Larsson, Anna-Kerstin, 1:526 
<tr><td><td>Larsson, Berit, 2:494
<tr><td><td>Larsson, Ulla-Britta, 2:497
<tr><td><td>Ledin, Bo-Gunnar, 2:498 
<tr><td><td>Lindblad, Göran, 2:494 
<tr><td><td>Lindforss, Hans, 2:497 
<tr><td><td>Lindgren, Anna, 1:524 
<tr><td><td>Ljunggren, Anders, 1:525 
<tr><td><td>Lorentzen, Margareta, 2:493 
<tr><td><td>Lundberg, Kristina, 2:498 
<tr><td><td>Lundblad, Lena, 1:524 
<tr><td><td>Lundqvist, Marianne, 1:522 
<tr><td><td>Löfgren, Ulf, 1:527
<tr><td><td>Löfstedt, Marianne, 2:498
<tr><td><td>Mahl Karlsson, Gerd, 1:525 
<tr><td><td>Mattisson, Thor, 2:494 
<tr><td><td>Mohlin-Erbeus, Berit, 1:526 
<tr><td><td>Modigh, Mait, 1:520 
<tr><td><td>Morfidiakis, Emmanuel, 1:526
<tr><td><td>Nilsson, Karin, 2: 498 
<tr><td><td>Nilsson, Lennart, 2:498 
<tr><td><td>Niva, Vivi, 2:498 
<tr><td><td>Norberg, Elvy, 2:495 
<tr><td><td>Norberg, Gunvor, 2:497 
<tr><td><td>Nordin, Anders, 1:520 
<tr><td><td>Nygren, Carin, 1:524 
<tr><td><td>Nylund, Bengt, 2:497
<tr><td><td>Ohlsson, Thommy, 2:495 
<tr><td><td>Olsson, Birger, 2:497
<tr><td><td>Olsson, Dick, 1:526
<tr><td><td>Olsson, Lars, 1:525
<tr><td><td>Petersson, Lars, 1:526 
<tr><td><td>Pärssinen, Raimo, 2:497
<tr><td><td>Ramsell, Siv, 2:497 
<tr><td><td>Raud, Christina, 2:495 
<tr><td><td>Rignell, John 2:494 
<tr><td><td>Ringholm, Bo, 1:521 
<tr><td><td>Rosengren, Bibi, 1:524
<tr><td><td>Salén, Sven H, 1:522
<tr><td><td>Salzman, Tomas, 2:496
<tr><td><td>Sandberg, Inga, 1:523
<tr><td><td>Sandholm, Conny, 1:524
<tr><td><td>Sidén, Anita, 2:494
<tr><td><td>Sivertun, Ulf, 1:522 
<tr><td><td>Skansen-Thomasson, Sonia, 2:495 
<tr><td><td>Skoglund, Sven 2:493
<tr><td><td>Strand, Melker, 2:494 
<tr><td><td>Stråkander, Anna, 1:524 
<tr><td><td>Svegland, Stina, 2:494 
<tr><td><td>Svensson, Lilian, 1:527 
<tr><td><td>Svensson, Rune, 1:527
<tr><td><td>Svensson, Åke, 1:525 
<tr><td><td>Söderpalm-Berndes, Sten, 2:496
<tr><td><td>Thomé, Karin, 1:522 
<tr><td><td>Thoresson, Arne, 2:496 
<tr><td><td>Thörner, Brivio, 1:525 
<tr><td><td>Torgerson, Susann, 1:524
<tr><td><td>Wadensten, Margit, 2:493 
<tr><td><td>Waidelich, Tommy, 1:522 
<tr><td><td>Vallin, Staffan, 1:527 
<tr><td><td>Wallin, Gunvor, 2:494
<tr><td><td>Wallin, Mariana, 2:496
<tr><td><td>Weibull, Jörgen, 2:494
<tr><td><td>Weinehall, Lars, 2:498
<tr><td><td>Wermelin, Anita, 2:497
<tr><td><td>Wernebrink, Kalevi, 1:526
<tr><td><td>Wernerdal, Bengt, 2:494 
<tr><td><td>Viitamäki-Carlsson, Seija, 2:497 
<tr><td><td>Viitanen, Olavi, 2:496 
<tr><td><td>Vöss-Schrader, Ulla, 1:523
<tr><td><td>Örtendahl, Per Anders, 2:494 
<tr><td><td>Östergren, Karin, 2:497   </table>

**Comment by salgo60** [comment]
@MansMeg we have a [WIkidata chat tomorrow 14:00 local time](https://sv.wikipedia.org/wiki/Wikipedia:Wikitr%C3%A4ffar#Wikidatasnack,_online,_s%C3%B6ndag_9_april) were I will speak with people working more with the Swedish PMs than me how we do this in the best way

* I guess you are "just" happy if you get a Qnumber for each from me.... 
* I think we should have a source that is that chapter in the book so we can find them with a query ...
* and as said earlier a persistant unique identifier to your data objects would be nice so that we can say same as "Värlfärden analyseras" 
  * as I mentioned before I [did a try "same as" Riksarkivet archives #104](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/104) and those archives should also have same as a person in "Värlfärden analyseras" 
  * the process to create Wikidata properties is slow and sometimes never happen because everyone seems t have an opinion
     * a workaround can be that I use a Wikibase were I [have my own instance](https://sweopendata.wikibase.cloud/wiki/Kommuner) and can add same as and have SPARQL federation with WIkidata...

**Comment by MansMeg** [comment]
Hi!
1. Yes. Since we work in an iterative step, that is currently our main priority. Because then we will add this to our quality unit test to check that they are included in our database. Although, I'm not sure how we extract the people and import them into our database. But that is probably something we are going to look into in the next couple of weeks.
2.  That sounds like a good idea. Referring to the pages in the Enkammarbook is what I would do.
3. Yes. I should file this as an issue. We will probably do this when we release version 1.0 of the corpus. There is still quite some back-and-forth going on now.

**Comment by salgo60** [comment]
Please close this if you agree its delivered
* [X] [#115 Create a file with "ersättare" from the book --> then upload to WIkidata ](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/115)

**Comment by MansMeg** [comment]
Does this mean that you have added all the ersättare in wikidata now?

**Comment by salgo60** [comment]
I guess so see [115#issuecomment-1568012110](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/115#issuecomment-1568012110) that was done June 4

<img width="1362" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/e123aa5d-1e9f-457f-ae65-9b868cf4c64d">

## SPARQL with ref books pages for substitutes
* SPARQL [find all people in Volume 1 and page 519-527 - substitute](https://w.wiki/7Tjv)

<img width="1362" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/8beddf20-fbfa-4e36-8f3d-c754fdd8f020">

* SPARQL [find all people in Volume 2 and page 493-498 - substitute](https://w.wiki/7Tju)
<img width="1362" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/b2c3fe8a-7880-4811-9811-d052059cb4e1">

### On my TODO list 2023 sep 
* [ ] walkthrough people in WD that we have as active in First and second chamber and dont have the book "Två kammar Riksdagen" as a source P1433 - is about 340

* did today [Q5813810](https://www.wikidata.org/wiki/Q5813810) / [diff](https://www.wikidata.org/w/index.php?title=Q5813810&diff=1974818422&oldid=1913272079)

<img width="1362" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/051cca11-08a7-42d3-ab72-9694152cd04a">

**Comment by MansMeg** [comment]
Yes! Excellent!

**Comment by salgo60** [comment]
cc: @MansMeg @Lottabrorsson 

We marked some people [P1214](https://www.wikidata.org/wiki/Property:P1214) "no value" --> we think they should be **part of Riksdagens Öppna data** or have GUID [P8388](https://www.wikidata.org/wiki/Property:P8388), let me know if you take an action on that

<img width="871" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/94cc52e4-1ad1-42a1-8075-c47728a55eb8">

* SPARQL list [Riksdagens person-id P1214](https://www.wikidata.org/wiki/Property:P1214) = "no value"  = https://w.wiki/7TwF

<img width="871" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/68ef12c2-bff0-4e5e-9c73-8114672e3cac">

----
* [2019 I meet the people from Riksdagen](https://phabricator.wikimedia.org/T235527#5615454) and we spoke about adding WIkidata id (or Welfare state analytic identifier to the data) no action in this so far but lesson learned is normally it makes sense pointing on each other 
  * see my [Riksdagens "skuggbacklog"](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/50) issue [#63](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/63)
