### ISSUE TITLE
FYI dubletter i WD Register -  Enkammarriksdagen 1971-1993_94 Band1-2 

### ISSUE THREAD

**Issue by salgo60** [welfare-state-analytics/riksdagen-corpus#270]
FYI Fil [WD Register över biograferade riksdagsledamöter och ersättare Enkammarriksdagen 1971-1993_94 Band1-2 _2023_05_04.txt](https://github.com/welfare-state-analytics/riksdagen-corpus/files/11188948/WD.Register.over.biograferade.riksdagsledamoter.och.ersattare.Enkammarriksdagen.1971-1993_94.Band1-2._2023_05_04.txt) har samma person flera ggr: Inget problem när man vet om det jag uppdaterar Wikidata från denna fil [#107](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/107) 

De dubletter jag hittat med [Open Refine](https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine)
<table>
<tr><th>WD Qnummer</th><th>I Riksdagen kallad</th><th>Column 3</th><th>Column 4</th></tr>
<tr><td>Q97155947</td><td>Ahlström i Göteborg</td><td> Inger E</td><td> 2:66</td><td></td><td></td></tr>
<tr><td>Q97155947</td><td>Wickzén i Falkenberg senare Göteborg</td><td> Inger E</td><td> 2:66</td><td></td></tr>
<tr><td>Q21585329</td><td>Berg i Hällefors</td><td> Ulla B</td><td> 2:285 </td><td></td><td></td></tr>
<tr><td>Q21585329</td><td>Samuelsson i Hällefors</td><td> Ulla B</td><td> 2:285 </td><td></td><td></td></tr>
<tr><td>Q5887544</td><td>Dockered i Dockered senare Sjövik</td><td> G Robert</td><td> 2:164</td><td></td></tr>
<tr><td>Q5887544</td><td>Johansson i Dockered senare Sjövik</td><td> G Robert</td><td> 2:164</td></tr>
<tr><td>Q4946778</td><td>Engman i Stockholm</td><td> Barbro B</td><td> 1:68</td><td></td><td></td></tr>
<tr><td>Q4946778</td><td>Engman-Nordin i Stockholm</td><td> Barbro B</td><td> 1:68 </td><td></td><td></td></tr>
<tr><td>Q4971770</td><td>Evermo i Bromma</td><td> Barbro E</td><td> 1:71</td><td></td><td></td></tr>
<tr><td>Q4971770</td><td>Evermo Palmerlund i Bromma</td><td> Barbro E</td><td> 1:71 </td><td></td><td></td></tr>
<tr><td>Q4971770</td><td>Palmerlund i Bromma</td><td> Barbro E</td><td> 1:71 </td><td></td><td></td></tr>
<tr><td>Q4949515</td><td>Gardner i Åkersberga</td><td> K Ingela</td><td> 1:151 </td><td></td><td></td></tr>
<tr><td>Q4949515</td><td>Sundström i Åkersberga</td><td> K Ingela</td><td> 1:151</td><td></td><td></td></tr>
<tr><td>Q4955985</td><td>Hemmingsson i Västerås</td><td> G Margareta</td><td> 2:307</td><td></td><td></td></tr>
<tr><td>Q4955985</td><td>Israelsson i Västerås</td><td> G Margareta</td><td> 2:307</td><td></td><td></td></tr>
<tr><td>Q4955783</td><td>Ingvardsson i Sundbyberg</td><td> Margo</td><td> 1:85 </td><td></td><td></td></tr>
<tr><td>Q4955783</td><td>Sörinder-Ingvardsson i Sundbyberg</td><td> Margo</td><td> 1:85</td><td></td><td></td></tr>
<tr><td>Q4974616</td><td>Rhenman i Stockholm</td><td> Anne</td><td> 1:262 </td><td></td><td></td></tr>
<tr><td>Q4974616</td><td>Sörensen i Stockholm</td><td> Anne</td><td> 1:262 </td><td></td><td></td></tr>
</table>

**Comment by MansMeg** [comment]
Super! Detta ska vi ta med oss när vi bygger vår kvalitetskontroll.

**Comment by salgo60** [comment]
@MansMeg kommer ni att koppla mot Riksdagens Öppna data och uppdatera kontinuerligt
* Jämför repository [every-politician-scrapers](https://github.com/every-politician-scrapers) som jobbar mot > 200 parlament - del av projekt [Wikidata:WikiProject_every_politician](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician)
   * Sverige: [every-politician-scrapers/sweden-riksdag-api-current](https://github.com/every-politician-scrapers/sweden-riksdag-api-current), [Pulls](https://github.com/every-politician-scrapers/sweden-riksdag-api-current/pulls?q=is%3Apr+) / ändring för [5 minuter sedan](https://github.com/every-politician-scrapers/sweden-riksdag-api-current/pull/72/files)
   
----
* FYI detta skickades ut för 5 dagar sedan [från Riksdagens Öppna data](https://forum.civictech.se/t/riksdagens-oppna-data-liten-oversyn/528/3?u=salgo60)
   * vi snackade lite om det [igår på Wikidata fika ](https://sv.wikipedia.org/wiki/Wikipedia:Wikitr%C3%A4ffar#Wikidatasnack,_online,_s%C3%B6ndag_9_april)och intresset är varierande av dom personer som var med om dom skall ge feedback
      * jag [träffade dom 2019](https://phabricator.wikimedia.org/T235527#5615454) men inget hände - då snacka dom om [Eurovoc](https://en.wikipedia.org/wiki/EuroVoc) tror dom gav upp
   * ni borde ha en samsyn med Riksdagens Öppna data vad dom skall leverera.... sedan om dom levererar ller ej är nästa fråga...

**Comment by MansMeg** [comment]
Det är oklart hur kopplingen kommer se ut. Vi kommer ha idn till riksdagens öppna data. Mer än så vet jag inte i dagsläget.

**Comment by salgo60** [comment]
> Det är oklart hur kopplingen kommer se ut. Vi kommer ha idn till riksdagens öppna data. Mer än så vet jag inte i dagsläget.

ha både gamla och nya för personer deras data är lite geggigt och lesson learned är att vissa gamla dokument har fortfarande det gamla jag startade en process för att ta bort det gamla i Wikidata men det var fel tänkt (lesson earned är att det är ofta bra att ha... undantag är Nobelprize där jag lyckats driva igenom att [P3188](https://www.wikidata.org/wiki/Wikidata:Properties_for_deletion/P3188) tagits bort efter 2 års diskussion 🥲  )
* gamla kallar vi [P1214](https://www.wikidata.org/wiki/Property:P1214)
* nya kallar vi [P8388](https://www.wikidata.org/wiki/Property:P8388)
* vid valet 2022 lyckades dom lägga upp dubletter av 3 personer som suttit i EU parlamentet och nu kom in i Riksdagen som några personer på Wikipedia hitta - vårt id [#88](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/88) - ingen feedback om dom löst det på sin sida...

**Comment by MansMeg** [comment]
Vi har haft det problemet också. Vi kör nog, som ni, med båda dessa idn. Sedan får vi acceptera att en och samma person kan ha flera idn just nu.

**Comment by salgo60** [comment]
mm jag har ställt samman massa galenskap jag hittat genom åren på en [Magnus list](https://www.wikidata.org/wiki/User:Salgo60/ExternalIdentifiers) - rekommenderar en kille som plocka upp min lista och höll ett föredrag på stanford.zoom.us - [listan startar vid 27:50 min](https://stanford.zoom.us/rec/play/zCW7Zel4sQVeSIgwYL1fAz2E9dytx0_VDdCdKHd2e-CpXQJvS37W-PtohlON9wYLJ3PV_CCH1PR2Kg_s._N9DzHE1blpFqQNL)

[<img width="1223" alt="image" src="https://user-images.githubusercontent.com/14206509/230898208-c498bca0-c516-4fb7-b65a-a38d2b449f64.png">](https://stanford.zoom.us/rec/play/zCW7Zel4sQVeSIgwYL1fAz2E9dytx0_VDdCdKHd2e-CpXQJvS37W-PtohlON9wYLJ3PV_CCH1PR2Kg_s._N9DzHE1blpFqQNL)

* det som vore snyggt är om ni kan bygga upp ett kvalitetskontroll bibliotek med länkade data så alla vet vilka kontroller olika aktörer har
  * Wikidata skapades av [Denny Vrandečić](https://scholia.toolforge.org/author/Q18618629) efter utflykt till Google är han tillbaka och skapar Wikidata 2.0 som heter [Abstract Wikipedia](https://en.wikipedia.org/wiki/Abstract_Wikipedia) och kommer att ha en del [Wikifunctions](https://en.wikipedia.org/wiki/Wikifunctions) som är ett funktionsbibliotek... --> vore enormt snyggt att ha samma tänk med digital humaniora
* Europeana har ett "[Metadata Quality Assurance Framework for Europeana](https://rnd-2.eanadev.org/europeana-qa/?type=p&fragment=sw&id=206&version=v2020-02&development=#cardinality-score-place)" men tyvärr så lyckas dom inte så bra, jag skrev en [blog om deras problem 2019](http://minancestry.blogspot.com/2020/03/carl-larsson-who-is-that-sadly.html) och även på [#77-4 Strings not things](https://github.com/salgo60/DiggUptime/issues/77#issuecomment-1308635367)
   * min hobby analys är att skall saker som Länkade data lyckas krävs det en annan laguppställning en det vi ser idag på arkiv/museer... det skall vara mer [det tänk vi hade i bankvärlden och semantisk interoperabilitet](https://www.youtube.com/live/GeDXzInR_mA?feature=share&t=990)
   * intressant är att den hobby genalogy site Wikitree som jag [skapade min första WD egenskap 2016](o). Dom kollar varje vecka 22 miljoner profiler mot > [300 regler](https://www.wikitree.com/wiki/Category:DD_Suggestions_Help) --> [exempel veckorapport](https://www.wikitree.com/wiki/Space:Data_Doctors_Report_2023-04-09) / [video regel double entry in Wikidata](https://www.youtube.com/watch?v=D6EIqBtz8Bk)
