### ISSUE TITLE
Add/check mps with missing wikidata ids

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#277]
In issue #265 three mps has been identified as missing. This should be fixed either in the test file or in wikidata.

**Comment by salgo60** [comment]
1. ? @MansMeg do you have the book refs on missing in WD so can I add them I dont find them....
2. FYI: **Work in progress** I am doing a rerun in OpenRefine on the [file](https://github.com/MansMeg/Wikidata_riksdagen-corpus/blob/main/data/WD%20Register%20%C3%B6ver%20biograferade%20riksdagsledam%C3%B6ter%20och%20ers%C3%A4ttare%20Enkammarriksdagen%201971-1993_94%20Band1-2.txt) mentioned #270 
    1. All duplicates in the file that are wrong get **not same as** in Wikidata see [Q5711053#P1889](https://www.wikidata.org/wiki/Q5711053#P1889) --> _ we will maybe later find them with [SPARQL](https://w.wiki/6auS) - see below
1. **Next - not started** The substitutes is next we found in
    1. right now I have a "WD format" see [#111](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/111) and will create a file from the data in the book [#115](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/115) so I can create the WD object using Open Refine in Wikidata

----
Added not same as in WD for "our" duplicates --> [SPARQL will find them](https://w.wiki/6auT) - as long it stays in WD 😺 

[<img width="1260" alt="image" src="https://user-images.githubusercontent.com/14206509/232206303-9f72dc12-740e-4b36-8353-0f9e631a033f.png">](https://w.wiki/6auT)

**Comment by MansMeg** [comment]
1. Unfortunately not. @BobBorges , do you have the refs for the mps missing? Ie name and book/page number? Then we can add them.
2. Im not sure I understand. Are you working with the duplicates in #276 ?

**Comment by BobBorges** [comment]
I do. I'll boot up the computer in a bit.

**Comment by BobBorges** [comment]
- Q00FEL00 Carl B Hasselrot | Hasselrot i Stockholm senare Lundegård | Carl B | 2:278 | 4:231 | i Stockholm senare Lundegård
- Q00FEL00 Sven Hedlund | Hedlund i Göteborg | Sven A | 3:124 | 4:93 | i Göteborg
- Q00FEL00 Hans W Wachtmeister | Wachtmeister af Johannishus i Wambåsa senare Johannishus | Hans W | 3:83 |   | i Wambåsa senare Johannishus

**Comment by BobBorges** [comment]
It would be good, if possible, if we could work with the same catalog / test file so we don't have to clean or reformat data every time there are edits. Most of the time I used working with the files I got from Emil was spent fixing rows with too few or too many commas. Eventually, I also had to replace the separator with ';' because pandas wasn't respecting the quotes around name-iort strings with commas.

**Comment by emla5688** [comment]
Yeah, there are different number of commas primarily due to when the speaker has multiple i-orts, such as 'Ahrland i Stockholm, senare Malmö, ...' which makes it quite tedious to work with. In hindsight it would probably have been easier to use a different separator as you, @BobBorges, mentioned

**Comment by BobBorges** [comment]
I tried first to wrap the strings with commas in quotes, which was good enough for libre office, but not Python for some reason :|

**Comment by MansMeg** [comment]
That was part of the idea of the first task in #265 . It was probably not clear enough by me. The first step is to combine and clean Emils files. Then we store that file in the quality assurance folder in /corpus. Then we can update/correct that file that will be the core file for the unit tests.

**Comment by emla5688** [comment]
Have you looked into re.split(), and if it could be used to resolve the issue?

**Comment by BobBorges** [comment]
@MansMeg Task was clear. I just put it in the wrong folder. @emla5688, I know it, indeed. Cleaning up the data was absolutely no problem & not difficult -- I only mentioned it b/c it will be a waste of time to do that over again, e.g. if there are updates made to those original files you sent me yesterday.

**Comment by MansMeg** [comment]
I agree with @BobBorges here. As soon as we have a first test file in place we should focus on edit that one instead.

@emla5688 we can talk about how to do this monday. But now it is time for you to get deep into git. So you should now work with the same branch and do ev. updates in the file in that branch.

**Comment by MansMeg** [comment]
All MPs now seem to have wikidata IDs
