### ISSUE TITLE
MP Göran Engström 1976-1979 accuracy.  

### ISSUE THREAD

**Issue by JoeNoonan** [welfare-state-analytics/riksdagen-corpus#281]
I am getting the seats from scanned copies of the yearly books förteckning över riksdagens ledamöter. I noticed this oddity where this guy Göran Engström (https://www.wikidata.org/wiki/Q21694244) isn't in any of the books nor in the voting rolls( that I spotted checked these aren't digitized), from 1976-79 when he should be in office. He is also on the Riksdagen website (https://www.riksdagen.se/sv/ledamoter-partier/ledamot/goran-engstrom_0366083752400) for these times.  

May be good to check to see if we can find evidence he was in office in other sources, or if this is an error in the primary source material we should flag.

**Comment by salgo60** [comment]
* [Q21694244#P1343](https://www.wikidata.org/wiki/Q21694244)

[<img width="1093" alt="image" src="https://user-images.githubusercontent.com/14206509/233655368-eaa2f3b9-c805-4e7e-a21e-dd68be0d9ee4.png">](https://www.wikidata.org/wiki/Q21694244)

### [Enkammarriksdagen 1971-1993/94](https://www.wikidata.org/wiki/Q111443541) volume 2 page 331

<img width="180" alt="image" src="https://user-images.githubusercontent.com/14206509/233656976-49caa771-c9da-4701-84a2-884d817fc7bd.png">
<img width="397" alt="image" src="https://user-images.githubusercontent.com/14206509/233656567-4252d6b8-50a3-4d7a-aa6f-0755f9c4f77f.png">

<img width="348" alt="image" src="https://user-images.githubusercontent.com/14206509/233657430-0e774c84-d646-42de-bb66-07d8aa5f6d43.png">

<img width="348" alt="image" src="https://user-images.githubusercontent.com/14206509/233657630-ce3e1c9f-fd2f-4672-ba5b-7972d02c9a67.png">

----
### data.riksdagen.se

* [0366083752400](https://data.riksdagen.se/personlista/?iid=0366083752400&utformat=html)

[<img width="697" alt="image" src="https://user-images.githubusercontent.com/14206509/233655811-38fe2d3a-4e00-4187-98df-2cf6de328e71.png">](https://data.riksdagen.se/personlista/?iid=0366083752400&utformat=html)
----

### www.riksdagen.se/sv/ledamoter-partier/ledamot
* [db1e73e4-1638-4c50-9dbf-73b32a7772f1](https://www.riksdagen.se/sv/ledamoter-partier/ledamot/_db1e73e4-1638-4c50-9dbf-73b32a7772f1)

<img width="979" alt="image" src="https://user-images.githubusercontent.com/14206509/233659258-57f90e53-ca04-437d-9a4d-3d3f603e5812.png">

# SCHOLIA

* [Scholia Q21694244](https://scholia.toolforge.org/author/Q21694244)

First document from the [API is 1991-01-25 link](https://data.riksdagen.se/dokumentlista/?sok=&doktyp=&rm=&from=&tom=&ts=&bet=&tempbet=&nr=&org=&iid=0366083752400&avd=&webbtv=&talare=&exakt=&planering=&facets=&sort=rel&sortorder=desc&rapport=&utformat=htm&a=s#soktraff)

* List of [publications sparql](https://w.wiki/6cRJ) in Wikidata 

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/14206509/233659859-80b6f53a-3bf5-4714-9d26-49a6e443eaf8.png">

* [Co-Author graf Q21694244](https://w.wiki/6cRL)

[<img width="542" alt="image" src="https://user-images.githubusercontent.com/14206509/233660476-77bed380-e86d-45c9-8a8d-e7e1fb962d96.png">](https://w.wiki/6cRL)

**Comment by MansMeg** [comment]
Ok. It seems to be something wrong with riksdagens data then. Do you fix this on wikidata @salgo60? Then I’ll report it to riksdagen.

@JoeNoonan I guess we will update this in the data as soon as possible. But now we know.

**Comment by salgo60** [comment]
?!?!? what is correct and what do we trust? FYI I am on my way out and will be off internet for somedays...

**Comment by MansMeg** [comment]
I think we all would say that we trust the enkammarbook. Or @Lottabrorsson , what would you say in this case. I think this is a clear case of an error in Riksdagens öppna data?

**Comment by JoeNoonan** [comment]
Before @salgo60 posted all this information I found an profile on this guy in the Dala Demokraten, where he mention his career as only being an MP during 1988-1991 period. I think with this level of triangulation it is quite clear that this is an error in Riksdagens öppna data.

![image](https://user-images.githubusercontent.com/28146094/233922679-b74274f1-0797-46e1-9a7f-f327eb6abdad.png)

**Comment by MansMeg** [comment]
Yes. Do you have a reference for this @JoeNoonan, I think a url is sifficient . Wikidata usually solves conflictibg info with refs.

**Comment by JoeNoonan** [comment]
Of course. Here is the paywalled source: https://www.dalademokraten.se/2023-01-04/goran-har-alltid-varit-med-i-kommunstyrelsen--berattar-om-forr-och-nu

Here is the retriever archive link: https://nogo.retriever-info.com/prod?a=6414&d=00934920230104365208121&s=9349&sa=2001208&x=8dc3a1b23cf36eae79529732d85ac44f&tz=Europe/Stockholm&t=1682319724

**Comment by MansMeg** [comment]
Great! @salgo60 is this enough to change in wikidata to the enkammarbook?

**Comment by Lottabrorsson** [comment]
> I think we all would say that we trust the enkammarbook. Or @Lottabrorsson , what would you say in this case. I think this is a clear case of an error in Riksdagens öppna data?

I think so. Maybe there is the other information in "Ledamotsförteckning" and/or "Fakta om folkvalda". I can take look tomorrow and also ask Lars about it.

**Comment by MansMeg** [comment]
Nu är detta rapporterat till Lotta och Lars och jag har tagit bort det som är fel i wikidata. Så förhoppningsvis kommer detta nu bli korrekt. 

Det är en kort period 1982 som nu inte ligger inne i wikidata (andra ersättningsperioden). Om du vill får du lägga in den @salgo60 . Annars får vi plocka den pucken senare. 

Så nu stänger jag denna issue.
