### ISSUE TITLE
MP Karl Rask (Q6063791) name error in metadata/name.csv

### ISSUE THREAD

**Issue by JoeNoonan** [welfare-state-analytics/riksdagen-corpus#284]
I believe the MP Karl Rask (Q6063791) has the incorrect primary name in metadata/name.csv. In the file his name is "Karl Rask Rask"

On Wikidata he is referred to as "Karl Rask": https://www.wikidata.org/wiki/Q6063791

This is also in the enkammarbook;

![image](https://user-images.githubusercontent.com/28146094/234197531-64fa29aa-a73a-4725-99df-25752a3826ba.png)

**Comment by salgo60** [comment]
OT I touched it in [WD](https://www.wikidata.org/w/index.php?title=Q6063791&diff=1882296961&oldid=1867397602) and [sv.Wikipedia](https://sv.wikipedia.org/w/index.php?title=Karl_Rask&diff=52591856&oldid=49228787)

* as he was active when Riksdagens Öppna data is available his [Scholia profile start looking good](https://scholia.toolforge.org/author/Q6063791) --> would be nice if we could load metdata data for **e.g. old parliamentary motions into Wikidata** --> we need persistant identifiers for those documents etc,...

**Comment by MansMeg** [comment]
Great! Then this will be fixed in the next release of the corpus. I close it. Thanks @salgo60 

Yes. Motions are part of the project and will have persistent identifiers.

**Comment by salgo60** [comment]
@BobBorges [this error was added to Wikidata 11 June 2023](https://www.wikidata.org/w/index.php?title=Q6063791&diff=1913291800&oldid=1882296961) ....

<img width="1026" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/7b7baa93-dd92-48ae-a623-9f5a7fcc3111">

**Depends how you use Wikidata you should check for errors like this....**

<img width="1277" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/1ec50627-9782-4ddc-8176-4292b55b4957">

**Action taken** I [did an undo](https://www.wikidata.org/w/index.php?title=Q6063791&diff=1987413996&oldid=1913291800)

<img width="1277" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/c763b6a9-acfc-4541-8607-a3fa23987f09">

<img width="1277" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/51c1ad29-0d7d-45bd-815e-3939a18de5f4">

**Comment by salgo60** [comment]
[Can we trust the rest of the 11 June edits?](https://www.wikidata.org/w/index.php?title=Special:Contributions/BobBorges&target=BobBorges&offset=20230611225406&limit=500)

Best practice is to massupdate in a batch using a tool like Open refine then you can revert all changes

* see my [edit. batch/208142](https://quickstatements.toolforge.org/#/batch/208142)

* [Revert manual mistakes with the EditGroups tool
](https://openrefine.org/docs/manual/wikibase/overview#revert-mistakes-with-the-editgroups-tool)

<img width="1277" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/ca909d04-0039-4871-9d1b-7a01aa413fd6">
