### ISSUE TITLE
Formalize the handling of riksdagar

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#288]
It would be good to map MPs to the riksdagar the attended or were part of. Hence we would probably need to add two csvs in the metadatabase:

1. A riksdagar.csv with one riksdag per line containing information on that specific riksdag
2. A mapping between members_of_parliament and riksdagar as a csv file. Or maybe make the members_of_parliament file to have one row per MP and riksdag?

**Comment by fredrik1984** [comment]
I think Väinö had lists of the specific start/end dates for the different riksmöten. Here is also a wikipedia page that lists all the riksmöten, with specific start/end dates, including such riksmöten as lagtima and urtima: https://sv.wikipedia.org/wiki/Riksm%C3%B6tets_%C3%B6ppnande

**Comment by salgo60** [comment]
[<img width="1383" alt="image" src="https://user-images.githubusercontent.com/14206509/235265677-ed29635c-f6d3-48cb-8c56-f066e0c8f196.png">](https://w.wiki/6dxp) 
* [json](https://query.wikidata.org/sparql?query=%23title%3A%20Riksdagen%20%3E%201867%20Q85680242%20Q10711120%0A%0ASELECT%20%3FWD%20%3FWDLabel%20%3Fstart%20%3Fend%20%3Ffollowedby%20%3Farticle%0AWHERE%0A%7B%0A%20VALUES%20%3Flegislativesession%20%7Bwd%3AQ85680242%20wd%3AQ10711120%7D%0A%20%0A%20%0A%20%20%3FWD%20wdt%3AP31%20%3Flegislativesession.%0A%20%20OPTIONAL%20%7B%3FWD%20wdt%3AP580%20%3Fstart%7D%0A%20%20OPTIONAL%20%7B%3FWD%20wdt%3AP582%20%3Fend%7D%0A%20%20OPTIONAL%20%7B%3FWD%20wdt%3AP156%20%3Ffollowedby%7D%0A%20%20FILTER%20%28year%28%3Fstart%29%20%3E%201866%29%0A%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%3Farticle%20schema%3Aabout%20%3FWD%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AinLanguage%20%22sv%22%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E%20.%0A%20%20%20%20%7D%0A%0ASERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22.%20%7D%0A%20%0A%7D%0AORDER%20BY%20%3Fstart%20%3FWDriksLabel%0A&format=json)
* SPARQL [showing urtima legitima](https://w.wiki/6dxs)

* Later sv:WIkipedia articles also have votes per party using a template [Riksmöte](https://sv.wikipedia.org/wiki/Mall:Riksm%C3%B6te)

[<img width="336" alt="image" src="https://user-images.githubusercontent.com/14206509/235266575-5556c7c4-111d-4845-8071-03eff03f9b38.png">](https://sv.wikipedia.org/wiki/Riksdagen_1972)

* some electoral district has Wikipedia articles with number of votes e.g.[Vadstena, Söderköpings, Skänninge, Motala och Gränna valkrets](https://sv.wikipedia.org/wiki/Vadstena,_S%C3%B6derk%C3%B6pings,_Sk%C3%A4nninge,_Motala_och_Gr%C3%A4nna_valkrets)
   * there is an [Wikipedia API](https://www.mediawiki.org/wiki/API:Main_page) to extract text from Wikipedia articles
      * see also [wikitextparser](https://github.com/5j9/wikitextparser) - "_The purpose is to allow users easily extract and/or manipulate templates, template parameters, parser functions, tables, external links, wikilinks, lists, etc. found in wikitexts._"
   * you can also extract structured data from an [Wikipedia article using OpenRefine](https://schoolofdata.org/2013/07/15/openrefinelodrefine-a-power-tool-for-cleaning-data/) -  [video](https://www.youtube.com/watch?v=cO8NVCs_Ba0)
     
[<img width="506" alt="image" src="https://user-images.githubusercontent.com/14206509/235267031-977ec5d5-04a7-468e-90de-8ed2873f091e.png">](https://sv.wikipedia.org/wiki/Vadstena,_S%C3%B6derk%C3%B6pings,_Sk%C3%A4nninge,_Motala_och_Gr%C3%A4nna_valkrets)

**Comment by fredrik1984** [comment]
see #356

**Comment by BobBorges** [comment]
solved with #355 and #356
