### ISSUE TITLE
Setup a stats and quality plots in the README

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#291]
We want to be able to follow the quality of the corpus and reasonable stats for each new release of the corpus. This is commonly used by people doing research and should be easy to update. Also, old numbers for previous releases should be stored as now with the quality plot. We should probably store and plot the stats both in total and by year since many researchers will cut out some years that are of relevance to them).

Hence, ideally, we would have one stats dashboard and one quality dashboard. Then, we could link to these figures from the project's homepage.

We should add the following plots to the README:

**Corpus information**
(This should probably just be a table).
- [x] The total number of persons in the MP catalogue
- [x] The total number of pages by document type
- [x] The size in Gb of the corpus folder

**Corpus Statistics - Figures**
- [x] Number of documents by type (protocols, motions, government bills etc), year, and corpus version
- [x] Number of pages by type (protocols, motions, government bills etc), year, and corpus version
- [x] Number of MPs by year and chamber (with the actual number of seats as a line - Bobs plot, but more readable)
- [x] The number of speeches by year and corpus version

**Corpus Quality**
- [x] Speech-to-speaker mapping proportion by year and corpus version
- [x] Number of members of parliament by year and chamber as a ratio with respect to the actual number of seats (see paper)
- [ ] The OCR quality (character- and word error rate) by decade and document type (records) - note this is a two-stage sample and needs to be estimated by taking this into account, liam knows more
- [ ] The segmentation error by decennia and document type (records)
- [ ] The segmentation classification error by decennia and document type (records)
- [ ] The number proportion of empty chairs and chairs with multiple persons overlap.

**Comment by salgo60** [comment]
### How WD try to track quality with dashboards see also [Entity Schema](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/129)
Wikidata has a template [Property dashboard](https://www.wikidata.org/wiki/Template:Property_dashboard) for doing that "driven" by SPARQL maybe a candidate to compare with or at least have as a benchmark 

Examples pages with the above dashboard
   * [Wikidata:WikiProject every politician/Statistics](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Statistics) - [history](https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_every_politician/Statistics&action=history&offset=&limit=500) - [1 dec 2019](https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_every_politician/Statistics&oldid=1066858670)
> |selector_sparql=wdt:P106 wd:Q82955
   |grouping_property=P27
   
   * [Wikidata:WikiProject every politician/Sweden](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Sweden)
     *  [WikiProject every politician/Sweden/Coverage by party](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Sweden/Coverage_by_party)
> |selector_sparql=wdt:P39 wd:Q10655178
 |grouping_property=P102
 |properties=P21,P27,P569,P19,P735,P734,P1214,P18
    * [Wikidata:WikiProject every politician/Sweden/Coverage by election](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Sweden/Coverage_by_election) 
> |selector_sparql=wdt:P39 wd:Q10655178
 |grouping_property=P3602   
 
   * [Wikidata:WikiProject every politician/Sweden/Nameforms coverage](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Sweden/Nameforms_coverage)    
>  |selector_sparql=wdt:P39/wdt:P279* wd:Q10655178
  |grouping_property=P39

   * [Wikidata:WikiProject every politician/Sweden/Coverage by party first](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Sweden/Coverage_by_party_first) 
   |selector_sparql=wdt:P39 wd:Q33071890
   |grouping_property=P102
   * [Wikidata:WikiProject every politician/Sweden/Coverage by party second](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Sweden/Coverage_by_party_second) 
>  |selector_sparql=wdt:P39 wd:Q81531912
  |grouping_property=P102
   
   * [Wikidata:WikiProject_every_politician/Sweden/Coverage by party estates](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Sweden/Coverage_by_party_estates) 
> |selector_sparql=wdt:P39 wd:Q82697153
  |grouping_property=P102
   * [Wikidata:WikiProject Sweden/Swedish Riksdag documents/Coverage of commission of inquiry reports](https://www.wikidata.org/wiki/Wikidata:WikiProject_Sweden/Swedish_Riksdag_documents/Coverage_of_commission_of_inquiry_reports)
 > |selector_sparql=wdt:P31/wdt:P279* wd:Q98457443;wdt:P8433 []
|grouping_property=P179

   * [Wikidata:WikiProject Sweden/Swedish Riksdag documents/Coverage of laws by series](url)
  > |selector_sparql=wdt:P31/wdt:P279* wd:Q820655; wdt:P8433 []
|grouping_property=P1433
 ----
 Another good "quality template" is [PositionHolderHistory](https://www.wikidata.org/wiki/Template:PositionHolderHistory)
 * example Swedish prime minister "[statsminister Q687075](https://www.wikidata.org/w/index.php?title=Talk:Q687075)", [Q920108](https://www.wikidata.org/wiki/Talk:Q920108), [Q1749063](http://www.wikidata.org/wiki/Talk:Q1749063).... you find them often on the Talk page if not just add _{{PositionHolderHistory|id=Q1749063}}_ example of less good data [Sveriges kanslipresident (Q10543361)](https://www.wikidata.org/wiki/Talk:Q10543361) **with a lot of warnings**

**Comment by salgo60** [comment]
If number of pictures of a person in the PM are interesting I have created example SPARQL Federation between Wikidata and pictures on Wikicommons that depicts a person in the Swedish PM (P39 wd:Q81531912 wd:Q33071890) see [#133](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/133) more [Dashboard candidates](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues?q=label%3A%22Dashboard+candidate%22+)

### Wikidata Data quality - Grafana dashboard

* Wikidata use Grafana for stats and data quality see example [#40](https://github.com/salgo60/Svenskaforsamlingar/issues/40#issuecomment-1542224031)

[![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/023c60eb-ed7c-4086-9578-3b2d7cafb792)](https://github.com/salgo60/Svenskaforsamlingar/issues/40#issuecomment-1542224031)

**Comment by MansMeg** [comment]
@BobBorges I now updated the issue to be more clear what I think we should include in the README.

**Comment by BobBorges** [comment]
Excellent! Thanks for the direction.

**Comment by BobBorges** [comment]
It seems like github markdown doesn't support any type of variable substitution or file transclusion, so the following strategies would not be possible in the README. 

variable substitution (django template)
```
There are currently {{ number_of_MPs }} in the MP database.
```
or

File transclusion (latex)
```
\subsection{Number of MPs}
\include{number_of_MPs.tex}
```


Do any of you have suggestions about automating dynamic updates to the readme? @MansMeg @ninpnin  Plots are not an issue -- these can be added / updated the same way as the speaker mapping accuracy plot as part of each release cycle. Text / tables are more troublesome. Two options that come to mind:

1. text and tables as images. Problem: text shouldn't be an image as far as I'm concerned
2. storing the main text parts of the readme (sub)sections as separate files and compiling a single readme while concatenating newly generated segments in the appropriate order as part of the release workflow OR the whole readme as a single F-string --> substitute vars and dump to .md. Problem: (a) it's not a very DRY strategy with the readme file (subsections) ending up somewhere as input (b) direct on-the-fly edits to the readme are overwritten on new release

I'm not aware of a markdown parser that could handle reading an md file and updating targeted fragments (like etree for xml or orgparse for .org files). But maybe something like this exists.

I started working with strategy (2), but wanted to put the issue up for discussion before getting too deep into it.

**Comment by MansMeg** [comment]
In R, I can do this with knitr and the kable() function. Then it computes the thing automatically; see here: 
https://bookdown.org/yihui/rmarkdown-cookbook/kable.html

But I'm not sure how to do this in the best way in Python. @ninpnin probably know this better than me. But maybe the Markdown library? It looks mature to me, but unsure if it solves the problem.
https://pypi.org/project/Markdown/
