### ISSUE TITLE
Add i-ort for MPs since 1994/95

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#294]
We have all the i-ort for MPs from 1867–1993/94 from the bio books. After 1993/94, i-ort is basically only used when two MPs have the same name and party at the same mandate period. Still, we should add all existing i-ort to the MP database.

**Comment by BobBorges** [comment]
Was there a defined upper limit of the known_mps_catalog (Emil and Magnus' file) --- 199394?  Latest birth dates are in 1960s. There is an iort for every person in that file, but I just checked two speakers from  a 202122 protocol and they are not in this catalog. Since the catalog is used for quality control, shouldn't we strive to have all MPs in the period for which we have protocols?

**Comment by fredrik1984** [comment]
I think so. All MPs should be in the catalog. @ninpnin do you have any thoughts here?

**Comment by MansMeg** [comment]
Yes. This is just up until 1994. The other iorts we will get from riksdagens öppna data. But I think we take it step by step. Im not sure this is the main priority to fix. So lets leave this as an issue for now.

**Comment by salgo60** [comment]
@BobBorges I have in my backlog for "[ersättare](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues?q=is%3Aissue+label%3Aers%C3%A4ttare+)" [#116](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/115) ----> I guess that will add some people missing in Emils "gold standard file"

* you also have some people active today who are mentioned with the oit name 
   * se wikipedia 
      * [Jonas Andersson i Linköping](https://sv.wikipedia.org/wiki/Jonas_Andersson_i_Link%C3%B6ping)[[2]](https://sv.wikipedia.org/wiki/I_riksdagen_kallad#cite_note-2)[[3]](https://sv.wikipedia.org/wiki/I_riksdagen_kallad#cite_note-3) och [Jonas Andersson i Skellefteå](https://sv.wikipedia.org/wiki/Jonas_Andersson_i_Skellefte%C3%A5)[[4]](https://sv.wikipedia.org/wiki/I_riksdagen_kallad#cite_note-4)[[5]](https://sv.wikipedia.org/wiki/I_riksdagen_kallad#cite_note-5).
      
<img width="1391" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/0534df41-eea4-4fca-868e-5d53f513b876">

* [Notebook checking whats in Riksdagens Öppna data](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/Notebook/iort.ipynb)

**Comment by fredrik1984** [comment]
The important thing, for now, is to have all MPs in the database and some metadata that we need to manage the mapping between MPs in the database and speaker introductions, motions, committee reports etc. 

For this we need name (first name+surname), chamber+time in chamber, i-ort (at least up to 1990), party (this becomes an important category from the 1950s, before that it seems not to be an important category for how MPs are introduced in the parliamentary documents).

Hence, we soon have what the need to start improving the mapping pf speaker introduction and later mapping MPs to motions.

**Comment by salgo60** [comment]
[#141 ](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/141) I created an issue with the iort problems I see in todays data from Riksdagen... and also did a check iort "Riksdagens Öppna data" <-> WD

Let me know if we should have 10 minutes sharing screen and I can show you how Wikidata supports more iort or other related issues.... we have an instance of [Jitsi](https://meet.jit.si/) instance [meet.jit.si/Wikidata-SV](https://meet.jit.si/Wikidata-SV) that I normally use ([same instance used for wikidata sunday informal meetings of some people](https://sv.wikipedia.org/wiki/Wikipedia:Wikitr%C3%A4ffar#Kommande))...

/Magnus Sälgö
0735152802

**Comment by BobBorges** [comment]
This might be trickier than we think. I downloaded 700k rows of open MP data from riksdagen -- of 2171 people in that list, only 17 have a non-empty i-ort :|

**Comment by BobBorges** [comment]
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/6cc6f540-92b5-4bcd-9221-67e1d254d390)

**Comment by salgo60** [comment]
* see [#141](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/141)

**Comment by fredrik1984** [comment]
Well, I don't think this is a really big problem for us. I-ort is not used in the same comprehensive way anymore. We need to ask the library about when they stopped using it for all MPs. My hunch is that it was sometime during the 1990s. Today they use first name + surname + party to distinguish between MPs.

**Comment by MansMeg** [comment]
Then I guess we just check these 17 people and add them as a unit test and we are done with this issue.
