### ISSUE TITLE
Birgitta Sjöqvist (Q117288697) in office before her birth

### ISSUE THREAD

**Issue by JoeNoonan** [welfare-state-analytics/riksdagen-corpus#301]
I believe this is a wikidata issue. Birgitta Sjöqvist (Q117288697) was born on 17 December 1916 but registered as being a member of the second chamber in 1858 to 1860. 

Wikidata here: https://www.wikidata.org/wiki/Q117288697

**Comment by fredrik1984** [comment]
Thanks! The correct year should be 1958–1960. I just changed that in her Wikidata-post.

**Comment by MansMeg** [comment]
Great!
