### ISSUE TITLE
Fix potential duplicate MPs

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#302]
There might be duplicated entries in wiki data where the same person occurs multiple times. I think the unit test will capture this by going through the number of MPs daily in the parliament. However, I file this issue here to do a check.

@ninpnin You found an example of such a duplicate. Could you add it to this issue as an example?
EDIT: Not needed @JoeNoonan gave an example.

**Comment by JoeNoonan** [comment]
I just found a duplicate. Gunnar Olsson i Edane.

There are two entries, both with the same birthday. 

https://www.wikidata.org/wiki/Q97061982

https://www.wikidata.org/wiki/Q110994286

Q97061982 seems to have more information.

**Comment by MansMeg** [comment]
Great! @salgo60 How do we fix these duplicates in the best way. Is it possible to merge them?

**Comment by salgo60** [comment]
@MansMeg @JoeNoonan  merged done. [Q97061982](https://www.wikidata.org/w/index.php?title=Q97061982&uselang=en&diff=1902457325&oldid=1884174562) ✅ 

<img width="1385" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/66752bc0-a37a-4914-8a06-22a0ad68c14a">

* [video](https://youtu.be/LQObtLq6Ppo)

**Comment by MansMeg** [comment]
Great! Thanks for the video. That might come in handy later on!
