### ISSUE TITLE
Add missing replacer MPs (ersättare) and MP metadata to Wikidata (from Joe's list)

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#305]
Joe Noonan has discovered 45 MP replacers (ersättare) with missing Wikidata-id or missing important metadata (chamber, dates in parliament, etc). He has created a nice CSV file of these MPs (attached here). In the column "ers_name_from_text" you find the MP replacer and in the column "mp_name" you find the (ordinarie) MP that is being replaced. 

According to Joe, these 45 MP replacers were not found in our current Github .csv metadata file. @BobBorges can you check this? These 45 MPs seem to be in the bio books (in the list at the end, "Register över ej biograferade ersättare").

@salgo60: would it be possible for you to add these MPs to Wikidata + add relevant metadata? 

[missing_replacements_1974_1993.xlsx](https://github.com/welfare-state-analytics/riksdagen-corpus/files/11567118/missing_replacements_1974_1993.xlsx)

**Comment by salgo60** [comment]
Yes I can add it and I have it in my backlog to add them but if you have a csv file its easier....

I am out on a 2 days short kajak trip so I check status when I am back

![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/81a512b6-ea4b-4ace-8cea-3c4432632cc3)

**Comment by MansMeg** [comment]
Ok. We have fixed alot in the current PR with MP additions. These might have been fixed there. Hence, this might already have been fixed in this PR. This is the reason why we need quick release cycles. 

@BobBorges Do you think we will be able to fix this PR and release it tomorrow?

**Comment by MansMeg** [comment]
Ah. I now saw that this us stuff we want to use for the replacement roles and including this in our metadata.

**Comment by BobBorges** [comment]
There are a few outstanding things I like to discuss in the meeting tomorrow relating to the PR; it seems like we haven't introduced bugs, but there's still the issue of carefully checking a sample of diffs and some other things to be fixed per the discussions on Monday along with some of the current issues here.

**Comment by salgo60** [comment]
I have started now see [#115#issuecomment-1568012110](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/115#issuecomment-1568012110)
* step 1 will be just create empty objects --> you get a Qnumber
* then I will try to find more info about the objects

@fredrik1984 the following people I dont find in the books
* Britt Johannesson
* Carl Graf

**Comment by fredrik1984** [comment]
Excellent, thank you @salgo60!

I find both Britt Johannesson and Carl Graf in the bio books. I attach a screenshot of each here. I think Graf is Carl Fredrik Graf.

![Skärmavbild 2023-05-30 kl  13 43 44](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/15212990/a1bab853-8849-4e23-bb02-2dff8f3f663f)
![Skärmavbild 2023-05-30 kl  13 47 03](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/15212990/b84513d2-7654-4a9d-92a8-80d1c60e13f3)

**Comment by salgo60** [comment]
More my old eyes cant find
* Olavi Väitanen

**Comment by fredrik1984** [comment]
His name is actually a Olavi Viitanen, so this is probably an OCR error. 

![Skärmavbild 2023-05-30 kl  14 46 04](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/15212990/c75bcd1d-c138-458b-abde-12bf56983a83)

**Comment by salgo60** [comment]
* Johanesson Bohlin was [Q4939797](https://www.wikidata.org/wiki/Q4939797)

**Comment by salgo60** [comment]
* Britt Johannesson was already in WD [Q4939797](https://www.wikidata.org/wiki/Q4939797) - [graph](https://w.wiki/6muF)

[<img width="926" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/09b69d07-29ef-4c03-b2e7-65346defab74">](https://w.wiki/6muF)

  * [Riksdagen britt-bohlin-olsson_0512357753412](https://www.riksdagen.se/sv/ledamoter-partier/ledamot/britt-bohlin-olsson_0512357753412)

<img width="1057" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/c27826f1-e64f-4530-b3c2-dc4fc00e49c1">

* and I guess she has an article in the book which the people doing the book maybe has missed....

* volume 2 page 163

<img width="190" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/020b76c2-72cc-47d8-8510-ea86fe951593">

<img width="383" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/30150c8a-6fbf-422b-9f42-672a45e2ce80">

<img width="383" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/e28c3e6d-f806-42f2-8b82-507122c0ea3e">

**Comment by salgo60** [comment]
@fredrik1984 version 1 is done [see](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/115#issuecomment-1570084666) 
* [X]  I started with the list but then used the books and added metadata to all the people on the following pages with **no asterisks**
   * [SPARQL find all people in Volume 1 and page 519-527](https://w.wiki/6nn9)
   * [SPARQL find all people in Volume 2 and page 493-498](https://w.wiki/6n6B)

* feedback to "Riksdagens Öppna data" 
   * the [following people gave been found but are missing in Riksdagens data](https://w.wiki/6nda)

**Comment by fredrik1984** [comment]
Thanks! Regarding the people that are missing in Riksdagens data, does this means that they are found in the bio books but are missing in Riksdagens öppna data?

**Comment by salgo60** [comment]
> Thanks! Regarding the people that are missing in Riksdagens data, does this means that they are found in the bio books but are missing in Riksdagens öppna data?

**Yes.....**

Many WD persons has started to use the pattern when something is missing in an external identifier
we have started to use this pattern setting _No Value_

<img width="1153" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/2981cf58-7fe2-4193-8436-3722e7a13582">

<img width="1153" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/7f70e112-9597-4355-934e-debb9aa32e1b">

* "_Något värde_" is used when we know this person has been a substitute but we dont know the name...

<img width="886" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/8c824262-ab97-4950-8305-199c38ff9ec1">

**As said I just** walked through the substitute pages and added those without an asteriks

----
### What can we trust

1. Riksdagens data has sometimes text strings for substitute but that is rather easy to "translate" into a WD object for the person [#60](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/60)
2. Robin WD user [Popperipopp](https://www.wikidata.org/wiki/Special:Contributions/Popperipopp) has added many BUT I have added the source "[Enkammarriksdagen 1971-1993/94](https://www.wikidata.org/wiki/Q111443541) / [Q111443541](https://www.wikidata.org/wiki/Q111443541)" --> We can do [SPARQL all from the book Enkammarriksdagen 1971-1993/94 / Q111443541](https://w.wiki/6mvr) ( **OBS** many are missing)

<img width="886" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/a9ffe6ad-2675-4742-83ee-1684229430ef">

3. We can rather easy Google search and find documents at Riksdagen that states a person is substituted
example:

>  [G80958](https://data.riksdagen.se/dokument/G80958)
> Uppdraget som ersättare hade därigenom upphört för Gerd Mahl Karls­son, Lars-Erik Ahlinder, Torgny Larsson, Per Arne Aglert och Bror Eriksson (svenska)
> [Riksdagens protokoll 1984/85:58](https://www.wikidata.org/wiki/Q98490259) / Q98490259

4. I have also found that Wiki articles like [Fyrstadskretsen](https://sv.wikipedia.org/wiki/Fyrstadskretsen) tells substitutes but has no source (not used by me)

<img width="886" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/e8c4efb7-8fc4-4f77-a661-34166d7259c3">

### Should Riksdagens Open Data be outside this loop?
Feels odd that we dont report things back to [Riksdagens Öppna data see #149](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/149)

**Comment by MansMeg** [comment]
I guess this has now been fixed and can be closed?

Re your question on Riksdagens öppna data, that is a separate issue we will do as a quality control, i.e. look at differences between RÖD and our MP database.

**Comment by salgo60** [comment]
I have done the WD part and added an issue to Riksdagens "skuggbacklog" [#158](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/158)

**Comment by MansMeg** [comment]
Excellent!
