### ISSUE TITLE
Speaker identification script update assigns known speaker as unknown

### ISSUE THREAD

**Issue by liamtabib** [welfare-state-analytics/riksdagen-corpus#307]
We have an issue of identified speakers being categorized as 'unknown' after fuzzy matching speakers.

This includes the diffs, where the first line is before and second line is now:
---
-          <u who="Q3162739" xml:id="i-85b579d271a7af35-3" prev="i-85b579d271a7af35-0">
+          <u who="unknown" xml:id="i-85b579d271a7af35-3">
---
-          <u who="Q3162739" xml:id="i-e4d0499bf5d06298-13" prev="i-e4d0499bf5d06298-0">
+          <u who="unknown" xml:id="i-e4d0499bf5d06298-13">
---
-          <u who="Q3162739" xml:id="i-8d48b869646538b8-27" prev="i-8d48b869646538b8-25">
+          <u who="unknown" xml:id="i-8d48b869646538b8-27">
---
-          <u xml:id="i-4ayVM75tu4cfAdCtoBtXmJ" prev="i-0bd353fe75fb9a6b-0" who="Q3162739">
+          <u xml:id="i-4ayVM75tu4cfAdCtoBtXmJ" who="unknown">
---
-          <u who="Q3162739" xml:id="i-74e11d3923e9e582-12" next="i-41bb1ddd84febd4c-30">
+          <u who="unknown" xml:id="i-74e11d3923e9e582-12">
---
-          <u who="Q3162739" xml:id="i-7d75fdb63351bebf-31" next="i-WT84G6GQBK1ihCNxzQoF1Y">
+          <u who="unknown" xml:id="i-7d75fdb63351bebf-31">
---
-          <u who="Q5789491" xml:id="i-1923ca51c0b4eb00-8" prev="i-1923ca51c0b4eb00-7">
+          <u who="unknown" xml:id="i-1923ca51c0b4eb00-8">
---
-          <u xml:id="i-f0a7702322ac1583-929" prev="i-f0a7702322ac1583-922" who="Q97971246">
+          <u xml:id="i-f0a7702322ac1583-929" who="unknown">
---
-          <u xml:id="i-f0a7702322ac1583-930" prev="i-f0a7702322ac1583-922" who="Q97971246">
+          <u xml:id="i-f0a7702322ac1583-930" who="unknown">
---

**Comment by MansMeg** [comment]
Could you add the ids also. Ie copy the text from the hit diffs?
