### ISSUE TITLE
v0.9.0: Inconsistent use of attributes in <pb> tag?

### ISSUE THREAD

**Issue by roger-mahler** [welfare-state-analytics/riksdagen-corpus#309]
N.B. This might be by design.

The "n" and "facs" attributes of the `pb` attribute have a somewhat varying usage in the corpus:

Protocol `prot_1871__ak__0121.xml` has both `n` and `facs` attributes:

```xml
<pb n="0" facs="https://betalab.kb.se/prot-1871--ak--0121/prot_1871__ak__0121-000.jp2/_view"/>
```

Protocol `prot_1921__ak__12` has only `facs` attribute:
```xml
<pb facs="https://betalab.kb.se/prot-1921--ak--12/prot_1921__ak__12-000.jp2/_view"/>
```

Protocol `prot-202021--7.xml` has source URL in `n` attribute and no `facs` attribute:
```xml
  <pb n="http://data.riksdagen.se/fil/5F7468FD-7275-4675-8413-C2C995E75DB8#page=2"/>
```

**Comment by MansMeg** [comment]
@ninpnin This sounds strange. How should it be? Also, maybe we should add this to the schema? Does ParlaClarin have this or is it stuff we have added?

**Comment by ninpnin** [comment]
'n' should be 'facs' in all cases. Should be an easy fix

**Comment by ninpnin** [comment]
<img width="699" alt="Screenshot 2023-05-31 at 15 50 13" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/10169469/589ac4a3-032b-4e8b-a114-b5dc0ccb30e3">

The root cause seems to be fixed, however we should fix the remaining errors.

**Comment by MansMeg** [comment]
Great! Could you fix this and setup a PR with a random sample of edits? I can do a quick QC?

**Comment by BobBorges** [comment]
Open PR #357
