### ISSUE TITLE
Update README for metadata

### ISSUE THREAD

**Issue by JoeNoonan** [welfare-state-analytics/riksdagen-corpus#310]
README.md on the metadata github is out of date. i.e. party_affiliation.csv is described as only having two variables person_id and party when it actually has wiki_id , start, end, party, and party_id . It also mentions that the member_of_parliament.csv contains party data when it does not.

**Comment by MansMeg** [comment]
We should also update with the decisions made on the data, ie. [#358](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/358)
