### ISSUE TITLE
Alfred Malmström i Vissefjärda

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#314]
I have a hard time knowing if this is the same or different persons? @salgo60 , do you know?
Q5974194 | Malmström | P Alfred L | Vissefjärda
Q5974292 | Malmström | T Alfred | Vissefjärda

**Comment by fredrik1984** [comment]
They are different persons:

<img width="682" alt="Skärmavbild 2023-06-02 kl  14 41 29" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/15212990/bdf2b4b6-a9ca-45db-bf03-6ea460e8a137">

**Comment by MansMeg** [comment]
Great! Thanks @fredrik1984

**Comment by salgo60** [comment]
Its father and son [graph](https://w.wiki/6nRe) so they share 50% of the DNA I guess [owl:DNAnearlysameAs](https://www.w3.org/2009/12/rdf-ws/papers/ws21) och ligger i [samma grav](https://gravar.se/forsamling/emmaboda-pastorat/vissefjarda-kyrkogard/c/thure-alfred-malmstrom-99874) [owl:LocationnearlysameAs](https://www.w3.org/2009/12/rdf-ws/papers/ws21);-)

<img width="1052" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/1d5ee029-046a-483a-8d91-0c3b9d974518">
