### ISSUE TITLE
Duplicates in the known MP catalog

### ISSUE THREAD

**Issue by BobBorges** [welfare-state-analytics/riksdagen-corpus#316]
There are no duplicate rows, but a number of wiki IDs appear multiple times. There are name differences and some entries with different references. Should we merge these somehow?
[duplicated_known-mps.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/11715541/duplicated_known-mps.csv)

**Comment by MansMeg** [comment]
Can you give an example? Im not sure I follow?

**Comment by BobBorges** [comment]
Fredrik linked this issue in #342, so I'd just ask for clarification here. Do we want to do anything with these instances of wiki_ids that appear more than once in the  known_mp_catalog?

@MansMeg All the examples are attached to the original post. No duplicate rows, in the sense that every cell in the row is identical, but we get people appearing with different names and/or iort, or some with same info but different page reference in the bio-books.

**Comment by MansMeg** [comment]
Ok. So no duplicates of persons, only names and iort duplicates? Thos make sense, different spellings of a name, changed names etc. Or?

**Comment by BobBorges** [comment]
> So no duplicates of persons, only names and iort duplicates?
 
I'm not sure I follow what you mean? There are no exact duplicate rows.  People who have name changes/iort changes are sometimes listed twice (one row per name variant / iort). Similarly, some people have references in different volumes of bio books -- I think most have the references grouped together in one row, but some get additional rows for biobook reference.

**Comment by MansMeg** [comment]
Different name variants and iort variants are not duplicates, right. Its just that the person have multiple names and/or iorts? The same with multiple book references. This might correctly exist, right? I guess a duplicate is two rows with the exact same information, i.e. two wikidata_ids with the exact same information?

**Comment by BobBorges** [comment]
> two wikidata_ids with the exact same information?

no such duplicates

**Comment by MansMeg** [comment]
Ok. So then we can close this issue I guess?

**Comment by fredrik1984** [comment]
> The same with multiple book references. This might correctly exist, right? 

Just to confirm: yes – the same person can be referenced in different places in the bio books since an MP can change constituency and thus be in different constituency parts of the bio books.
