### ISSUE TITLE
Mistakes (?) in the known MPs catalog

### ISSUE THREAD

**Issue by BobBorges** [welfare-state-analytics/riksdagen-corpus#317]
Working through the missing i-ort, I found some issues in the known MPs catalog. These ought to be sorted out in our catalog.

* [x] 9    | FEL(Q5711044) | Enander | S Johan | Lillhärdal | (4:220), 5:294 | References refer to two people
* [x] 13  | FEL(Q16945247) | Gustafsson | T D M Axel | Jönköping | (4:226), 2:155 | References refer to two people
* [x] 14  | FEL(Q16945247) | Gustafsson | T D M Axel | Lindesberg | (4:226), 2:155 | References refer to two people
* [x] 89   | FEL(Q5820900) | Jansson | P A Julius | Hanåsa | 2:281 | Something wrong with surname
* [x] 245 | FEL(Q6020574) | Olauson | Daniel | Västerås | (1:153,   4:131,) 1:447 | ID and pages are for carl Nystrom I stockholm

**Comment by MansMeg** [comment]
The top three, I dont really follow? Is it multiple persons with the same iort?
Is 245 incorrect in our database (ie the mapping is incorrect)?

Re 89, is it error at our end or at wikidata?

**Comment by BobBorges** [comment]
9 for example:

The wiki ID is almost the right name Anders Johan Enander @ 4:220, a guy born on July 2 1826, but not i Lillhärdal. However reference 5:294 is is Sven Johan Enander i Lillhärdal born on 29 December 1847. These two are also on the duplicate Wiki IDs list in the other issue, so while those duplicates are probably mostly actual duplicates, they might get checked carefully -- The 1847 guy appears not to be in our catalog with the correct birth-day/-year. 

13, 14 were a similar story

89 is PA Julius Högstedt in wikidata

245 I don't find this Olauson i Västerås, but everything else points to Carl Nystrom i Stockholm

I made the issue with tick boxes so I remember to sort them all out transparently for the group and in the best way possible.

**Comment by fredrik1984** [comment]
Good that you spotted these, Bob!

9 – should be this guy: https://www.wikidata.org/wiki/Q5711053. Still, https://www.wikidata.org/wiki/Q5711044 is also an MP.

13, 14 – should be this guy: https://www.wikidata.org/wiki/Q105086918. Still, https://www.wikidata.org/wiki/Q16945247 is also an MP.

89 – I don't seem to find any MP called Julius Jansson in the bio books. Hence, Julius Högstedt is right, and he is also found in the bio books, https://www.wikidata.org/wiki/Q5820900

245 – there is a Daniel Olausson i Västerås in the bio books: https://www.wikidata.org/wiki/Q6024400

**Comment by MansMeg** [comment]
@BobBorges , could you separate out what is a problem in wikidata? There we might get help from the wikidara people and what is due to an error on our side ie something we beed to fix?

**Comment by BobBorges** [comment]
I think these were issues with our sheet.

**Comment by MansMeg** [comment]
The csv-file you mean? The register from the biobooks?

**Comment by BobBorges** [comment]
exactly. So I will just fix them as I go and these problems should disappear.

**Comment by MansMeg** [comment]
Ah, ok! Great! Sorry for my confusion.
