### ISSUE TITLE
Setup structure to include/connect annotated material to our corpus in a structured fashion

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#32]
In the longer run, I think more and more people would like to include annotated data for the Swedish parliamentary corpus. In the long run 

1. [Natural Language Annotation for Machine Learning](https://www.oreilly.com/library/view/natural-language-annotation/9781449332693/) states that we should keep annotations separate from the main corpus, so probably we need to find a way to make stable connections.
2. We would like to store manually annotation separately from a corpus where we have used predictions based on the manual annotations.

**Comment by ninpnin** [comment]
Deprecated
