### ISSUE TITLE
Help Jan Teorell’s project assign the correct chair to MPs during the 1960s

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#325]
Teorell's project has had some trouble adding MP chair for the 1960s due to how the annual Riksdag registers present this data during that decade. 

This is primarily a task for @BobBorges and @ninpnin to dig into.

Here are some files that we have got from Joe:

[1960s_seats_for_correction (2).xlsx](https://github.com/welfare-state-analytics/riksdagen-corpus/files/11878443/1960s_seats_for_correction.2.xlsx)

[1925_1960_seats_for_correction (1).csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/11878445/1925_1960_seats_for_correction.1.csv)

**Comment by salgo60** [comment]
Do you have good tools? We use [Open Refine](https://openrefine.org/) that has matching functions and excellent integration with [WIkidata](https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine)

<img width="924" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/37bf964c-a4a7-4b18-a302-b41f99280ad2">

----
* **OT 1:** "Funny" that they seems to have invented their own way of naming people not using "[i riksdagen kallad](https://www.wikidata.org/wiki/Q110382440)".... everything just get more crazy...
* **OT 2**  I asked "[KB Tidningsarkivet](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/153)" if they have an API and a linking modell I guess its just texts and they dont use TEI we will see - [link](https://feedback.blogg.kb.se/forums/topic/lankmodell/)
  * guess mapping "Tidningsarkivet" to Swedish PM Then we speak about challenge...
  
  I did a test reconciliation using Open Refine and we got many suggestions but not so many exact matches,... - [video](https://youtu.be/lO29DhXQunk)
  
  <img width="1213" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/9a53f8c5-a234-472d-8029-db8aceff78d6">

**Comment by JoeNoonan** [comment]
I think this is a duplicate of issue #228, I've updated the chair files there.

**Comment by BobBorges** [comment]
> I think this is a duplicate of issue https://github.com/welfare-state-analytics/riksdagen-corpus/issues/228, I've updated the chair files there.

Indeed. Closed as duplicate of #228
