### ISSUE TITLE
Suggestion: keeping track of sources

### ISSUE THREAD

**Issue by BobBorges** [welfare-state-analytics/riksdagen-corpus#326]
I would like to start keeping track of where we get information from. E.g. I construct a unit test for N MPs on a given day from which a protocol was generated and need to look up how many MPs there should have been in Stjernquist 1996. IMO references to these sources should be part of the corpus so that sources of info can be readily findable and verifiable.

Currently, if we take the MP catalog as an example, we all know in the project that those references are to the bio books, but if someone wants to reuse our work, this might not be so obvious what "1:267" refers to.

I suggest a directory with bibtex entries where citation key matches the file name; we use that citation key (+page numbers) when we need to reference a source somewhere in the corpus. This gives us and anyone else a transparent way to know where we get our info.

If that's all agreeable, then the only question is where to keep it exactly? It could be `corpus/sources/`, `corpus/metadata/sources/` or similar.

**Comment by MansMeg** [comment]
I think this is a good idea. I think I have already mentioned this somewhere in another issue (but could not find it). From Emils file we have this information. My suggestion is that we add another csv-file called references.csv or so (in the metadatabase). In this file we have:

person_id;bibtex_id;page

where we include each person in the biobooks, the bibtex_id (I think it is a good idea to use a bibtex solution) with bibtex reference ids (i.e. one ref per volume) and then the page to find this person.

probably then add a bibtex file called references.bib.

This should be quite easy to fix from Emils file is my guess. Is this similar to what you want?

**Comment by BobBorges** [comment]
Yes, it's what I mean. Only my suggestion applies more generally, not only to MPs and the bio books, but for any sources from which we extract information. Now for example, I'm working on that unit test for the correct number of MPs per parliament day and had to look up how many MPs per year, so my csv test file is looking like:

year, chamber, N-MP, source

where "source" is also a bibtex key to an entry in a .bib file for all sources relating to the corpus.

**Comment by MansMeg** [comment]
That is a good idea. Maybe start put it in corpus/references/references.bib since it is references rather than source. I have no strong opinion though.

I would also include party in the unit test as follows:
year, chamber, party, N-MP, reference_id

?

**Comment by salgo60** [comment]
In Wikidata you also get the unique id of the scanned picture in Svensk Poträttarkiv SPA of the article in the book

Example [timeline with link SPA](https://js.histropedia.com/apps/query-timeline/index.html?q=SELECT%20distinct%20?person%20?personLabel%20%28SAMPLE%28?SPA%29%20AS%20?SPA%29%20%20%28sample%28?bild%29%20AS%20?bild%29%20%0A?birth%20?death%20?partyLabel%20WHERE%20%7B%0A%0A%20%20VALUES%20?member%20%7B%0A%20%20%20%20wd:Q33071890%20%0A%20%20%20%20wd:Q81531912%20%0A%20%20%20%20wd:Q82697153%20%0A%20%20%20%20wd:Q10655178%20%0A%20%20%7D%0A%20%20?person%20wdt:P39%20?member;%0A%20%20%20%20wdt:P1343%20?source.%0A%20%20?person%20p:P1343%20?pTva.%0A%20%20OPTIONAL%7B?person%20wdt:P102%20?party%7D%0A%20%20OPTIONAL%7B?person%20wdt:P569%20?birth%7D%0A%20%20OPTIONAL%7B?person%20wdt:P570%20?death%7D%0A%20%20?pTva%20ps:P1343%20wd:Q110346241.%0A%20%20?pTva%20prov:wasDerivedFrom%20%5B%20pr:P4819%20?SPAid%20%5D.%0A%0A%20%20OPTIONAL%20%7B?person%20wdt:P18%20?bild%7D.%0A%20%0A%20%20BIND%28URI%28CONCAT%28%22https://portrattarkiv.se/details/%22,?SPAid%29%29%20AS%20?SPA%29%0A%0A%20%20SERVICE%20wikibase:label%20%7B%20bd:serviceParam%20wikibase:language%20%22sv,en%22.%20%7D%0A%7D%20GROUP%20BY%20%20?person%20?personLabel%20%20?death%20?birth%20?partyLabel%0Aorder%20by%20?partyLabel&md=true&g=article&l=SPA&t=personLabel&s=birth&e=death&i=bild&d=0&c=partyLabel&f=partyLabel&v=t) - still work in progress
