### ISSUE TITLE
Add motions to the corpus

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#328]
I'm unsure I could find this issue in the tracker, so I put it here. We want to add the motions to the corpus based on the discussions in June. This includes:

- [ ] Choose an XML scheme. Here a suggestion is to start with Riksdagens XML schema with additional tags for the text in the motions. We should start with the most simplest solution now and then extend as we need.
- [ ] Re-OCR motions with Tesseract if not already done.  
- [ ] Getting motions into XML scheme. Here we should take a random sample of motions during the whole time period and add a random sample each time.

What content we should annotate in motions are:
- year
- chamber
- motion number (these are found in the title of each motion), 
- motion body text, 
- MP signers of motion (last in motion, if possible in the right order)
- motion intro, 
- MP in motion intro (i.e. main responsible MP for the motion, either one or two MPs), 
- decision points (att-satser), 
- place and dates of the motion (e.g. Stockholm den 3 oktober 2007)

**Comment by salgo60** [comment]
FYI @SchermanJ updated "our OCR issues [#65](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/65#issuecomment-1644623975)" with problems he has found...

**Comment by ninpnin** [comment]
The repo for motions is here: https://github.com/swerik-project/riksdagen-motions

**Comment by MansMeg** [comment]
I think we, for now, should start with keeping the motions in the same repo for multiple reasons:
1) Set a standard for the corpus API
2) We need the mp database for the motions
3) If we separate out the motions we need to separate out the mp database.

so for now I suggest we use one repo for the full corpus.

**Comment by ninpnin** [comment]
We might want to look into [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules), though they have been a bit complicated in my past experience.

**Comment by MansMeg** [comment]
I have thought about that as well. That might be a good long-term solution. Although, I think this is a second step. For now we can keep it together in one repository, I think. As you say, I also find it slightly cumbersome.

**Comment by ninpnin** [comment]
The primary advantage of git submodules to me is the ability to _only_ clone parts of the repo. As the data grows larger, this will make a lot of things a lot smoother. Think only cloning the protocols, metadata, motions or whatnot.

**Comment by MansMeg** [comment]
Yes. Long term, this might be a good idea - I'm still not 100% sure. I think we should discuss this with the tech advisory board. But then we need to move out the different parts of the corpus folder, as well as the protocols and the MP database.

So I suggest we do like this:
1. For now we keep motions in the larger repo
2. We file an issue on the different parts (protocols, motions, mp database) to separate issue and discuss this with the advisory board how to do this in the best way. Git submodules, separate repos etc.

**Comment by fredrik1984** [comment]
see #394 #322

**Comment by ninpnin** [comment]
Let's follow this here https://github.com/swerik-project/riksdagen-motions
