### ISSUE TITLE
Marginal notes are tagged with date

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#335]
We now have a tag that the marginal notes are dates. See the example below. Should we keep this as a date or call it "marginal note"?

```
           </note>
           <pb n="35" facs="https://betalab.kb.se/prot-1900--fk--11/prot_1900__fk__11-035.jp2/_view"/>
          <note xml:id="i-9LEfCGZtUBd4EDB7bd1CCH" type="date">
             N:o II. 36 Tisdagen den 20 Februari..
           </note>
```

**Comment by ninpnin** [comment]
All of these do contain the date of the protocol, and type=date is the parlaClarin way of denoting that.

**Comment by MansMeg** [comment]
Seem like a strange way to annotate dates. This marginal note contain both date and the page number for example.

**Comment by ninpnin** [comment]
I think the other options are a lot worse:
1. Not annotate dates. Then we have no idea where the date metadata comes from
2. Use a lot of resources to split these into multiple paragraphs with high accuracy

**Comment by MansMeg** [comment]
I think neither option is the final option we want to go with. The current semantics is kind of bad. The type is not a date, but the marginal note contain the date. I guess we can find a better way. Although this is far down the priority ladder.

**Comment by ninpnin** [comment]
To me, this is a segmentation error #250
