### ISSUE TITLE
Merged MP Database with MP, name and party affiliation 

### ISSUE THREAD

**Issue by JoeNoonan** [welfare-state-analytics/riksdagen-corpus#339]
For political scientists and other researchers, there is a need for a fully merged dataset with [member_of_parliament.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/corpus/metadata/member_of_parliament.csv), [name.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/corpus/metadata/name.csv), and [party_affiliation.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/corpus/metadata/party_affiliation.csv) merged. Basically, a dataset that has wiki_id, role, name, party, and some sort of time variable (either year or date in and date out). The merge is a bit complex, since not all cases on the parties have start and end dates and can only be matched to the MPs wiki_id for the whole period, while others have start and end dates.

In the Slack there is discussion of creating this as a function within an R package and/or python lib.

**Comment by fredrik1984** [comment]
I think you are totally right. This is a resource the Swerik project should provide.

**Comment by ninpnin** [comment]
@JoeNoonan perhaps this what you want: https://github.com/welfare-state-analytics/riksdagen-corpus/blob/dev/input/matching/member_of_parliament.csv

It is a couple of months old, though.

**Comment by MansMeg** [comment]
We should not point users to stuff that are outside the API. We will not maje any garantuees for that file.

**Comment by BobBorges** [comment]
I'm closing the issue as complete. Indeed, we want to package the merged data for users. I like @ninpnin's idea to just start including this file in each zipped release.

**Comment by MansMeg** [comment]
Can you open an issue on creating a routine to include such a file in releases? Now this issue is closed if we don't have an open issue for this it will be lost.
