### ISSUE TITLE
strange docDates

### ISSUE THREAD

**Issue by mhbodell** [welfare-state-analytics/riksdagen-corpus#34]
There are some docDates that are strange, example files:

                   docname
1  prot-1939-urtima-fk--30
2  prot-1940-urtima-fk--20
3        prot-1942--ak--20
4         prot-1946--ak--9
5        prot-1947--ak--36
6        prot-1947--fk--17
7        prot-1949--ak--15
8        prot-1949--fk--13
9        prot-1950--fk--18
10       prot-1954--ak--22
11       prot-1956--ak--20
12      prot-1958-b-ak--15
13       prot-1962--fk--22
14   prot-1967-höst-ak--52
15   prot-1967-höst-fk--43
16       prot-1968--ak--25
17       prot-1970--ak--19
18          prot-1971--123
19           prot-1974--95

Some of the dates are before 1920 (many of them have more than 1 docDate -- which I don't know what that means).

**Comment by ninpnin** [comment]
AFAIK some of the protocols do span multiple days.

Some of these are erroneous, though. I checked prot-1942--ak--20, which has this block in it, explaining the weird date:

```xml
<note type="date" n="ae09d26c">
    Onsdagen den 27 maj 1912 f. m. Nr 20. 29
</note>
```

the proper date can be seen in another text block in the same protocol:

```xml
<note type="date" n="ac2218ae">
  8 Nr 20. Onsdagen den 27 maj 1942 f. m.
</note>
```

I guess this is an OCR error.

**Comment by ninpnin** [comment]
Fixed so that docDates and the protocol name year can't deviate by over one year.
