### ISSUE TITLE
Problems with metadata updates from wikidata

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#345]
In the discussion of Pull Request #344 we identified four different problems 
1. Incorrect updates used in the mapping algorithm. 
We captured incorrect revisions made by wikidata users in iort (changed correct iorts) using the unit test. However, the mapping algorithms had already been run using the incorrect data. Running some of the  tests before the mapping algorithm might be a solution.
2. New "duplicate" people are being added to Wikidata but are not merged - causing errors in the mapping algorithm
Continuously new people can be added by Wikidata users. This means that when we do the metadata update there can be new duplicates (the same person as multiple wikidata entries). A solution is to list these potential duplicates (new names the mapping algorithm will confuse) with new names/persons the algorithm finds difficult and check them quickly before we run the algorithm.

A potential solution is to structure the metadata updates more than we currently do to capture potential problems more efficiently.

**Comment by BobBorges** [comment]
Re 2, they're not new people, but new attributes or whatever that cause more rows to be created in the input/matching/*.csv files.

**Comment by BobBorges** [comment]
I will try to outline a procedure for updates from wikidata before the next time we do it, hopefully to avoid some of the trouble we ran into this time.

**Comment by salgo60** [comment]
Let me know if WD has errors 

### Add sources when changing values
I saw some earlier edits done by the project in Wikidata without sources....

* [ ] Let me know if we should have a short session where I show you how to add/copy the source to a statement
  * statements without a source in Wikidata are not preferred as the source should confirm what you find in WD and make Wikidata a little bit more trustworthy....
  * 
  
### alias vs. Name

In WD we can just have sources on properties e.g. [change Q5792849 1940037453](https://www.wikidata.org/w/index.php?title=Q5792849&diff=1970487427&oldid=1940037453) on the [Name property](https://www.wikidata.org/wiki/Property:P2561)

![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/fec6d8a5-8a4e-4865-b104-bb20bee2e732)

——
My personal opinion is that the alias field should be used when doing Named Entity Recognition and can contain “all kind” of information compared to the [Name Property P2561](https://www.wikidata.org/wiki/Property:P2561) were we should have sources confirming the values

**Comment by BobBorges** [comment]
In this particular case, it was two individuals in question. My previous edits (with source) were further edited. I put the changes back yesterday.

The edits in question have to do with apparent spelling variants of iort. I don't know myself what the correct variant is, my edits are in line with the spelling in the bio books. If there are sources for the other spelling, then I guess both variants should be on wikidata.

**Comment by MansMeg** [comment]
Yes. But the spelling in the biobooks should be the one that is used when the reference is the biobooks. Right, @salgo60 ?

**Comment by BobBorges** [comment]
That's what i was trying to say - my edits have bio book sources and spelling. If alt spellings will also be entered, they should get their own source.

**Comment by salgo60** [comment]
> Yes. But the spelling in the biobooks should be the one that is used when the reference is the biobooks. Right, @salgo60 ?

Yes as mentioned before
* the book "[Tvåkammar-riksdagen 1867–1970](https://www.wikidata.org/wiki/Q110346241)" has rather often more articles about the same see [> 150 persons](https://gist.github.com/salgo60/d2c594686ea5f2b7d956de95056884c9), [see a small check](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/157)

   *  person that I guess are published at different times --> the book themself will maybe have different ["i riksdagen kallad"](https://www.wikidata.org/wiki/Q110382440) for the same person.... today I only reference a person once even if they are in more articles **which I feel is wrong** see example below. 
      * we also have as a source the book "[Enkammarriksdagen 1971-1993/94](https://www.wikidata.org/wiki/Q111443541)" I dont know if someone has checked if the two books has the same facts.... I guess not ...
       * Riksdagen has a field "**iort**" looks they only can store one value in it.... and I feel normally bad quality data se [#141](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/141)
   * example person with more articles [Q5795740](https://www.wikidata.org/wiki/Q5795740) "Hederstierna i Stockholm senare Västerås" in books 1:436 |  2:158 |  4:92 - **are they identical?** in the below example we can see they dont have the same parties --> we should add all books and see **what facts they confirm** - here is a list of > [150 persons with more articles](https://gist.github.com/salgo60/d2c594686ea5f2b7d956de95056884c9)
        * From the example below we can see that the **naming of parties are not consistent** and its different
            * 1:436 use "skånska p" / "centern" 
               * my try is 
                    * skånska p = [Q10671173](https://www.wikidata.org/wiki/Q10671173)
                    * centern = [Q10411412](https://www.wikidata.org/wiki/Q10411412) not same as [Q10444846](https://www.wikidata.org/wiki/Q10444846) 
            * 2:158 use just centern not "skånska p"
            * 4:92 use "skånska p" and "AK:s center" t
         * **Its very important that we get ONE list of parties** with unique [persistent identifiers](https://github.com/diggsweden/persistent-identifiers-investigation/issues/12) that we think has existed and **what different name strings** are the same parties...
         
#### Volume 1 page 436 - skånska p / centern
        
<img width="364" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/eca05227-d3f0-47c1-b31a-6a27bfc523cb"> <img width="286" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/8b8c8fb4-3af1-4fba-abe6-9ed1a59884b7">    
    
#### Volume 2 page 158 - centern

<img width="393" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/39a9c603-c82f-4972-b607-3136ac925e73">         
<img width="370" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/4d4b2574-76fe-4897-b18a-9ff40d1bd7cc">

#### Volume 4 page 92 - skånska p / AK:s center
        
<img width="367" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/7c732e53-b40b-4c95-a569-3d0d5bc9a72b">
         
         
* there are also other sources for ["i riksdagen kallad"](https://www.wikidata.org/wiki/Q110382440) as the book "[Enkammarriksdagen 1971-1993/94](https://www.wikidata.org/wiki/Q111443541)" 
   * Riksdagen has in its open data a field that only can handle one value see [#141](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/141) - I guess bad quality....

What would be interesting is if we could confirm what is stated in the books with where its mentioned in your corpus and get a better understanding/quality by adding a [Property:P4584](https://www.wikidata.org/wiki/Property:P4584) **"first appearance"** based on your corpus

1. [ ] that every unique combination person Ior get an unique persitent identifier in your corpus
2. [ ] that in the Swedish Corpus you also in the TEI code track when its used and have the persistent idemtifier in the TEI
3. [ ] "we" in wikidata can say that the IoT name is same as Riksdagen-corpus xxx
4. [ ] we could start tracking when all unique IoT are first and lasted used based on your corpus

### Sources
I would also like to see in your data

5. [ ] persistent unique identifiers for every source used ex. books "[Tvåkammar-riksdagen 1867–1970](https://www.wikidata.org/wiki/Q110346241)" should have an unique persistent identifier for every book

## Examples when "[Tvåkammar-riksdagen 1867–1970](https://www.wikidata.org/wiki/Q110346241)" is wrong
* we had today an discussion about Bertha Wellin [Q4895524](https://www.wikidata.org/wiki/Q4895524) and then it looks like both "[Tvåkammar-riksdagen 1867–1970](https://www.wikidata.org/wiki/Q110346241)" and [SKBL](https://skbl.se/en/article/BerthaWellin) **is wrong** see [Diskussion:Bertha_Wellin#WD-mallen](https://sv.wikipedia.org/wiki/Diskussion:Bertha_Wellin#WD-mallen)
* [SPARQL depreciated statements - swedish](https://w.wiki/7SK8) - [english](https://w.wiki/7SKB)
<img width="1420" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/527b9067-53ab-4700-ac96-005b36c393ed">
<img width="1420" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/9ad8308f-18b3-44c3-9e59-ebafeb927702">

   * see same problem with Riksarkivet SBL [#35](https://github.com/salgo60/Svenskaforsamlingar/issues/35)
      * SPARQL WIkidata
          * [birthplace were Riksarkivet SBL is depreciated because of bad quality](https://w.wiki/7SMv)
          * [deathplace were SBL is depreciated because of bad quality](https://w.wiki/7SMw)
          * [depreciated statements with source SBL](https://w.wiki/7SM$)      

## My suggestion step up and use sources and persistent identifiers
* see DIGG project [diggsweden/persistent-identifiers-investigation](https://github.com/diggsweden/persistent-identifiers-investigation/issues/12)
* [ ] create persistent identifiers for all source articles you will reference i.e. if a person has 2 articles that should have 2 persistent unique identfiers 
    * [SPA has scanned most of the articles](https://portrattarkiv.se/advancedsearch;facts=PortraitCatalog:Tv%C3%A5kammar-riksdagen%201867-) but when the person had no picture in the books I feel they didnt scan it....
* [ ] every unique combination ["i riksdagen kallad"](https://www.wikidata.org/wiki/Q110382440) and person should have a persistent identifier
* [ ] all "parties" (and also wrong parties mentioned in the book also that you dont agree with) should have unique persistent identifiers
   * use semantics to say **same as** , [followed by P156](https://www.wikidata.org/wiki/Property:P156), [said to be the same as P460](https://www.wikidata.org/wiki/Property:P460), [merged into P7888](https://www.wikidata.org/wiki/Property:P7888)
* [ ] in the corpus the TEI file should for every ["i riksdagen kallad"](https://www.wikidata.org/wiki/Q110382440) have a same as the persistent identifier you have for the ["i riksdagen kallad"](https://www.wikidata.org/wiki/Q110382440)
* [ ] in Wikidata we should say "same as" your persistent identifiers for every ["i riksdagen kallad"](https://www.wikidata.org/wiki/Q110382440)
* [ ] preferred would be if you had [landing pages](https://unbounce.com/landing-page-articles/what-is-a-landing-page/) that we could link
   * [ ] every person
   * [ ] every ["i riksdagen kallad"](https://www.wikidata.org/wiki/Q110382440)
      * [ ] easy see when used for the first time in the corpus and the last
      * [ ] also easy access the corpus --> we could link it from sv:Wikipedia
* [ ] that we have a 30 minutes walk through how Wikidata and how gadgets works and how we use sources to say this source confirm or in the source we read xxx and translate that to e.g. death reason yyy see [death reasons](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/128)
* [ ] Wkidata related activities
   * [ ] If you start using PIDs **we create a request for a Wikidata property for the welfare-state-analytics project**
      * [ ] if you have a PIDs created we connect them to WIkidata
         * [ ] **Wikidata Swedish PM** <-> welfare-state-analytics
         * [ ] **Wikidata "I Riksdagen kallad"** <-> welfare-state-analytics
         * [ ] **Wikidata "describer by source"**  <-> welfare-state-analytics trusted sources you use see [#324](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/324#issuecomment-1614318328)
         * [ ] **Wikidata "party"** <-> welfare-state-analytics
         * [ ] **Wikidata "position"** e.g. Member of the First Chamber [Q33071890](https://www.wikidata.org/wiki/Q33071890) / Member of the Second Chamber [Q81531912](https://www.wikidata.org/wiki/Q81531912) / Member of the Riksdag of the Estates  [Q82697153](https://www.wikidata.org/wiki/Q82697153) / member of the Swedish Riksdag [Q10655178](https://www.wikidata.org/wiki/Q10655178) <-> welfare-state-analytics
         * [ ] **Wikidata "position minister"** eg. Minister of Trade [Q10686108](https://www.wikidata.org/wiki/Q10686108) list<-> welfare-state-analytics
              * [wd:Q687075](http://www.wikidata.org/entity/Q687075)	Prime Minister of Sweden	
              * [wd:Q920108](http://www.wikidata.org/entity/Q920108)	Minister for Defence	
              *  [wd:Q1749063](http://www.wikidata.org/entity/Q1749063)	Minister for Foreign Affairs of Sweden	
              *  [wd:Q3315958](http://www.wikidata.org/entity/Q3315958)	Minister for Justice	
              *  [wd:Q3612254](http://www.wikidata.org/entity/Q3612254)	Minister for Energy	
              *  [wd:Q4189744](http://www.wikidata.org/entity/Q4189744)	Deputy Prime Minister of Sweden	
              *  [wd:Q4806239](http://www.wikidata.org/entity/Q4806239)	Minister for Nordic Cooperation	
              *  [wd:Q6865819](http://www.wikidata.org/entity/Q6865819)	Minister for EU Affairs	
              *  [wd:Q6865835](http://www.wikidata.org/entity/Q6865835)	Sweden's Minister for Finance	
              *  [wd:Q6865858](http://www.wikidata.org/entity/Q6865858)	Minister for Gender Equality Affairs	
              *  [wd:Q6865890](http://www.wikidata.org/entity/Q6865890)	Minister for Integration	
              *  [wd:Q10430169](http://www.wikidata.org/entity/Q10430169)	Deputy Minister of Employment	
              *  [wd:Q10430171](http://www.wikidata.org/entity/Q10430171)	Deputy Minister of Finance	
              *  [wd:Q10430174](http://www.wikidata.org/entity/Q10430174)	Deputy Minister of Justice	
              *  [wd:Q10497411](http://www.wikidata.org/entity/Q10497411)	Minister for Resource Management	
               *  [wd:Q10541572](http://www.wikidata.org/entity/Q10541572)	Prime Minister of Justice	
              *  [wd:Q10547443](http://www.wikidata.org/entity/Q10547443)	Minister of Municipalities	
              *  [wd:Q10650489](http://www.wikidata.org/entity/Q10650489)	Swedish Government Offices	
              *  [wd:Q10670469](http://www.wikidata.org/entity/Q10670469)	Minister of Primary Education	
              *  [wd:Q10686032](http://www.wikidata.org/entity/Q10686032)	Minister of Employment	
              *  [wd:Q10686038](http://www.wikidata.org/entity/Q10686038)	Minister for International Development Cooperation	
              *  [wd:Q10686041](http://www.wikidata.org/entity/Q10686041)	Minister for Housing	
              *  [wd:Q10686046](http://www.wikidata.org/entity/Q10686046)	Minister of Civil Affairs	
              *  [wd:Q10686108](http://www.wikidata.org/entity/Q10686108)	Minister of Trade	
              *  [wd:Q10686169](http://www.wikidata.org/entity/Q10686169)	Minister for Infrastructure	
              *  [wd:Q10686171](http://www.wikidata.org/entity/Q10686171)	Minister for Domestic Affairs	
              *  [wd:Q10686194](http://www.wikidata.org/entity/Q10686194)	Minister for Rural Affairs	
              *  [wd:Q10686216](http://www.wikidata.org/entity/Q10686216)	Minister for the Environment	
              *  [wd:Q10686220](http://www.wikidata.org/entity/Q10686220)	Minister for Enterprise	
              *  [wd:Q10686247](http://www.wikidata.org/entity/Q10686247)	Minister for Social Affairs	
              *  [wd:Q10686263](http://www.wikidata.org/entity/Q10686263)	Minister for Education and Science	
              *  [wd:Q17103474](http://www.wikidata.org/entity/Q17103474)	Minister for Financial Markets	
              *  [wd:Q18176984](http://www.wikidata.org/entity/Q18176984)	Minister for Culture of Sweden	
              *  [wd:Q18183298](http://www.wikidata.org/entity/Q18183298)	Minister for Migration	
              *  [wd:Q18242897](http://www.wikidata.org/entity/Q18242897)	Minister of Immigration	
              *  [wd:Q18246311](http://www.wikidata.org/entity/Q18246311)	Minister of Democracy	
              *  [wd:Q18246318](http://www.wikidata.org/entity/Q18246318)	Minister for Social Security	
              *  [wd:Q18589764](http://www.wikidata.org/entity/Q18589764)	Minister of Youth Affairs	
              *  [wd:Q18589796](http://www.wikidata.org/entity/Q18589796)	Minister for Consumer Affairs	
              *  [wd:Q19975875](http://www.wikidata.org/entity/Q19975875)	Minister for Information Technology	
              *  [wd:Q19977291](http://www.wikidata.org/entity/Q19977291)	Minister of Taxation	
              *  [wd:Q26659741](http://www.wikidata.org/entity/Q26659741)	Prime Minister for Foreign Affairs	
              *  [wd:Q39074196](http://www.wikidata.org/entity/Q39074196)	Minister for the Climate (Sweden)	
              *  [wd:Q39074295](http://www.wikidata.org/entity/Q39074295)	Minister for Government Coordination	
              *  [wd:Q59392942](http://www.wikidata.org/entity/Q59392942)	Minister of Communications	
              *  [wd:Q83933521](http://www.wikidata.org/entity/Q83933521)	Minister for Terrestrial Defence	
              *  [wd:Q83933561](http://www.wikidata.org/entity/Q83933561)	Minister for Naval Defence	
              *  [wd:Q84566470](http://www.wikidata.org/entity/Q84566470)	Minister of Ecclesiastics	
              *  [wd:Q87748605](http://www.wikidata.org/entity/Q87748605)	Minister of Sports	
              *  [wd:Q93262421](http://www.wikidata.org/entity/Q93262421)	Minister of Economic Affairs	
              *  [wd:Q93270583](http://www.wikidata.org/entity/Q93270583)	Minister of Budget Affairs	
              *  [wd:Q95187493](http://www.wikidata.org/entity/Q95187493)	Minister of Foreign Trade	
              *  [wd:Q95187834](http://www.wikidata.org/entity/Q95187834)	Minister of Health	
              *  [wd:Q95983946](http://www.wikidata.org/entity/Q95983946)	Minister for Higher Education and Science	
              *  [wd:Q105359146](http://www.wikidata.org/entity/Q105359146)	Vice Prime Minister of Sweden	
              *  [wd:Q110820075](http://www.wikidata.org/entity/Q110820075)	Minister of Agriculture	
              *  [wd:Q114734692](http://www.wikidata.org/entity/Q114734692)	Minister of Civil Defence	
              *  [wd:Q114736354](http://www.wikidata.org/entity/Q114736354)	Minister for the Elderly	
              *  [wd:Q114736377](http://www.wikidata.org/entity/Q114736377)	Q114736377	
              *  [wd:Q118352089](http://www.wikidata.org/entity/Q118352089)	Statsministerns statssekreterare	
              *  [wd:Q120737220](http://www.wikidata.org/entity/Q120737220)	Ministry for Rural Affairs
              * list all positions people in WD in First and sec chamber has had [SPARQL](https://w.wiki/7Tc5) - [swedish](https://w.wiki/7TcA)
              <img width="1097" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/35ff99eb-9d53-41d3-a5fb-019e366c8669">

**Comment by BobBorges** [comment]
I like the idea of persistent identifiers. Until then, I think we can solve (close) this issue with a metadata update procedure.


0. start a fresh branch off dev

1. requery metadata
    `scripts/wikidata_query.py` and 'scripts/wikidata_process.py`

2. run `test.db.py` locally
    - will find changed wiki_id
    - will find edits that conflict with our unit test files (someone edits / deletes iort from wikidata)
    
    ---> update wiki_ids in unit test files (I will write a script to do this efficiently)
    ---> address edits on wikidata

3. repeat 1 and 2 until `test.db.py` passes

4. `redetect.py` to remap speakers to intros in protocols

5. run `test.mp.py` locally (other tests?)
    - ensure that everything looks like it works (no stray wiki IDs that aren't in metadata or whatevr)

6. save diff to (an untracked) file
    - this helped me, when I could search the whole diff to give good answers to those looking at the PR
    
7. `sample-git-dif` on protocols
    - mk markdown
    
8. git add *ONLY* sampled protocols
    -commit / push
    -open pr -- post markdown
    
    ---> unit tests will still fail on remote : is ok
    
9. when sampled diffs look ok
    - add /commit /push rest of protocols
    
    - unit tests should pass on remote --> merge
    
The issues last time around would have been spotted and fixed very quickly if I were following this as a guide.

**Comment by MansMeg** [comment]
That sounds like a good solution. Maybe put this in the repo wiki for now?

**Comment by salgo60** [comment]
FYI: We have a suspected duplicate in WIkidata that [I have asked other people for a second opinion](https://sv.wikipedia.org/wiki/Wikipedia:Persondatafr%C3%A5gor#Anders_Andersson_i_K%C3%A4lltorp_samma_person_som_Anders_Andersson_i_Greby) but no feedback yet

* [Q5553916](https://www.wikidata.org/wiki/Q5553916)
* [Q5553949](https://www.wikidata.org/wiki/Q5553949)

<img width="1146" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/542f8f25-11da-4dc3-b360-a0ba00c9964b">

I used [Property:P460](https://www.wikidata.org/wiki/Property:P460) "[said to be the same as](https://www.wikidata.org/wiki/Property:P460)"

<img width="1205" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/7bd3d371-d3cf-409f-9bc7-3c2bfbf5e5f9">

The [sv:Wikipedia article is marked](https://sv.wikipedia.org/wiki/Anders_Andersson_i_K%C3%A4lltorp)

<img width="1205" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/91a728d7-3312-4b77-be6f-d3414362be14">

**Comment by BobBorges** [comment]
> Maybe put this in the repo wiki for now?

done.
