### ISSUE TITLE
Decide on an XML schema for motions

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#348]
We are now having two different solutions on how to store motions and it is not clear which approach is the best one. Below are the two potential solutions.

*The TEI ParlaClarin format*
The TEI parlaclarin is a TEI XML format for structuring and annotating parliamentary protocols.
https://github.com/clarin-eric/parla-clarin/tree/master

Pro:
- We have been working with TEI Parla-Clarin for the records (protokollen).
- There is a community around the schema
- Most of the content we need is already implemented.
- Consistent with the current use of the Parla-Clarin schema for the protocols/records

Con:
- The ParlaClarin format is for storing parliamentary debates, which is a slight mismatch

*The Riksdagen Motion format with additions*
The Swedish parliament already have a format to store motion that is used by the Riksdagens Öppna data. 
https://www.riksdagen.se/sv/dokument-och-lagar/riksdagens-oppna-data/dokument/
Download motions as XML in zip files.

Pro:
- It is simple for the parliament to reuse these old motions by simply remove attributes/tags form the body
- The metadata format is well tested by the parliament already.

Con:
- The current XML format lacks some important information that is needed for research. Hence we would need to add additional tags to the current XML schema.
- We need to do everything ourselves. There are no schemas, there is no format to store the actual content, no tests that we get for free, no knowledge from working with TEI for years, no documentation, no community to rely on.

**Comment by BobBorges** [comment]
> _The Riksdagen Motion format with additions_
>  ... we would need to add additional tags to the current XML schema.

AFAIC this is a significant Con. I guess we'd have to spend significant amount of time to decide what gets included and exactly how.

> _The TEI ParlaClarin format_

Can we use this for motions without adding or otherwise fiddling with the specification? It seems to me like it's ideally suited, so  +1 for TEI ParlaClarin and -1 for the Riksdagen Motion format.

**Comment by MansMeg** [comment]
I'm not sure if the TEI has this in their specifications? @ninpnin might know. My guess is that both schemas require fiddling. Just in different ways. @ninpnin ?

**Comment by BobBorges** [comment]
TEI by itself is probably too generic, but ParlaClarin TEI has a lot of what we need -- [example](https://github.com/clarin-eric/parla-clarin/blob/master/Examples/AkomaNtosoKE-Example.xml). Could you post the photo of the whiteboard after the project meeting where this was discussed? Maybe we could look item by item through the info that we want to encode and see how it would look in ParlaClarin.

**Comment by fredrik1984** [comment]
This is kind of the prioritization of annotating content in motions:
1.	Year, chamber, motion number (these are found in the title of each motion), motion body text, MP signers of motion (last in motion, if possible in the right order)
2.	Motion intro, MP in motion intro (i.e. main responsible MP for the motion, either one or two MPs), decision points (att-satser), place and dates (e.g. Stockholm den 3 oktober 2007)

Here is a photo from the motion workshop in June:

![Unknown](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/15212990/a6e67f30-7c12-4db3-9cb6-dd143c3c80a1)

**Comment by MansMeg** [comment]
The example you showed was for protocols, not for motions?

**Comment by BobBorges** [comment]
Sure. The whole ParlaClarin is about protocols -- from their landing page:

> a TEI customisation for annotating *parliamentary debates*

I have to compare point for point with the photo, but my point is that it seems most if not all what we want to annotate is already implemented in that schema.

**Comment by ninpnin** [comment]
Not only we need to add elements, we need to do everything ourselves. There are no schemas, there is no format to store the actual content, no tests that we get for free, no knowledge from working with TEI for years, no documentation, no community to rely on.

AFAIK, ParlaClarin doesn't add any elements of their own to TEI, they just _define_ what each element type means in the context of parliamentary debates. They do only one part for parliamentary debates that we need to do for motions if we decide to extend the Riksdagen Motion format. The elements, the schemas, etc. come with the TEI package.

**Comment by BobBorges** [comment]
Are we bound to XML?

**Comment by MansMeg** [comment]
I would say yes. We should keep to a few formats as possible.

**Comment by BobBorges** [comment]
Another (last) point from me, which is a pro-parlaclarin / con-riksdagxml is about consistency in _our_ corpus -- to me it would look and feel very strange to have such wildly different formats (shema/no-schema, tagsets, attrubutes, doc organization) within the same corpus.

I'm interested what the tech-advisory board says.

**Comment by MansMeg** [comment]
**Decision made:**
We go with the TEI ParlaClarin format, but test that we can transform the TEI format to the Riksdagen open data XML format so we don't loose any data
