### ISSUE TITLE
List missing parties and fill out in Wikidata

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#349]
We should start filling out parties for those MPs who are currently missing this. We will do that in the following steps:

- [x] @BobBorges updates the file delivered by Lirre to wiki data
- [x] @BobBorges creates a file with the historical MPs that are missing party 
- [x] @BobBorges setup a Google sheet (and share it here) so everyone can help out
- [x] @Lottabrorsson , Mattias, @fredrik1984 , @liamtabib  and others help out to fill out the list with missing parties based on the biobook
- [x] @BobBorges makes an update of the wikidata metadata to the corpus
- [x] @BobBorges include the manually checked parties as a unit test in the corpus (i.e. to check that this has not changed when updating with data from wikidata)

**Comment by salgo60** [comment]
Example odd thing that I marked [depreciated](https://www.wikidata.org/wiki/Help:Deprecation) and [contemporary constraint issue
](https://www.wikidata.org/wiki/Q74557669)

* [Q5813810](https://www.wikidata.org/wiki/Q5813810)

<img width="388" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/18a4971d-70c2-4f87-9665-ab1e050d7c32">

says in [Tvåkammar Riksdagen (h)](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfscA) that I thought was [Högerpartiet Q111033682](https://www.wikidata.org/wiki/Q111033682?uselang=sv) but my understanding is that this name started in 1952 and more correct is [Högerns riksorganisation Q122599272](https://www.wikidata.org/wiki/Q122599272)

**My try in Wikidata**
* [Q5813810?uselang=sv#P102](https://www.wikidata.org/wiki/Q5813810?uselang=sv#P102)

<img width="867" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/8c080c44-88e3-4f27-9f05-39b1a24e4bc6">

----
* see also WD items marked as [Q120143028 Welfare analytics - party](https://www.wikidata.org/wiki/Q120143028) - also explained on issue [#324](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/324#issuecomment-1615690601)

To get something started I mark those WD records were I see a potential problem with [P5008 on focus list of Wikimedia project](https://www.wikidata.org/wiki/Property:P5008) = [Q120143028 - Välfärden analyserad - parti](https://www.wikidata.org/wiki/Q120143028)

[SPARQL list](https://w.wiki/6vqJ) - > 200 items right now

* [Q5813810](https://www.wikidata.org/wiki/Q5813810#P5008) was marked

<img width="871" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/ef44d2a8-7b58-4e94-9e0c-7f3695d80e9f">

**Comment by BobBorges** [comment]
Have we settled on using historical party names? 

On the file I got back from Lirre, a handful of rows have party lmb with party_id:Q110843 and historical_party_id:Q10554125.

**Comment by fredrik1984** [comment]
Yes. We discussed this last Friday. We will focus on adding the actual historical party names. Then researchers can create aggregated party names based on our work. 

However, it might be that we will do something like this anyway. But the priority should be to focus on the empirical data.

**Comment by MansMeg** [comment]
Yes. We should only store the historical data. Ie the party they belonged to for a given date.

**Comment by BobBorges** [comment]
Here's a google sheet with MPs missing at least one party affiliation in our metadata:

https://docs.google.com/spreadsheets/d/1bywraAUEoRy-XPNjfk-7rpMhnQKLJc1EvSQyP3S9GII/edit?usp=sharing

It should be open for anyone with the link, but lmk if any of you have trouble opening it.

**Comment by fredrik1984** [comment]
Excellent! I just asked for permission to edit. I can divide the list between @Lottabrorsson, Mattias, and me.

The principle is to follow the bio books. If a MP never belonged to a party this should also be noted. Also if the MP was a "vilde"

**Comment by BobBorges** [comment]
I've just added columns `start` and `end` (should've been there from the start), so when that info is in the books, pls add it too. And if you find people with multiple affiliations, just duplicate the row and add different parties separately (w/ start/end if possible).

![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/4b29c44c-f800-4149-ac9a-dde3799acbbb)

**Comment by BobBorges** [comment]
> I just asked for permission to edit.

I guess the others also have to do that. I didn't get any notice of this request, so Lotta, Mattias, just DM on slack or email me if I don't grant your permissions within a reasonable amount of time :D

**Comment by fredrik1984** [comment]
Hm, should an MP that does not belong to a party be linked to this: https://www.wikidata.org/wiki/Q327591 ?

I write "no party" in the Google Excel file.

**Comment by MansMeg** [comment]
Whatever is easiest, I think. But @BobBorges might have other thoughts.

**Comment by BobBorges** [comment]
I also wrote "None"  (python friendly) in one of the rows. I don't see any reason to link nothing to something, but others please weigh in here.

**Comment by salgo60** [comment]
> no party

In Wikidata we use "**[no value](https://www.mediawiki.org/wiki/Wikibase/DataModel#PropertyNoValueSnak)**" and add a source  like _Two-Chamber Parliament 1867-1970_. That is a **negative statement** i.e. The source confirm the lack of party value

<img width="895" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/0d3bb0df-345b-4d6c-9216-aeaab79e255b">

see [Q5797559#P102](https://www.wikidata.org/wiki/Q5797559#P102) below

<img width="1337" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/e1d1f71c-6daa-44c2-9d10-970875d4ab31">

* SPARQL 
`?person rdf:type wdno:P102. `

* people with source _Two-Chamber Parliament 1867-1970_.
  * [timeline "party = no value" with link SPA](https://js.histropedia.com/apps/query-timeline/index.html?q=SELECT%20distinct%20?person%20?personLabel%20(SAMPLE(?SPA)%20AS%20?SPA)%20%20(sample(?bild)%20AS%20?bild)%20%0A?birth%20?death%20?partyLabel%20WHERE%20%7B%0A%0A%20%20VALUES%20?member%20%7B%0A%20%20%20%20wd:Q33071890%20%0A%20%20%20%20wd:Q81531912%20%0A%20%20%20%20wd:Q82697153%20%0A%20%20%20%20wd:Q10655178%20%0A%20%20%7D%0A%20%20?person%20wdt:P39%20?member;%0A%20%20%20%20wdt:P1343%20?source.%0A%20%20?person%20p:P1343%20?pTva.%0A%20%20OPTIONAL%7B?person%20wdt:P102%20?party%7D%0A%20%20OPTIONAL%7B?person%20wdt:P569%20?birth%7D%0A%20%20OPTIONAL%7B?person%20wdt:P570%20?death%7D%0A%20%20?pTva%20ps:P1343%20wd:Q110346241.%0A%20%20?pTva%20prov:wasDerivedFrom%20%5B%20pr:P4819%20?SPAid%20%5D.%0A%20%20?person%20rdf:type%20wdno:P102.%20%20%20%23missing%20party%20value%0A%0A%20%20OPTIONAL%20%7B?person%20wdt:P18%20?bild%7D.%0A%20%0A%20%20BIND(URI(CONCAT(%22https://portrattarkiv.se/details/%22,?SPAid))%20AS%20?SPA)%0A%0A%20%20SERVICE%20wikibase:label%20%7B%20bd:serviceParam%20wikibase:language%20%22sv,en%22.%20%7D%0A%7D%20GROUP%20BY%20%20?person%20?personLabel%20%20?death%20?birth%20?partyLabel%0Aorder%20by%20?partyLabel&d=0&md=true&g=article&l=SPA&t=personLabel&s=birth&e=death&i=bild&c=partyLabel&f=partyLabel&v=t) / [people connected with a party (also vilde)](https://js.histropedia.com/apps/query-timeline/index.html?q=SELECT%20distinct%20?person%20?personLabel%20(SAMPLE(?SPA)%20AS%20?SPA)%20%20(sample(?bild)%20AS%20?bild)%20%0A?birth%20?death%20?partyLabel%20WHERE%20%7B%0A%0A%20%20VALUES%20?member%20%7B%0A%20%20%20%20wd:Q33071890%20%0A%20%20%20%20wd:Q81531912%20%0A%20%20%20%20wd:Q82697153%20%0A%20%20%20%20wd:Q10655178%20%0A%20%20%7D%0A%20%20?person%20wdt:P39%20?member;%0A%20%20%20%20wdt:P1343%20?source.%0A%20%20?person%20p:P1343%20?pTva.%0A%20%20OPTIONAL%7B?person%20wdt:P102%20?party%7D%0A%20%20OPTIONAL%7B?person%20wdt:P569%20?birth%7D%0A%20%20OPTIONAL%7B?person%20wdt:P570%20?death%7D%0A%20%20?pTva%20ps:P1343%20wd:Q110346241.%0A%20%20?pTva%20prov:wasDerivedFrom%20%5B%20pr:P4819%20?SPAid%20%5D.%0A%20%20%23?person%20rdf:type%20wdno:P102.%20%20%20%23missing%20party%20value%0A%0A%20%20OPTIONAL%20%7B?person%20wdt:P18%20?bild%7D.%0A%20%0A%20%20BIND(URI(CONCAT(%22https://portrattarkiv.se/details/%22,?SPAid))%20AS%20?SPA)%0A%0A%20%20SERVICE%20wikibase:label%20%7B%20bd:serviceParam%20wikibase:language%20%22sv,en%22.%20%7D%0A%7D%20GROUP%20BY%20%20?person%20?personLabel%20%20?death%20?birth%20?partyLabel%0Aorder%20by%20?partyLabel&d=0&md=true&g=article&l=SPA&t=personLabel&s=birth&e=death&i=bild&c=partyLabel&f=partyLabel&v=t) / [all Swedish PM people also not connected to the book](https://js.histropedia.com/apps/query-timeline/index.html?q=SELECT%20distinct%20?person%20?personLabel%20(SAMPLE(?SPA)%20AS%20?SPA)%20%20(sample(?bild)%20AS%20?bild)%20%0A?birth%20?death%20?partyLabel%20WHERE%20%7B%0A%0A%20%20VALUES%20?member%20%7B%0A%20%20%20%20wd:Q33071890%20%0A%20%20%20%20wd:Q81531912%20%0A%20%20%20%20wd:Q82697153%20%0A%20%20%20%20wd:Q10655178%20%0A%20%20%7D%0A%20%20?person%20wdt:P39%20?member;%0A%20%20%20%20wdt:P1343%20?source.%0A%20%20?person%20p:P1343%20?pTva.%0A%20%20OPTIONAL%7B?person%20wdt:P102%20?party%7D%0A%20%20OPTIONAL%7B?person%20wdt:P569%20?birth%7D%0A%20%20OPTIONAL%7B?person%20wdt:P570%20?death%7D%0A%20%20%23?pTva%20ps:P1343%20wd:Q110346241.%0A%20%20%23?pTva%20prov:wasDerivedFrom%20%5B%20pr:P4819%20?SPAid%20%5D.%0A%20%20%23?person%20rdf:type%20wdno:P102.%20%20%20%23missing%20party%20value%0A%0A%20%20OPTIONAL%20%7B?person%20wdt:P18%20?bild%7D.%0A%20%0A%20%20BIND(URI(CONCAT(%22https://portrattarkiv.se/details/%22,?SPAid))%20AS%20?SPA)%0A%0A%20%20SERVICE%20wikibase:label%20%7B%20bd:serviceParam%20wikibase:language%20%22sv,en%22.%20%7D%0A%7D%20GROUP%20BY%20%20?person%20?personLabel%20%20?death%20?birth%20?partyLabel%0Aorder%20by%20?partyLabel&d=0&md=true&g=article&l=person&t=personLabel&s=birth&e=death&i=bild&c=partyLabel&f=partyLabel&v=t)
  
.

  <img width="1337" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/84467ca1-0e58-460a-a473-9b5abe2a7692"> 
  
  #### All Swedish PM people in WD -  no value 1184
  * [Timeline](https://js.histropedia.com/apps/query-timeline/index.html?q=SELECT%20distinct%20?person%20?personLabel%20(SAMPLE(?SPA)%20AS%20?SPA)%20%20(sample(?bild)%20AS%20?bild)%20%0A?birth%20?death%20?partyLabel%20WHERE%20%7B%0A%0A%20%20VALUES%20?member%20%7B%0A%20%20%20%20wd:Q33071890%20%0A%20%20%20%20wd:Q81531912%20%0A%20%20%20%20wd:Q82697153%20%0A%20%20%20%20wd:Q10655178%20%0A%20%20%7D%0A%20%20?person%20wdt:P39%20?member;%0A%20%20%20%20wdt:P1343%20?source.%0A%20%20?person%20p:P1343%20?pTva.%0A%20%20OPTIONAL%7B?person%20wdt:P102%20?party%7D%0A%20%20OPTIONAL%7B?person%20wdt:P569%20?birth%7D%0A%20%20OPTIONAL%7B?person%20wdt:P570%20?death%7D%0A%20%20%23?pTva%20ps:P1343%20wd:Q110346241.%0A%20%20%23?pTva%20prov:wasDerivedFrom%20%5B%20pr:P4819%20?SPAid%20%5D.%0A%20%20%23?person%20rdf:type%20wdno:P102.%20%20%20%23missing%20party%20value%0A%0A%20%20OPTIONAL%20%7B?person%20wdt:P18%20?bild%7D.%0A%20%0A%20%20BIND(URI(CONCAT(%22https://portrattarkiv.se/details/%22,?SPAid))%20AS%20?SPA)%0A%0A%20%20SERVICE%20wikibase:label%20%7B%20bd:serviceParam%20wikibase:language%20%22sv,en%22.%20%7D%0A%7D%20GROUP%20BY%20%20?person%20?personLabel%20%20?death%20?birth%20?partyLabel%0Aorder%20by%20?partyLabel&d=0&md=true&g=article&l=person&t=personLabel&s=birth&e=death&i=bild&c=partyLabel&f=partyLabel&v=t)
  
  <img width="1399" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/d18a3f3c-239e-40dc-948d-1f6917688771">  
  
  <img width="1399" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/8eb76b47-c002-4a42-992a-030c127bea33">

**Comment by BobBorges** [comment]
I retract my statement
>  I don't see any reason to link nothing to something

Explicitly setting  no value is a good way to disambiguate people who didn't belong to a party (with a source) from people whose party no one checked/uploaded. 

@salgo60 I'll use this when uploading to wikidata

@fredrik1984 @Lottabrorsson (does mattias have github) -- in the google sheet write `None` or `No party` and I'll handle the novaluesnak from those values.

**Comment by Lottabrorsson** [comment]
> I retract my statement
> 
> > I don't see any reason to link nothing to something
> 
> Explicitly setting no value is a good way to disambiguate people who didn't belong to a party (with a source) from people whose party no one checked/uploaded.
> 
> @salgo60 I'll use this when uploading to wikidata
> 
> @fredrik1984 @Lottabrorsson (does mattias have github) -- in the google sheet write `None` or `No party` and I'll handle the novaluesnak from those values.

@BobBorges Mattias may have some problem with his login but he will look at that tomorrow.

**Comment by BobBorges** [comment]
Party info from Lirre was added to the google sheet -- will upload everything in one go when the sheet is ready.

**Comment by fredrik1984** [comment]
So, now I am done with my share of looking up MPs with no wikidata party:

https://docs.google.com/spreadsheets/d/1bywraAUEoRy-XPNjfk-7rpMhnQKLJc1EvSQyP3S9GII/edit#gid=336275707

Now, let's wait for Lotta and Mattias and then Bob can add these.

**Comment by salgo60** [comment]
if you add to Wikidata **add** a source just party with no source can easily be deleted as not trusted...

**Comment by MansMeg** [comment]
Yes. We should add a source. We should also use this google sheet that Fredrik put there as a unit test for the corpus to check that these party affiliations are included in the corpus. I added that as a task above.

**Comment by BobBorges** [comment]
By chance, I found two entries in the manual data, where the MPs should get assigned No party, but exist in Wikidata with a party, which is also present on the referenced pages in the bio books.

https://www.wikidata.org/wiki/Q5967169
![Image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/efde25e3-f12a-4ea9-bf34-6ef1287c0e22)

https://www.wikidata.org/wiki/Q5574217
![Image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/7d05d01b-347c-426d-a830-113a8f0c4da0)

Am I missing something here, or it's an error with the manual data? @fredrik1984 @Lottabrorsson

**Comment by fredrik1984** [comment]
It looks like a manual error (probably by me since Lotta and Mattias are so thorough)! Hence, the should be assigned parties (lmp in both cases).

**Comment by BobBorges** [comment]
@Lottabrorsson @fredrik1984 These are the remaining questions after updating wikidata from the manual work you did with party membership. Could you take a second look at these cases?

<!DOCTYPE html>

<html>
<head>
	
	
</head>

<body>

  | wiki_id | person_id | reference | note | start | end | party_wiki_id | party_abbrev
-- | -- | -- | -- | -- | -- | -- | -- | --
? | Q6026244 | i-UdMTB3XcTo7EfJoec6jQJk | 4:430 | Felaktigt inlagd Q10499215 | 1912 | 1914 | Q1594086 | lib s
? | Q5796156 | i-PkDNy9bEbEnW9xaNKSjppw | 5:298 | h saknas, men vilket ska det vara? | 1935 | 1941 |   | h
? | Q5568434 | i-SmANBDpEMp49AgxGMgLJX | 1:55 | It says "centern" in the bio book but the start/end years are AFTER the party existed | 1893 | 1893 | Q10444846 | centern
? | Q5795740 | i-KaBa73f9cDZ3KHsxdHYgui | 1:436 | It says "centern" in the bio book but the start/end years are AFTER the party existed | 1888 | 1891 | Q10444846 | centern
? | Q6167502 | i-P8XgFPqiTRHFcNFh5XMfy8 | 2:181 | no year stated in the bio book  Q10444846 and Q10444847 both centern? | ? | ? | Q10444846 | centern
? | Q5776520 | i-Tb3QUhGvYi4j7F3VwMLWH7 | 1:92 | no year stated in the bio book – bio book says “vänstern” Q111597190? (same guy in vol 4 says vänstervilde) | ? | ? | Q111108382 | "västervilde"
? | Q5806065 | i-3Vt59Mph8bZHW3Yk38AtwE | 2:383 | no year stated in the bio book – wiki id for party is different | ? | ? | Q110843 | h
? | Q5603236 | i-SP5YPpt92pVj8ZPcZjt3GV | 2:266 | Only nya lmp has a year in the bio book | ? | ? | Q6487621 | lmp
? | Q5955465 | i-HEaiAtuCoZP4zvRQQyuhM7 | 3:133 | Q-nr är en annan person, namnet hör till Q5955520 ; 1876-06-03 |   |   | Q105112 | s
? | Q5556673 | i-Vofu3seWF5yQe8KpMLXV3T | 4:205 | Står Q111033682 Men Något är fel med partiet h, vilket ska det vara?https://www.wikidata.org/wiki/Q111077860 | 1938 | 1951 | Q111077860 | h
? | Q5570120 | i-Ui4MNjsjiePyrsfZ1FnUm7 | 4:206 | Står Q111033682 Men Något är fel med partiet h, vilket ska det vara?https://www.wikidata.org/wiki/Q111077860 | 1935 | 1942 | Q111077860 | h
? | Q5789075 | i-3DJPoU6X43Z3gZwYQ5mZfw | 5:351 | Står Q111033682 Men Något är fel med partiet h, vilket ska det vara?https://www.wikidata.org/wiki/Q111077860 | 1935 | 1944 |   | h
? | Q5937245 | i-FhTohnRic91X2Lkt914b7Q | 4:247 | Står Q111033682 Men Något är fel med partiet h, vilket ska det vara?https://www.wikidata.org/wiki/Q111077860 | 1935 | 1943 | Q111077860 | h
? | Q6011353 | i-RZvCDDC9zwyuV3rH48onze | 5:430 | Står Q111033682 Men Något är fel med partiet h, vilket ska det vara?https://www.wikidata.org/wiki/Q111077860 | 1935 | 1940 | Q111077860 | h
? | Q6014382 | i-HWuy1bfrVaJd5tRcAdeD1m | 4:128 | Står Q111033682 Men Något är fel med partiet h, vilket ska det vara?https://www.wikidata.org/wiki/Q111077860 | 1935 | 1942 | Q111077860 | h
? | Q6093360 | i-UXRUTZDfYdtzvHei35SC2n | 5:436 | Står Q111033682 Men Något är fel med partiet h, vilket ska det vara?https://www.wikidata.org/wiki/Q111077860 | 1935 | 1938 | Q111077860 | h
? | Q10501501 |   | 5:263 | Stod inga årtal i Wiki – wiki_id is for a party | 1905L | 1911 | Q10501501 | mod
? | Q6237662 | i-NPaHZmLBpwn5suNf7XNkx5 | 1:460 | This is an example of party name in wikidata that is incorrect from a historical point of view but still is the same party | 1935 | 1936 | Q110843 | h
? | Q6237662 | i-NPaHZmLBpwn5suNf7XNkx5 | 1:460 | This is an example of party name in wikidata that is incorrect from a historical point of view but still is the same party | 1941 | 1944 | Q110843 | h
? | Q5608541 | i-McNdJaEnje6pXfi83cxxZW | 3:204 | Tidsperiod för parti inte angiven i Wikidata | 1917 | 1917 | Q1309957 | vilde
? | Q6178909 | i-B7hrTkCutn2YGLqw9zbUd2 |   | Dude has mandates in the unicameral period, but party memberhsip stops in 1970 on wikidata,. I extended (c) (Q110832) for him until 1982 per biobook EK1:105. I assume it’s the same centerpartiet. |   |   |   |  


</body>

</html>

**Comment by Lottabrorsson** [comment]
> Q5603236

@BobBorges @fredrik1984 I can look at them. Get back to you later this week.

**Comment by fredrik1984** [comment]
Great work Bob! And thank you Lotta for taking a look at these MPs that Bob listed. Get back to me if you need input.
