### ISSUE TITLE
Identify missing motions during 1970-2000

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#351]
There are some periods where there are either missing motions because they are in Word format or have not yet been digitised.

- [ ] RB will find the missing motions and send them to @liamtabib 
- [ ] @liamtabib will put the missing motions in the repository of PDF motions

**Comment by Lottabrorsson** [comment]
> There are some periods where there are either missing motions because they are in Word format or have not yet been digitised.
> 
> * [ ]  RB will find the missing protocols and send them to @liamtabib
> * [ ]  @liamtabib will put the missing protocols in the repository of PDF motions

@MansMeg Do you mean both protocols and motions in this issue?

**Comment by MansMeg** [comment]
Sorry! Only motions. Now clarified.

**Comment by BobBorges** [comment]
I think we should keep the original word files as well.

**Comment by MansMeg** [comment]
I agree with Bob
