### ISSUE TITLE
Update the quality graph for version 0.10

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#352]
The quality graph on the landing page only go to 0.9. We should update this.

**Comment by BobBorges** [comment]
Should I push this straight to main?
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/1d423f6c-569f-4400-ab81-09859ec344cc)

**Comment by MansMeg** [comment]
Yes. I think you can do that. But check with @ninpnin .

**Comment by BobBorges** [comment]
#361
