### ISSUE TITLE
Off-by-one errors in page numbers

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#36]
just checking: tagged page numbers not always match with actual page numbers, but it is the tagged one's we check? an exampel: <pb n="153" facs="https://betalab.kb.se/prot-1922--fk--37/prot_1922__fk__37-153.jp2/_view"/>    <note n="48f9b2fb">    Nr 37.    </note>    <note type="date" n="98919e5b">    154 Onsdagen den 24 maj e: m.

**Comment by ninpnin** [comment]
I'm not sure if we want to change this, it's the same indexing schema as at betalab after all.

EDIT: Though we might want to communicate this upstream.

**Comment by MansMeg** [comment]
Ok, that is strange. So are beta lab also off by one error with respect to the physical copies? From a textual representation error perspective, we should try to stay close to the actual page numbers in the protocols.

**Comment by MansMeg** [comment]
Yes, we should probably communicate this with KB-lab - although I guess this issue is of lower priority right now.

**Comment by ninpnin** [comment]
It's rather the inconsistent page numbering of the actual protocols – the first page might not be numbered, some other (meta) pages might not have numbers

**Comment by MansMeg** [comment]
Oh. ok. Lets then take this discussion with Johan and Fredrik. What they think we should do.

**Comment by ninpnin** [comment]
Hmm. I just went through a couple of different protocols. I realized I might be misremembering, since those protocols had page numbers also on the table of contents pages.

**Comment by MansMeg** [comment]
Ok. Then I suggest we add the correct page number, as also was proposed by Johan. Hence the correct page number (the same as the printed one) and the betalab link.

**Comment by ninpnin** [comment]
I think we can fix most of these by just starting indexing from 1. That should be a very quick and easy fix.
