### ISSUE TITLE
Accessibility of merged metadata

### ISSUE THREAD

**Issue by BobBorges** [welfare-state-analytics/riksdagen-corpus#364]
We need to make merged metadata files accessible to researchers without also pointing them to the `input/` dir, since we mean to remove that from the repo.

- [x] ensure functionality of `scripts/wikidata_process.py` is only dependent on pyriksdagen module functions
- [x] add example how to generate merged metadata file to notebook
- [x] attach merged metadata files (currently in `input/matching/`) automatically with each release

**Comment by ninpnin** [comment]
On the python side,

```py
from pyriksdagen.metadata import load_Corpus_metadata
```

does exactly this now.

**Comment by ninpnin** [comment]
Apparently I had already added this functionality to the notebook
