### ISSUE TITLE
Add speaker of the Riksdag as role in the MP database

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#365]
We want to know which MPs were elected as speaker of the Riksdag (talman), and which period. Note that speaker of the Riksdag gets a replacer in the Riksdag since he/she can't vote.

https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_talm%C3%A4n_i_Sveriges_riksdag

**Comment by BobBorges** [comment]
Done? `corpus/metadata/speaker.csv`

**Comment by fredrik1984** [comment]
Ok, it looks complete to me!
