### ISSUE TITLE
Tag different speech categories

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#37]
There are different speech categories in the Swedish parliament: interpellationsdebatt, partiledardebatt, anföranden etc. There are also other kinds of categories that perhaps should be tagged as a speech, but perhaps not. For example, "Meddelanden ang enkla frågor", which seems to be written questions from mp that are read out loud by the speaker of the house (?). 

How to deal with these speech categories? Should we tag them as "seg", and if so, how to detect them (and other similar speech categories)?

**Comment by MansMeg** [comment]
I actually do not know how to add this metadata right now. Maybe have a separate CSV for this kind of information? Although, these categories are important for analysis in the long run.

**Comment by fredrik1984** [comment]
Agree, this issue is not a prioritized issue, but something to keep in mind.

**Comment by ninpnin** [comment]
Tracked in #102
