### ISSUE TITLE
Unit test that dates are consistant in the MP database

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#372]
We should probably add a unit test on birthdate, dearhdate and mandate periods when we get the mandate period dates up to date. Eg no one should start a mandate before they are born.

**Comment by BobBorges** [comment]
Absolutely!

**Comment by BobBorges** [comment]
Do we have a rule of thumb for youngest allowed MP? I checked birth year < mandatae start year -15. And aside from the guy I posted about yesterday, there's this fella who was apparently in FK as a 14yo.

https://www.wikidata.org/wiki/Q117018060

Otherwise, we're pretty good about birth and start dates. Will check the death/end tomorrow & add a unit test for this.

**Comment by MansMeg** [comment]
Have you checked this in the biobooks? Seem strange, ie probably an error in wikidata.

**Comment by fredrik1984** [comment]
His birth/death dates are correct, it was the chamber dates that were wrong. I changed that now in Wikidata. These dates will be more correct when Lotta and Mattias finish their work with bio books 3–5 (this person was in bio book 5)

Regarding how young one can be to be elected to the riksdag it is roughly like this:

First chamber: 36 years old (1867–1911)
Second chamber: 21 years old (1867–1911)

1911: 24 years old
1919: 23 years old
1945: 21 years old
1965: 20 years old
1969: 19 years old
1975: 18 years old

**Comment by MansMeg** [comment]
Boom! Please add this as a unit test (with a comment with a reference if Fredrik has such a reference).

**Comment by fredrik1984** [comment]
Ok! If we are going to use that as a unit test then we need to check the historical process more. I realized that I confused the right to vote and the right to be elected. I went back to Nils Stjernquist's book about the bicameral riksdag from 1966 and 1996, and to be honest this was quite confusing to me. The first and second chamber have different rules, and it was difficult for me to follow actually. Perhaps @Lottabrorsson can help out with this later (not super urgent). But I think any MP under 24 years old before 1970 should be red-flagged...

**Comment by BobBorges** [comment]
if I do birth year < (mandate start year - 24) I get 56 hits. I'll check these carefully.

**Comment by fredrik1984** [comment]
Put this on hold for now. Lotta and Mattias will go through specific start/end dates in the bio books/Wikidata and then some of these will be solved. After they have done their work with bio book 3–5 we can test this again. 

Another related test would be to red-flag MPs that sat in the riksdag longer than e.g. 40 years.

**Comment by Lottabrorsson** [comment]
> Ok! If we are going to use that as a unit test then we need to check the historical process more. I realized that I confused the right to vote and the right to be elected. I went back to Nils Stjernquist's book about the bicameral riksdag from 1966 and 1996, and to be honest this was quite confusing to me. The first and second chamber have different rules, and it was difficult for me to follow actually. Perhaps @Lottabrorsson can help out with this later (not super urgent). But I think any MP under 24 years old before 1970 should be red-flagged...

@fredrik1984 Yes, I can take a look.

**Comment by BobBorges** [comment]
this is checked in riksdagen-records/test/mp.py
