### ISSUE TITLE
Speaker tag before note

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#38]
In the xml files, sometimes a speaker tag comes before a note. Is this correct?  Shouldn't speaker only be tagged in relation to seg?

**Comment by MansMeg** [comment]
Can you copy in an example?

**Comment by fredrik1984** [comment]
<pb n="22" facs="https://betalab.kb.se/prot-1964--fk--23/prot_1964__fk__23-022.jp2/_view"/>
          <note type="date" n="fce40d6c">
            Tisdagen den 12 maj 1964
          </note>
          <note n="cf5564f3">
            m, m., jämte i ämnet väckta motioner, såvitt propositionen och
            motionerna avser medelsanvisning.
          </note>
          <u who="gosta_skoglund_8feb36" xml:id="i-c905995e2b806d85-42" prev="i-c905995e2b806d85-39" n="5104c78e"/>
          <note n="f0233de4">
            Anmäldes och bordlades följande under sammanträdet till herr
            talmannen avlämnade motioner:
          </note>

**Comment by MansMeg** [comment]
That seem to be incorrect.

**Comment by ninpnin** [comment]
Removed empty tags.
