### ISSUE TITLE
Missing MP:s in the metadata

### ISSUE THREAD

**Issue by Stubbendorff** [welfare-state-analytics/riksdagen-corpus#39]
List of speakers found in the corpus but not in _members_of_parliament_.
- [ ] Gustav Andersson (1945)
- [ ] David Norman (1945)
- [ ] Karl Wistrand (1945)

**Comment by ninpnin** [comment]
Which chamber did they sit in?

**Comment by Stubbendorff** [comment]
Andersson in the second, Norman and Wistrand in the first.

**Comment by ninpnin** [comment]
Is this still relevant with the wikidata metadata?

**Comment by MansMeg** [comment]
Probably not. I close this now.

**Comment by salgo60** [comment]
* [X]  Gustav Andersson (1945) second chamber --> [Lista_Över_ledamöter_av_Sveriges_riksdags_andra_kammare_1945-1948](https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_ledam%C3%B6ter_av_Sveriges_riksdags_andra_kammare_1945%E2%80%931948) -->

<img width="565" alt="image" src="https://user-images.githubusercontent.com/14206509/166651381-0a41e951-f330-42cb-bd28-3df3e9547a3b.png">


* Wikipedia [Gustaf_Andersson_(sjukkassedirektör)](https://sv.wikipedia.org/wiki/Gustaf_Andersson_(sjukkassedirekt%C3%B6r))
* Wikidata [Q5554616](https://www.wikidata.org/wiki/Q5554616)
* Andersson i Eskilstuna senare Nyköping, E Gustaf, 1:359 --> SPA [sj9PGLAlnmUAAAAAABfP5Q](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfP5Q)

<img width="546" alt="image" src="https://user-images.githubusercontent.com/14206509/166652004-d3569b48-42d9-4762-ac7f-453a40f6997b.png">

**Comment by MansMeg** [comment]
Great! Yes, then this issue is solved with the connection to wikidata

**Comment by salgo60** [comment]
* [X]  David Norman (1945) same as WD [Q6017122](https://www.wikidata.org/wiki/Q6017122)
* [X] Karl Wistrand (1945) same as WD [Q6340875](https://www.wikidata.org/wiki/Q6340875)

**Comment by MansMeg** [comment]
Cool! Thanks @salgo60 !
