### ISSUE TITLE
Better schema testing

### ISSUE THREAD

**Issue by BobBorges** [welfare-state-analytics/riksdagen-corpus#395]
Currently the schema unit test runs on one random file per year. We should at least run the schema test locally once on the whole corpus to find files that don't fit the schema instead of inconsistently passing/failing unit test when working on other issues. Then update workflows:

- [ ] on release: schema test all protocols
- [ ] on push: schema test on protocols with edits

**Comment by BobBorges** [comment]
Schema test is currently run on all changed/created files on PR. Maybe that's better than push, since we shouldn't be pushing edited protocols directly to dev or main anyway. What do you say @MansMeg?

**Comment by BobBorges** [comment]
On push, there's a random sample. We should just add the validation check for all files on release.

**Comment by ninpnin** [comment]
This on push testing is already implemented. Problem is, sometimes the diffs are so large that the list of changed files can't be generated on Github actions

**Comment by ninpnin** [comment]
See: https://github.com/welfare-state-analytics/riksdagen-corpus/actions/runs/7347998353/workflow#L33

**Comment by ninpnin** [comment]
Testing the whole corpus against the schema is quicker now that we have the full AK/FK/EK (sub)corpus files. It still takes like 20 minutes per subcorpus, though, so we might want to restrict when we run it.

**Comment by BobBorges** [comment]
I get the same error if I run the test locally on the same set of files, so I don't think it's a problem with actions.

**Comment by ninpnin** [comment]
The shell can only take arguments up to 1048576 characters, i.e. 20k files. Is it that this time?
