### ISSUE TITLE
Identify and handle empty speeches

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#397]
We know from the paper that there are a lot of speeches in 2010- that have incorrectly been annotated as speeches when they, in practice, are in a registry of speeches in the end of the records.
We need to identify these incorrect (empty) speeches and change them to note(?)

**Comment by fredrik1984** [comment]
@BobBorges – I guess this issue is related to the quality control I did last week? Is this issue fixed now?

**Comment by BobBorges** [comment]
yes
