### ISSUE TITLE
Solve the issue of name in parliament

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#40]
We need to have a file that contain maps from names in parliament to individual speakers in parliament. Hence we can have multiple names in parliament for the same member of parliament. This can also change over time.

A suggestion is. a csv with columns:
speaker_id, name_in_parliament, period_start, period_end

@ninpnin any thoughts?

**Comment by ninpnin** [comment]
Part of #41
