### ISSUE TITLE
Point to original files in data

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#408]
@ninpnin pointed out that this naming convention was due to a mapping toward the original files. Then I think we instead should point to these original files in the data instead.

**Comment by BobBorges** [comment]
Does this address your issue? If so, you can close it as done b/c it's already there :)
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/5239698b-bbb9-4d62-b205-c371e06cdac3)

**Comment by MansMeg** [comment]
Oh Sorry!
