### ISSUE TITLE
Improve mapping between intros and MP metadata

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#41]
There is currently a lot of unknown maps between names in parliament and actual MPs. We should list those missing names in parliament and go through them in increasing order.

@ninpnin any thoughts?

**Comment by ninpnin** [comment]
Currently, there are a lot of instances where multiple people are matched per intro. For instance __Herr Johansson i Älvsjö__ might match all _Johanssons_ and thus the speaker is undetermined.

We need to address this, among other issues in the MP metadata connection. The aim is at 90% accuracy or more, which will be validated by drawing a random sample of pages.

**Comment by MansMeg** [comment]
- [x] Fix a majority of the unknowns computationally @ninpnin 
- [x] Annotate a first 5 pages per decade - sample with true connections to MP @rbbby 
- [ ] List the unique introductions with unknown so we can start with manually fixing issues that have a larger effect on the corpus.
- [ ] Fix the rest of the unknown manually by decade
- [ ] Draw a random sample and manually check the connections between speaker and MP file

**Comment by ninpnin** [comment]
The annotation classifies the intros into three categories

Correctly tagged:
```xml
<note type="speaker">
Måns Magnusson:
</note>
<u who="mans_magnusson_1234">
[...]
```

Incorrectly tagged
```xml
<note type="speaker">
Per Andersson, som yttrade:
</note>
<u who="sven_andersson_1234">
[...]
```

Unknown
```xml
<note type="speaker">
Finlands president Niinistö, som sade:
</note>
<u who="unknown">
[...]
```

The latter ones are relatively easy to find computationally, the first two need to be annotated by hand.

**Comment by MansMeg** [comment]
After discussion:
@ninpnin will try to fix the obvious error sources found in the subsample by @rbbby 
then when done, a new subsample will be drawn

**Comment by ninpnin** [comment]
I wrote down some observations on the sample https://github.com/welfare-state-analytics/riksdagen-corpus/blob/mp/input/curation/mapping_sample_0.md

**Comment by ninpnin** [comment]
Errors detected in the first sample seem to fall into the following categories, in the order of least work per improvement

1. 30% Problems detecting ministers
2. 30% Errors with "X i Y" type intros, mostly stemming from incomplete metadata
3. 40% Miscallenous problems in the mapping process

We need to at least get 1. and 2. to reach 90% accuracy. The work on ministers is alrady ongoing #71, but we need to work on expanding the metadata as well.

- [x] Ministers
- [ ] Improving metadata for "X i Y"

**Comment by ninpnin** [comment]
Subset of #80
