### ISSUE TITLE
Re-OCR debate records since 1971

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#418]
The digitized debate records from the unicameral era probably need to be re-OCRed. They were digitized mid-2000s (the bicameral documents were digitized later in the mid-2010s). Around mid-1990s all debate records have been born digital.

**Comment by ninpnin** [comment]
I think we already use the tesseract versions. For example prot-197576--008, points to https://betalab.kb.se/prot-197576--8/prot_197576__8-000.xml which says

```xml
<softwareName>tesseract 4.1.1</softwareName>
```

**Comment by MansMeg** [comment]
Great!

Is this the case for all protocols? Then maybe we dont need to do this. This might come from Pelle that looked at the ocr at the parliament that doesnt use Tesseract.

**Comment by MansMeg** [comment]
Ie we might be able to close this issue.

**Comment by fredrik1984** [comment]
I think we can close the issue. I opened it because I forgot that we already have re-OCRed the protocols, and that our quality is significantly better between our protocols in the XML files and the same protocols on the Riksdag web.

**Comment by MansMeg** [comment]
Cool!
