### ISSUE TITLE
Fix split introductions

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#429]
Some introductions in the records are split based on line breaks. We should fix this so that there is only one line break. Jesper looked at this in his thesis and might both have good training data and even a model we could use/try. Otherwise we could fix the simple cases right away programatically.

**Comment by BobBorges** [comment]
There is a script already, but I'm missing a file it looks for `input/segmentation/join_intro_patterns.csv` -- if no one has that file, I think I can just do without it...

Two sequential speaker intros are merged -- if intros[0].text ends with "-" then remove "-" and join w/ no space, else join with space after intros[0].text. Caveman style, but it should work in most cases I think.

**Comment by MansMeg** [comment]
At least that would be a first run to get the obvious errors fixed.

**Comment by MansMeg** [comment]
Here is the model:
https://huggingface.co/jesperjmb/MergeIntrosNSP
