### ISSUE TITLE
Incorrect versions in the README figures

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#435]
There is no v.0.11.0 in the dashboard? I guess it is the incorrect version in the plots?

**Comment by MansMeg** [comment]
Also time indicate that this is not recent:
Last update: 2023-11-21, 12:27:58

I guess it needs to be part of the release cycle.

**Comment by MansMeg** [comment]
Also, title indicates the wrong version:
Swedish parliamentary proceedings --- 1867--today --- v0.10.0

**Comment by BobBorges** [comment]
It's still running
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/c4e9886a-9cd7-4af0-a9f9-55b8042a8466)

**Comment by MansMeg** [comment]
![IMG_4563](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/2458198/80a90362-97f4-4737-8f7a-f8a47f705580)

still same problem?

**Comment by ninpnin** [comment]
The release workflow crashed, hence no update
