### ISSUE TITLE
Open a "Discussions" forum for questions

### ISSUE THREAD

**Issue by Lauler** [welfare-state-analytics/riksdagen-corpus#443]
To encourage discussion and questions about `riksdagen-corpus`, I would recommend opening a "Discussions"-forum in the repo. There is somewhat of a barrier in asking simple/dumb questions about a library/dataset through opening an issue. A question is not necessarily always worthy of an issue. 

I'd like a place to ask some clarifying dumb questions that I feel aren't issues, but rather due to a lack of understanding/context on my part. 

For a repo with a discussions forum see: https://github.com/openai/whisper/discussions

To enable Discussions, go to the repository's `Settings` tab and check "Discussions".

**Comment by MansMeg** [comment]
I think this is a good idea. @ninpnin , @BobBorges and @fredrik1984 ?

**Comment by fredrik1984** [comment]
Yes, I think this could be a good idea. Maybe something that @MansMeg or @BobBorges could create?

**Comment by BobBorges** [comment]
@Lauler, thanks for the suggestion.

Done.
