### ISSUE TITLE
Bug in test badge?

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#445]
<img width="919" alt="Skärmavbild 2024-01-16 kl  11 01 27" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/2458198/e0ae12a2-57a4-4bb9-9eb4-e5ead81b6cdf">

**Comment by BobBorges** [comment]
No bug:
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/ecadd542-72ff-4fd8-8bd6-dbf52a756b6d)

**Comment by ninpnin** [comment]
Addressed in #444
