### ISSUE TITLE
Bug with the last year - large drop in mp quality

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#446]
Hi!

It seems like there is a drop, both in the accuracy of speaker identification and the number of MPs in the last release? 

![mp-coverage](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/2458198/b51788cb-a581-4f13-980e-fbaddbcd4253)
![version_plot](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/2458198/e447146f-a6f3-431c-93c7-5c2079842901)
![mp-coverage-ratio](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/2458198/428ddf41-c6a8-4cae-a952-11e0bd482ce7)

We should both fix this but also create a unit test that fails if there are these type of large drops in accuracy.

**Comment by BobBorges** [comment]
The only thing that concerns me is the drop in speaker identification in 2021+. The rest is about (or exactly) the same as 0.12. For the next release, I will implement more precise date handling, so the graphs should be a closer representation of reality.

> large drops in accuracy

What kind of threshold would you use for a unit test? Here is a drop of around 3% in one year.

**Comment by MansMeg** [comment]
Yes. Thats what Im concerned about.  Great!

I think we might want to capture a drop of 1.5% in any of the years and maybe in total? Also check for an increased absolute difference of 0.03 in the ratio? Does that make sense?

**Comment by BobBorges** [comment]
#355 #452 


![Image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/b40a73e7-b855-436f-bbdd-64dc8ec81b70)
