### ISSUE TITLE
Underspecified MP birthdates

### ISSUE THREAD

**Issue by BobBorges** [welfare-state-analytics/riksdagen-corpus#448]
## description

For most MPs we have a full birth date. The last estimate was that there are around 200 MPs who only have a birth year listed in our metadata. I have started looking up full birth dates for these people (in the linked file) -- there are some 110 left.

## the task

Look up the remaining individuals in the biography books and list their full birth date in the file along with the series (enkammar / tvåkammar), volume, and pages where you found the info (if it is different than what's already listed).

[Flagged_MP_issues - Underspecified Birthdates.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/13975292/Flagged_MP_issues.-.Underspecified.Birthdates.csv)

**Comment by todomoldovan** [comment]
I can take this

**Comment by todomoldovan** [comment]
[Flagged_MP_issues.-.Underspecified.Birthdates.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14011386/Flagged_MP_issues.-.Underspecified.Birthdates.csv)

**Comment by BobBorges** [comment]
I reopened the issue so I remember to take the next steps with this file.

**Comment by todomoldovan** [comment]
Date format fixed [Flagged_MP_issues.-.Underspecified.Birthdates.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14097484/Flagged_MP_issues.-.Underspecified.Birthdates.csv)

**Comment by todomoldovan** [comment]
Double-checked MP birthdates [clean.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14241011/clean.csv)
