### ISSUE TITLE
MPs Too Young?

### ISSUE THREAD

**Issue by BobBorges** [welfare-state-analytics/riksdagen-corpus#449]
## description

We flagged some MPs that seem too young -- this is not a legal thing, just a tendency. In some cases, they MP might actually be young, but it could also mean that there is some error in the metadata.

## the task

Check each individual on biobooks, and/or riksdagen open data to see if there are obvious discrepancies in either the birth date or the mandate. 

[Flagged_MP_issues - Too Young .csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/13975315/Flagged_MP_issues.-.Too.Young.csv)

**Comment by simonipek** [comment]
I can take this

**Comment by simonipek** [comment]
[Flagged_MP_issues.-. Checked.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14052365/Flagged_MP_issues.-.Checked.csv)

**Comment by BobBorges** [comment]
Excellent! Thanks @simonipek

**Comment by simonipek** [comment]
[Flagged_MP_issues.-. Corrected.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14125142/Flagged_MP_issues.-.Corrected.csv)

**Comment by ninpnin** [comment]
Is this done?

**Comment by simonipek** [comment]
I am finished with this, yes. Let me know if I should do anything more.

**Comment by ninpnin** [comment]
@BobBorges are there other things that should be tracked under this issue? Or should we close this?

**Comment by BobBorges** [comment]
closing
