### ISSUE TITLE
Riksdagen corpus paper

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#45]
- [ ] Do a litt review
- [ ] Setup a disposition of the paper

New ideas:
- using git to separate manually curation and automated curation
- quality estimation using random sampling

References:
http://ftp.cs.utoronto.ca/cs/ftp/pub/gh/Beelen-etal-CJPS-2017.pdf
https://journals.sagepub.com/doi/pdf/10.1177/2053168019838352
https://www.aclweb.org/anthology/2020.parlaclarin-1.2/
https://www.aclweb.org/anthology/2020.parlaclarin-1.9/

https://www.aclweb.org/anthology/volumes/2020.parlaclarin-1/

**Comment by MansMeg** [comment]
Here are some thoughts on what we want to include in the paper:

Tentative title: Constructing an agile research corpus: The example of the Swedish parliament

Background:
Many corpora are constructed once and then released. 
Benefits:
- Simplifies comparisons
- Require less storage
Cons
- It is difficult to improve continuously (and fix errors)
- It require us to download the whole corpus if a new version is released

Problems we face when constructing a real research corpus:
1. We can to continuously add new data to our corpus. Both going backwards (add older records) and forward (new documents released) in time - this introduces different qualities for different periods.
2. We want to add additional covariates as we go along. For example a new variable with Twitter accounts. These variables generally will not span the whole period.
3. We want to have a collaborative structure that makes it easy for other researchers to use - and improve - the corpus. This can mean adding additional covariates for different time periods or correcting errors in the corpus.
4. We want to curate the corpus both programmatically (that is we have a non-zero probability of a correction being wrong) or fully manually (that is a gold standard correction with probability 1 of being correct).
5. We want the corpus to be perfectly traceable back to the original source.
6. We want as few errors as possible. I.e. a text representation error of zero.

**Comment by ninpnin** [comment]
Progress is tracked on Overleaf
