### ISSUE TITLE
Errors with manually curated mandate dates.

### ISSUE THREAD

**Issue by BobBorges** [welfare-state-analytics/riksdagen-corpus#453]
I wrote a unittest (#452) to check that a manually curated list of mandate dates doesn't change. The test fails on 18 rows for various reasons (listed in the attached file). 

I think we should re-verify these dates in the bio books -- I don't see edits reverting the dates listed in wikidata, and there are some other errors (dead MPs, child MPs) by this list of dates.
[mandates-test_20240122-1459.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14011553/mandates-test_20240122-1459.csv)

**Comment by todomoldovan** [comment]
Verified as much as I could 
[mandates-test_20240122-1459.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14166007/mandates-test_20240122-1459.csv)
