### ISSUE TITLE
Create a structure to automatically update the corpus every year with new paralimentary data

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#46]

**Comment by MansMeg** [comment]
I think this is done already? @ninpnin

**Comment by salgo60** [comment]
@MansMeg Is the plan that you will have an API (or is it GITHUB) that we can call and check for Wikidata consistancy ? Today in Wikidata we have 
* [Property:P8433](https://www.wikidata.org/wiki/Property_talk:P8433) "Sveriges Riksdag dokument" 
<img width="504" alt="image" src="https://user-images.githubusercontent.com/14206509/166445358-a82869de-a042-4ed0-ab21-057ed456c730.png">

* [Property:P8388](https://www.wikidata.org/wiki/Property_talk:P8388) "Riksdagen person GUID"

<img width="481" alt="image" src="https://user-images.githubusercontent.com/14206509/166445745-93fe5b5b-c288-40f1-83fe-fe55a568dc3c.png">

* [Property:P1214](https://www.wikidata.org/wiki/Property_talk:P1214) "Riksdagens person-id"
 
<img width="446" alt="image" src="https://user-images.githubusercontent.com/14206509/166445706-55ba4aac-b510-4f6d-9963-61fb3e7c3df3.png">

Looks like we would like to have metadata about all "riksdagens" documents...

**Comment by ninpnin** [comment]
We can set up a CI script to check whether new data is availalable every now and then.

**Comment by MansMeg** [comment]
@salgo60 For now github will be the api to the corpus. I dont really get the question on metadata? Also, we are still on version 0.x so I would be causion to build something on top of our data right now.

**Comment by MansMeg** [comment]
@ninpnin I don think its nessecary. We are probably gonna update the corpus every now and then when we need/want to. The important part is that we have code and maybe som scripts to run to update.

**Comment by salgo60** [comment]
@MansMeg Thanks The problem Wikidata has as an open plattform is that we also have **vandalization** of data ---> if we can check our data with external sources --> its one way to find  **vandalization** 

Metadata --> that we add wikidata objects for all "Riksdagens dokument" but not store the content as you do in TEI format... my understanding today is that we lack good support for TEI

**Comment by ninpnin** [comment]
Deemed unnecessary
