### ISSUE TITLE
Setup ALTO and PDF files repos for the records

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#469]
Hi!

We have now gotten an ok from Chris at KB lab to put the ALTO-files from betalab as a separate repo. Its no rush, but probably good to fix long term to map back to the source in an open fashion.

**Comment by BobBorges** [comment]
Excellent! Now I'm curating those formerly missing protocols, and by default the pb element links will 404, so it will be better if we change all at once to link a page on gh.

**Comment by MansMeg** [comment]
Yes. Maybe make this part of 1.0? Would be nice at least.

**Comment by MansMeg** [comment]
We probably want to use gitLFS for the pdfs. So the question is how to point to specific pages on github LFS. I think @ljo had some ideas.

**Comment by BobBorges** [comment]
We could just chunk up the pdfs by page, unless github supports some GET-like parameter to link  a specific page.

**Comment by MansMeg** [comment]
Yes. I cant find a simple way to point to a specific page on github with git lfs.

**Comment by BobBorges** [comment]
it's easy enough to `pdfseparate` pdfs, so the one image per page option seems like a reasonable one.

**Comment by ninpnin** [comment]
Repo here https://github.com/swerik-project/riksdagen-records-pdf let's follow the issues there
