### ISSUE TITLE
Change name of id variables

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#475]
Our person_id is now called swerik_id. This is problematic for two reasons.
1. It doesn't say what the id is actually about (persons)
2. swerik is probably a name we want to avoid in the database since the data will survive longer than the project

I suggest we change swerik_id to person_id

I think ideally this is fixed before 1.0.

**Comment by fredrik1984** [comment]
Aha, I thought we already had decided about not having "swerik" in the id name, for the reason you mentioned. I also think "person_id" is a good choice since we will have other persons who are not MPs in our database as well (some ministers, the monarch, etc).

**Comment by MansMeg** [comment]
Yes, I thought so to, but I saw it some of the files so I opened an issue.

**Comment by BobBorges** [comment]
Ok, sorry if I missed the point somewhere. Can change to `person_id`.

**Comment by MansMeg** [comment]
No big problem. Its just that column name changes will not be back compatible. I.e. after 1.0, we will need to bump the major version. =)

**Comment by ninpnin** [comment]
Also, the thing will remain to be called SWERIK ID on Wikidata

**Comment by MansMeg** [comment]
Ok. We should probably fix that as well, long term.

**Comment by ninpnin** [comment]
? what should it be called there, then?

**Comment by BobBorges** [comment]
I'm not sure if it should be changed there -- the IDs will still resolve to the Swerik web page after the project so long as no one deletes the github organization. I think we ought to leave it swerik ID until/unless some other organization takes over administration of these IDs.

**Comment by MansMeg** [comment]
Ok. Sounds fair. Then we only need to do this in our corpus.

**Comment by BobBorges** [comment]
Done in the swerik-project repos.
