### ISSUE TITLE
Camera-ready article 

### ISSUE THREAD

**Issue by ninpnin** [welfare-state-analytics/riksdagen-corpus#483]
TODOs:
- [x] Update OCR accuracy results
- [x] Fix Figures 2-4, poor quality (?)
- [x] Fix minor issues pointed by Reviewer 1 (see below)
- [x] Shorten historical background section
- [x] Add, finish, and proofread Appendix
- [x] Regenerate graphs, figures etc. with new data
- [x] Generate PDF with camera-ready settings
- [x] Fix reference list
- [x] Double check links etc.

Minor issues by Reviewer 1:

> - [x] “This parliamentary document contains” -> change to “These parliamentary documents contain”
> - [x] The figures do not come in the sections they are mentioned in and should be placed in the sections where they are referred to shortly after the sentences in which they are mentioned (at least not in other sections or on other pages - it seems weird to have a figure in the middle of a text passage that has nothing to do with it)
> - [x] “corpus consists of two major parts, [...] (2) the members of parliament” -> change to “corpus consists of two major parts, [...] (2) data on the members of parliament”
> - [x] “the corpus contains all MPs during this period and additional metadata on each MP” -> change to “the corpus contains the names of all MPs during this period and additional metadata on each MP”
> - [ ] You mention Europarl as a main contribution to the design of comparable parliamentary corpora, enabling comparative analysis of parliamentary legislative processes. As it is rather different (topics, structure, language use) from national parliament corpora, it would rather be interesting to see more on initiatives that seek to make similar data (corpora from national parliaments, e.g. Swedish vs. Norwegian, English, German etc.) comparable for contrastive research.
> - [ ] The first 2 sentences of the paper can be found literally in various other text that are made available online, e.g. https://swerik-project.github.io/ You might quote a source or leave them out. Particularly the first sentence does not seem necessary here. And to me it is not entirely clear, for instance, what the term a “democratic resource” means.
> [...]  <--- Was there something else to do?
>  - [x] The references need some proofreading, 
>  - [x] ---> a comma, for instance, is missing between author names “Haidee Kotze Minna Korhonen” 
 > - [x] ---> and many nouns need to be capitalized (ireland, english, european)

**Comment by ninpnin** [comment]
@fredrik1984 I assume you take the rewriting of the historical background section? It was supposed to be slightly shorter than the one we have now.

**Comment by fredrik1984** [comment]
Yes, I can do that. I can also make the reference list more correct, there were some minor fixes regarding titles and stuff. Is there a style guide somewhere?

When is the deadline again? @ninpnin

**Comment by MansMeg** [comment]
I guess we want to rerun Figures on version 1.0? So we have the correct results in the paper.

**Comment by ninpnin** [comment]
Here's the [Author's kit](https://lrec-coling-2024.org/authors-kit/)

**Comment by BobBorges** [comment]
ocr quality results are updated in the ocr-quality-estimation repo:

![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/338d04be-d691-45c7-ab8b-a0279af652aa)

**Comment by BobBorges** [comment]
I don't understand what the reviewers want in figures 2--4. 

Figure 2 are images of protocols, 3--4 are actually not images, but typeset into the document. 

What's the actual issue?

**Comment by ninpnin** [comment]
@BobBorges I have no idea. Are the images of the protocols in the original resolution? If not, that's probably the only thing we can change about this.

**Comment by BobBorges** [comment]
reviewer is not the first to notice
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/a3ed2cc2-5fa4-4bd1-a3e5-9d89143de90e)

**Comment by BobBorges** [comment]
> Are the images of the protocols in the original resolution? 

same resolution as the pdf on betalab, as far as I can tell

**Comment by BobBorges** [comment]
> The figures do not come in the sections they are mentioned in and should be placed in the sections where they are referred to

This is now adjusted with the exception of figure 2 -- this one is too big to fit on the previous page, where it is mentioned. Figure 6 also come either on the previous (current) or following page than where it is mentioned due to the paragraph placement.

**Comment by MansMeg** [comment]
Great! You should celebrate.
