### ISSUE TITLE
Add new info to the Swerik webpage 

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#484]
**1. Change the name of the tab “Publications” to “Collaborations”.** On this page we will write down all ongoing and previous collaborations that Swerik has with other projects and researchers. On that page, add the following text below:
 
Swerik welcomes collaborations with research projects and individual scholars. Our working ideology is that researchers who work with the parliamentary infrastructure will also make it better.
 
**Collaboration with research projects investing resources in Swerik:**
 
Project: “What does it take to make leadership gender equal? Studies of political leadership in a gender balanced context”. PI: Josefina Eriksson (Uppsala University). Funder: The Swedish Research Council (2023–2026). **Swerik collaboration**: annotate interpellation debates.
 
Project: “What will we eat? Food as a security policy issue in Sweden 1900–2025”. PI: Johanna Pettersson Fürst (Uppsala University). Funder: The Swedish Research Council (2023–2027). **Swerik collaboration**: run topic models on parliamentary data.
 
Project: “Extending SWERIK”. PI: Måns Magnusson (Uppsala University). Funder: Centre for Digital Humanities and Social Sciences at Uppsala University (spring of 2024). **Swerik collaboration**: improve the segmentation of Swedish parliamentary speeches 1867–2023.
 
**Collaborations with other research projects:**
 
Project: “Political Representation: Tensions between Parliament and the People from the Age of Revolutions to the 21st Century”. PI: Pasi Ihalainen (Jyväskylä University). Funder: Research Council of Finland (2021–2026). **Swerik collaboration**: use Swerik data for an interface to explore different national parliamentary speeches.
 
Project: “Swedish Parliamentary Debates (SweDeb)”. PI: Fredrik Mohammadi Norén (Malmö University). Funder: Umeå University (2023–2024). **Swerik collaboration**: use Swerik data for an interface to explore different national parliamentary speeches.
 
Project: “Welfare State Analytics. Text Mining and Modeling Swedish Politics, Media & Culture, 1945–1989 (WeStAc)”. PI: Pelle Snickars (Lund University). Funder: The Swedish Research Council (2019–2024). **Swerik collaboration**: the Swerik project originated from the WeStAc project, which also use its parliamentary speech data for research. 
 
Project: “Terrorism in Swedish politics: a multimodal study of the configuration of terrorism in parliamentary debates, legislation, and policy networks in Sweden 1968–2018 (SweTerror)”. PI: Jens Edlund (KTH). Funder: The Swedish Research Council (2021–2024). **Swerik collaboration**: use its parliamentary speech data for research, and help out to improve the speech data and the MP database. 

Project: “A complete dataset of roll-call votes in the Swedish parliament, 1925–2022”. PI: Jan Teorell (Stockholm University). Funder: Riksbankens Jubileumsfond (2023). **Swerik collaboration**: add MP chair metadata and help out to improve party information to the MP database.
 
 
**2. Change name of the tab “Data & Code” to “Data, code & publications”.** When the LREC paper is finished, we will publish it there. Also find a nice way to integrate the Swerik MP catalog https://swerik-project.github.io/person-catalog/ somewhere here too.

**Comment by fredrik1984** [comment]
@ninpnin – when you have time, please make these two changes above on the Swerik web! Let me know if anything is unclear

**Comment by salgo60** [comment]
I added ORCID and WD identifiers see [173#issuecomment-1980316369](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/173#issuecomment-1980316369)

* [ ] **would be great if you added this as open data** -- we could add it to scholia faster
   * authors with Orcid and WD [SPARQL](https://w.wiki/9PDA) / [variant 2](https://w.wiki/9PBy) - [sweriksprojects.csv](https://gist.github.com/salgo60/0a144b98d0abd7abbcb0e58826d4f201#file-sweriksproj_members-csv) [raw](https://gist.githubusercontent.com/salgo60/0a144b98d0abd7abbcb0e58826d4f201/raw/f2e2df7956c9415c6a4ad00b7079501b6d90e4e8/sweriksproj_members.csv)
* [ ] use [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier) for datasets used or planned to be used

**Comment by salgo60** [comment]
@fredrik1984 

You can now connect your GITHUB account to ORCID see [GITHUB blog Authenticate ORCID iD](https://github.blog/changelog/2024-03-13-authenticate-orcid-id/)

example [my profile](https://github.com/salgo60)

<img width="403" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/d0b96c6a-806b-4a87-90f0-b4517611e9ee">
