### ISSUE TITLE
Missing record id

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#485]
I need to extract the record ids from the files. In some files this exist, as it should, as an XML id object in the TEI node:
```<TEI xml:id="prot-1896--ak--42">```

But this is not the case in all records. We should add this to all records and also add a unit test to ensure that it exists throughout.

**Comment by BobBorges** [comment]
It seems like most of the protocols _don't_ have this ID
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/1519024b-8b98-4d13-bf70-bff7476441fb)

**Comment by MansMeg** [comment]
No. Can you add them? I think it is quite easy. Now when you have a test.

**Comment by BobBorges** [comment]
Can you use the head element instead? 
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/8887511/bb50e956-2425-4fdb-bdd4-9608c1d867d4)

This is in every protocol already.

**Comment by MansMeg** [comment]
Hmm. Thats good. I could use that, but then we should rename head to id. The point is that we need a record id and that it is crystal clear that this is the id for the record.

Maybe should we move head to id, or rename head to id?

**Comment by BobBorges** [comment]
head is part of the tei namespace. could be in both places, I guess.

**Comment by MansMeg** [comment]
Yes. I think head is not crystal clear for a record id.

**Comment by MansMeg** [comment]
Or maybe make it even more clear. Can we ad a record_id under head in the preface?

**Comment by ninpnin** [comment]
I think we should use the XML ID attribute of the TEI element for this. See official ParlaClarin example

```xml
<TEI xml:id="document.id" xml:lang="en">
   <teiHeader>
      <fileDesc>
         <titleStmt>
            <!-- There are no rules on how these titles should be written -->
            <title>The parliament of the Republic of Slovenia</title>
            <title>Continuation of the second session</title>
            <title>30th January 2011</title>
```

The head element should be a header for the protocol anyway, but I don't think we need to change it now

```xml
<text>
   <front>
      <div type="preface">
         <!-- text before speeches started -->
         <head>THE PARLIAMENT OF THE REPUBLIC OF SLOVENIA</head>
         <head>Continuation of the second session</head>
         <docDate when="2011-01-30">30th January 2011</docDate>
      </div>
   </front>
   <body>
```

**Comment by MansMeg** [comment]
I think this make sense. I think it is clear that we should XML ID attribute of the TEI element. Good catch there @ninpnin .

**Comment by ninpnin** [comment]
https://github.com/swerik-project/riksdagen-records/pull/4

**Comment by MansMeg** [comment]
Excellent!
