### ISSUE TITLE
Classify written questions

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#49]
In the parliamentary protocols there are not only speeches but also written questions, often formulated by MPs addressing a particular minister. These are called things like "Allmänna frågor", "Anmälan av interpolation" etc. I don't if these are read out loud in the Parliament or if they are just answered by a speech. Either way, we must decide how to handle these questions.

**Comment by MansMeg** [comment]
Indeed. I know that they exist in the speeches from 1991. Maybe check how they are handled there?

**Comment by Stubbendorff** [comment]
it's not always obvious that they are "written" - some could be spoken.

**Comment by fredrik1984** [comment]
I asked Ann Larsson (manager of the protocol writing unit at Riksdagen) about "Allmänna frågor", "Anmälan av interpolation" etc. This is her answer:

"Dina klipp verkar vara från just anmälningstillfället och då säger (anmäler) tjänstgörande talman enbart till exempel ”en interpellation och två skriftliga frågor har inkommit”, liksom man med bordläggning av ärenden enbart säger ”till bordläggning anmäls till kammaren överlämnade propositioner 206 och 207”. I snabbprotokollet dokumenteras detta sedan med beteckning och rubrik, och i det slutliga protokollet publiceras interpellationen eller skriftliga frågan i sin helhet, vilket är det som du har klippt ut."

Hence, these are not read out laud, and should not count as speech. But there is a risk that several of these "Allmänna frågor", "Anmälan av interpolation" etc have been tagged as speeches since they are "introduced" in a similar way as ordinary speeches. We might need to check this, but perhaps not to version 0.3.

<img width="531" alt="Skärmavbild 2021-06-08 kl  11 58 50" src="https://user-images.githubusercontent.com/15212990/121717928-09287c80-cae2-11eb-81e1-347602590d9c.png">
<img width="548" alt="Skärmavbild 2021-06-08 kl  12 00 53" src="https://user-images.githubusercontent.com/15212990/121717948-0cbc0380-cae2-11eb-81c4-2d2c90f3da95.png">

**Comment by MansMeg** [comment]
Great work @fredrik1984 ! Yes, I think this is important to look into. I will change the issue title to reflect this. Also, I agree this is not 0.3.

**Comment by MansMeg** [comment]
Although, we can estimate how large this problem is. How many such cases did we see in the last batch?

**Comment by fredrik1984** [comment]
check #296

**Comment by ninpnin** [comment]
Duplicate
