### ISSUE TITLE
Clarify hashing in documentation + add hash as meta-data per segment

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#5]
If I understand you correctly, we have a solution to the automatic editing v.s. manual editing. I.e. that we will have a hash for each segment, and then if we do an automatic editing, we only do that in segments that match the hash? Then we would update the hash per segment.

I think we would then need:
1) To add an additional attribute: sha1 or similar because we do not want the ids to change over time
2) Document how we compute the hash and check that we have functionality both in R and Python that compute the hash in exactly the same way. I'm a little worried about the white spaces from the XML might create different hashes in R and Python.

Also, we might want to document these three levels of curation:
1) Gold standard
2) Manually curation (hash does not match)
3) Non-curated text
If I understand you correctly?

What do you think?

**Comment by ninpnin** [comment]
Deprecated
