### ISSUE TITLE
Document relevant parts of the corpus

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#52]
We now need a simple way for other researchers (and ourselves) to understand the corpus. We hence need to document the basics before we release it. I guess we want to keep the documentation in the Wiki. I think we need to do the following:

- [x] Add information in the README on where to find the documentation of the corpus
- [x] Document the URL to KB-labb that now is included. How can these pages be accessed?
- [x] What is n = "[hash]" and n="manual" and how does this work? Both for someone that use the corpus and for one that want to curate.
- [x] Document the accuracy for the different variables and how the accuracy were estimated

Maybe we need to document some more, but I think this is the basic stuff that at least I need. Maybe ask @roger-mahler as well?

**Comment by ninpnin** [comment]
The quality control part is documented in the [Wiki](https://github.com/welfare-state-analytics/riksdagen-corpus/wiki/Quality-control) now.

**Comment by ninpnin** [comment]
I also wrote some documentation on automated testing, continuous integration and the hashing system for differentiating manual and automatic curations. It's in the [Wiki](https://github.com/welfare-state-analytics/riksdagen-corpus/wiki/Continuous-integration-and-automatic-tests), too.

**Comment by ninpnin** [comment]
I added a short description of the Betalab links to the _Parla-Clarin Cheat Sheet_ part of the wiki.
