### ISSUE TITLE
Add additional variables to the MP file

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#53]
http://data.riksdagen.se/data/ledamoter/

- [ ] Born (född)
- [ ] Title (titel)

This probably needs a separate files
- [ ] Uppdrag i riksdagen (uppdrag)

**Comment by ninpnin** [comment]
Data sources:
- Riksdagens Öppna data for newer entries
   - A multitude of metadata available
- Statskalender and/or personregister for older entries
  - Birthyear always available, title is often already included in MoP.csv
  - We already have a script that matches the year from personregister, use that

**Comment by rbbby** [comment]
#103 will help

**Comment by ninpnin** [comment]
Done with Wikidata
