### ISSUE TITLE
Solve the issue with non-MP speakers in the parliament

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#57]
Now non-mp talks in the parliament, such as the king, Junilistan and FI EMP that speak in the parliament. Also ministers in the government.

These need to be included in a separate files, such as the MP list but with a different structure.

**Comment by rbbby** [comment]
Margot Wallström was found in the members of parliament dataset and she does not seem to have been a ledamot.

**Comment by ninpnin** [comment]
Merge with #50
