### ISSUE TITLE
Create a python library for reading and writing parlaClarin format

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#58]

**Comment by ninpnin** [comment]
A repository for the code only now exists here: https://github.com/welfare-state-analytics/pyriksdagen. It is possible to include it as a subrepository in this repo, so that we can have the newest version here and in the main repo too.

**Comment by MansMeg** [comment]
This is great, but should we not call it pyparlaclarin instead?

**Comment by MansMeg** [comment]
I think it is great if we would make it more general so others could use it as well?

**Comment by ninpnin** [comment]
Yeah. So the roadmap looks something like this:

- [ ] Do the necessary refactoring in the data repo: change code names to pyparlaclarin and so on
- [ ] Remove the code from the repo, add a reference to this 
- [ ] Upload to PyPi
- [ ] Inform the Parla-Clarin project of our existance

**Comment by MansMeg** [comment]
Yes! I think this is really good!

**Comment by MansMeg** [comment]
@ninpnin should provide a short description on the parlaclarin readme
