### ISSUE TITLE
Deliver a Parla-Clarin corpus of debates 2015–2022 to Maciej Ogrodniczuk

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#59]
Teo wmails from Maciej 2021-06. This should be delivered sometime in 2022. In return he and his Polish colleague can have a look at our tagged corpus.

Email 1:

Dear Fredrik,

we are now thinking about the follow-up of ParlaMint project (https://www.clarin.eu/content/parlamint) which has ended in May. This time we wanted to already put in the proposal the list of languages/people interested in joining in (instead of having a separate (mini-)grant procedure). And since we had 5k€ before, we would probably aim at the same amount for the ‘new’ languages. The money is distributed by CLARIN ERIC directly under CLARIN Resource Families Project Funding.

Do you think you could be interested? I know you have the data until 2019 but I guess there are newer data too. If not you, who do you think would be the best person to be included in the communication and made responsible for the whole process?

Best,
Maciej Ogrodniczuk (also on behalf of Petya Osenova and Tomaz Erjavec)

Email 2:

Hi,
 
we thought you might be interested in being part of our research mini-proposal (‘ParlaMint 2’) which we plan to deliver to CLARIN ERIC. Your main task would be preparation a Parla-CLARIN-encoded (https://github.com/clarin-eric/ParlaMint) corpus of Swedish parliamentary data from 2015 to 2022 which will then join the set of similar corpora we prepared in ParlaMint (https://www.clarin.si/repository/xmlui/handle/11356/1388).
 
Does it clarify the whole thing a bit? Can I count you in?
 
Best,
Maciej

**Comment by MansMeg** [comment]
I think we could start out this autumn and just give them the Parla-Clarin format as of now. Then we can see how much work it would be to convert. Maybe we might go for the ParlaMint format ourselves as well if it is more specific than the ParlaClarin format?

**Comment by fredrik1984** [comment]
Sounds like a plan!

**Comment by ninpnin** [comment]
Covered in the ParlaMint milestone.
