### ISSUE TITLE
How to handle curation of dashes (eg. MAGNUS- SON)?

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#60]
We now have (-) that can cut parts in the text. For example:
"Talmannen MAGNUS- SON"

When we analyze our corpus we would like to have this corrected. The question is how we define the corpus with regard to this? Is this what we should have in the original Parla-Clarin format and help people correct it, or should we remove this kind of typographic errors (for example between pages) in our final corpus?

**Comment by ninpnin** [comment]
Fix merged to _mp_.
