### ISSUE TITLE
Use a fine-tuned BERT for identification of tricky introductions

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#72]
Now more length introductions can be missed in the current algorithms. One way would be to use a BERT model on a small trainings set of positive samples (complicated introductions), then use that to predict new possible introductions. based on these we would then add identified complicated introductions to a new training set and re-train/fine-tune the introductions and continue like that until we have found a couple of thousands of introductions.

**Comment by MansMeg** [comment]
This is now being done as a masters thesis.

**Comment by salgo60** [comment]
@MansMeg maybe another thesis possibility ;-) 

* NER for Swedish PM in museum collection. I have tried to push museum people at Digital museum to do **same as Wikidata** for Swedish PM people see https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/42 a very slow process ☺️ 🐌 🐌 🐌 

[Digitaltmuseums](https://digitaltmuseum.se/) is 90 museums with 2 million photos 

<img width="889" alt="image" src="https://user-images.githubusercontent.com/14206509/166824244-f79ab32d-5a7b-4b43-92c7-3f87357881b7.png">

They have metadata and an API but meta data is rather primitive and text strings....

**Comment by MansMeg** [comment]
It is a little too far away from my work. But they might find the same technique useful.
