### ISSUE TITLE
improve mop mapping with metadata

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#80]
Super issue for what is being worked on in the current patch.

Statskalendern #78 

- [x] Scrape statskalendern for mandate periods and specifiers
- [ ] Impute mop with mandate periods
- [ ] Impute mop with specifiers
- [x] Add missing time periods to mop
- [x] Complement with missing data to mop

Clean name column #77 

- [x] Find incorrectly formatted names
- [ ] Fix the names (add born variable, different names in different times, etc.)

Algorithm bug #76 

- [x] Rewrite the matching algorithm
- [x] Generalize script to match talmän and ministers as well

Impute districts for 1994-1998
The district variable is missing for these years due to special formatting of wikipedia tables.

- [x] Scrape wikipedia and impute districts

Missing intros in 1994-1995
Intros are formatted differently in these years so our algorithm is unable to detect them currently. Write an aggressive algorithm for this and examine further manually.

- [x] Catch intros without ":" @ninpnin 

Improve note/seg classification

- [x] Retrieve manually annotated training/test data
- [ ] Debug data (check that the xml format has not been compromised)
- [ ] Train the algorithm on new data @ninpnin 

Ministers bug
Algorithm for detecting ministers has some minor bugs causing wrong matchings.

- [x] Fix ministers bug @ninpnin

**Comment by ninpnin** [comment]
Things still to be done
- [x] Incorporate exact mandate periods to the actual mop.csv file
- [x] Add remaining statscalendar pages
- [x] Incorporate statscalendar data to mop.csv
