### ISSUE TITLE
Look for errors in MOP

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#81]
Have found at least 1 case where party abbreviation is incorrect in mop.
Look for these kinds of errors by examining people who has more than 1 different party abbreviations and check these.

**Comment by ninpnin** [comment]
Incorrect in what way?

**Comment by rbbby** [comment]
A person was is member of M for a single time point and L for all others. When examining it further it seemed like the correct tag should be M.
