### ISSUE TITLE
detect_mp_new bugs

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#82]
List of found bugs for new version detect_mp, which takes an intro and maps it to the categories: name, gender, party, specifier, other.

- ‘Anf. 166 MARGARETA B KJELLIN (m):’ --> {‘party’: ‘(m)’, ‘name’: ‘MARGARETA’}, since middle names currently are required to be >1 character long.
- '1978/79:' --> wrongfully detected as intro
- '(c):' --> {‘party’: ‘(c)’}, artifact from intro being split over notes, join them back algorithmically over the whole corpus?

**Comment by ninpnin** [comment]
The latter two should be solved upstream.

**Comment by rbbby** [comment]
Regex currently results in: "Herr SJöÖHOLM (fp):" --> "SJ".

**Comment by rbbby** [comment]
OCR error "(5):" should be "(S):", currently not letting us match by party.
