### ISSUE TITLE
Add metadata for Riksmötets öppnande and mandate periods

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#85]
Exact dates for when new members of parliament, ministers and talmän is needed to avoid unnecessary buffering of start-/end-dates and to avoid overlaps. Currently these dates are gathered from metadata tags in the corpus and the use of exact dates is integrated into (at least) the talmän file.

Construct a file containing all of the dates for riksmötets öppnande by gathering data from https://sv.wikipedia.org/wiki/Riksm%C3%B6tets_%C3%B6ppnande.
This should probably be the same file as we will have the mandate periods in.

**Comment by rbbby** [comment]
We have the data now, but wait with implementation til after 0.4.

**Comment by BobBorges** [comment]
Closing: issue taken up more recently in #342
