### ISSUE TITLE
Add metadata on page image from beta-lab

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#9]
- [x] Add as meta-data in the ParlaClarin file
- [ ] Check with KBlab if it is ok to refer to their API. Also, is their API stable enough so we can include URL as data?

Note. I'm not sure how we are going to handle that the pages can start and end in the middle of a paragraph?

**Comment by ninpnin** [comment]
Current status: Waiting for a reply from Martin.
