### ISSUE TITLE
WIkidata same as

### ISSUE THREAD

**Issue by salgo60** [welfare-state-analytics/riksdagen-corpus#95]
I am doing a try matching [corpus/members_of_parliament.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/corpus/members_of_parliament.csv) with [Wikidata](https://www.youtube.com/watch?v=m_9_23jXPoE) 

When I use [Open Refine](https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine) and looks in the file [corpus/members_of_parliament.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/corpus/members_of_parliament.csv) my understanding is that you have one item per person and parlament period  
 
**Question A**: Do you have a file where you have "merged" those items and have one id per person e.g the below id:s looks like same as Wikidata [Q5573455](https://www.wikidata.org/wiki/Q5573455?uselang=sv) [sv:Wikipedia Karl_Bergström](https://sv.wikipedia.org/wiki/Karl_Bergstr%C3%B6m) 
 
 **Question B**: is your modeling documented? In Wikidata we can see challenges when a person is changing party etc...
 
![image](https://user-images.githubusercontent.com/14206509/145179393-2424908d-86a5-4c8c-98ad-24c17811b467.png)

* The ShEx we have for Riksdagsledamöter in Wikidata [EntitySchema:E134](https://www.wikidata.org/wiki/EntitySchema:E134)
* Video when this schema was created "[Wikipedia Weekly Network - Entity Schemas and Shape Expressions (ShEx)](https://www.youtube.com/watch?v=nM8kXuZM3lQ)"

**Comment by MansMeg** [comment]
Hi!

We have an issue on converting this data to a better form (normalized). Although it has not been the main priority yet. I think we are quite open to findibg a good format for this. Now it is just a csv-file.

Although, Im no expert on what would be the best format.

What is important with the format is (as I see it)
1. Having an individual id per person
2. Enable additional meta data, such as gender, party etc, but that this can change over time
3. That we have different metadata for different time periods. 
4. A way to judhe the quality of different meta data.

**Comment by salgo60** [comment]
Ok we can speak about that when we do the demo of Wikidata- I will try to walk through your list and see that every line in your data is matched to a person in Wikidata i.e. it will have a [Wikidata Q number](https://www.youtube.com/watch?v=m_9_23jXPoE) 

The good thing if we get external identififiers [owl:same as](https://www.w3.org/TR/owl-ref/#sameAs-def) in your data --> so that your data is **on level 5** in [5stardata.info ](https://5stardata.info/en/)

<img src="https://user-images.githubusercontent.com/14206509/145350117-4e38e3dc-3346-4a08-b301-7e19afd8e639.png" width="600" />
<img src="https://user-images.githubusercontent.com/14206509/145350152-7d62060e-acc4-4589-bf4c-cc31bb7fb6f4.png" width="600" />

if I do a [SPARQL in Wikidata](https://w.wiki/4XQi) of people with position held ([P39](https://www.wikidata.org/wiki/Property:P39)) 
as member of the Swedish Riksdag [Q10655178](https://www.wikidata.org/wiki/Q10655178) showing external properties --> [SPARQL](https://w.wiki/4XQi) -->

![image](https://user-images.githubusercontent.com/14206509/145348478-305f6422-f027-4b9a-bf3c-3289d6a8904a.png)

we can see that (can be errors in Wikidata)
* [P1214](https://www.wikidata.org/wiki/Property:P1214) "Riksdagens person-id" is a good candidate to be used by people who held a position in the Swedish Government = 1886 people
* [P8388](https://www.wikidata.org/wiki/Property:P8388) "Riksdagen person GUID" is a good candidate = 1878 people
* [P3217](https://www.wikidata.org/wiki/Property:P3217) "Svenskt Biografiskt Lexikon-ID" is a good candidate = 1002 people
* [P4963](https://www.wikidata.org/wiki/Property:P4963) "Svenskt kvinnobiografiskt lexikon" maybe = 79 people

I guess you could structure your data as [Litteraturbanken](https://litteraturbanken.se/)  has done [in the API](https://litteraturbanken.se/api/get_authors)
* example August Strindberg Litteraturbanken [https://litteraturbanken.se/api/get_author/StrindbergA](https://litteraturbanken.se/api/get_author/StrindbergA) 

![image](https://user-images.githubusercontent.com/14206509/145349704-66faac1c-9e26-459b-b4e0-f1ccb325714d.png)

My understanding is that they take all the data from Wikidata -->
1. The Wikidata Qnumber in **"wikidata_id"** = [Q7724](https://www.wikidata.org/wiki/Q7724)
2.  **"sbl_link"** is what we call P3217 and for Strindberg is [34518](https://sok.riksarkivet.se/sbl/Presentation.aspx?id=34518) i.e.  the key to [SBL](https://sok.riksarkivet.se/sbl/Presentation.aspx?id=34518) "Riksarkivet Svenskt Biografiskt Lexikon"

Example search of people in the Swedish parlament on Wikidata 
1) with SBL P3217 [query](https://w.wiki/4XRG) (same [query but link sv:Wikipedia](https://w.wiki/4XRH) )
2) with  [P8388](https://www.wikidata.org/wiki/Property:P8388) "Swedish Parliament person GUID" [query](https://w.wiki/4XRL)
![image](https://user-images.githubusercontent.com/14206509/145356677-bf584f3c-a6c0-4049-ac97-1920f7c37b96.png)

**Lets talk more!!!**

**Comment by salgo60** [comment]
FYI: I created a repository for the matching activity see [salgo60/Wikidata_riksdagen-corpus](https://github.com/salgo60/Wikidata_riksdagen-corpus) (will take 1-2 weeks)

**Comment by salgo60** [comment]
Wikidata related
* see GITHUB https://github.com/every-politician-scrapers/sweden-riksdag-api-current and last [commit](https://github.com/every-politician-scrapers/sweden-riksdag-api-current/commit/2b1bcc494e21659200de93e17d1450ac3178502d) how this user scrape Swedish Riksdagen to find differences his last [commit](https://github.com/every-politician-scrapers/sweden-riksdag-api-current/commit/2b1bcc494e21659200de93e17d1450ac3178502d) 
** every-politician-scrapers has [152 repositories](https://github.com/every-politician-scrapers) so I guess its for 152 countries he is doing it see Wikidata project space [Wikidata:WikiProject_every_politician](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician)

**Match with Wikidata**
* I did a small test 3000 lines doing a reconciliation with Wikidata and added some fields when exporting it see [news](https://github.com/salgo60/Wikidata_riksdagen-corpus) and the test [members_of_parliament WD 20211217.csv](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/members_of_parliament%20WD%2020211217.csv)   

**Question** What data would you like from Wikidata

**Comment by BobBorges** [comment]
Implemented? pls close

**Comment by MansMeg** [comment]
Yes. This can be closed now.
