### ISSUE TITLE
1921 should be 1920

### ISSUE THREAD

**Issue by Stubbendorff** [welfare-state-analytics/riksdagen-corpus#98]
1921 should be 1920 (1920-2020) - change it where we present the corpus - in headlines as well as introducing texts

**Comment by ninpnin** [comment]
Thanks @Stubbendorff for fixing this!

**Comment by MansMeg** [comment]
Has @Stubbendorff fixed this in a PR? I though he just opened an issue?

**Comment by ninpnin** [comment]
@MansMeg https://github.com/welfare-state-analytics/riksdagen-corpus/commit/fef1a82cfc3b1b3ed9473188549368aef0521f94

**Comment by MansMeg** [comment]
Cool!
